### ISSUE TITLE
[Bug]: [chaos][querynode]Search hangs after deleting querynode pod failure chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#12190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:`0f2b7d1`
- Deployment mode(standalone or cluster): cluster with 2 querynode
- SDK version(e.g. pymilvus v2.0.0rc2):2.0.0rc9.dev13
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

after delete chaos, search hangs

### Expected Behavior

all operations works well

### Steps To Reproduce

```markdown
cd `tests/python_client/chaos`

modify params:
pod="querynode"
chaos_type="pod_failure"
chaos_task="chaos-test"

run script `bash chaos_test.sh`
```

### Anything else?

before injecting chaos, collection `hello_milvus` was not released
[querynode-pod-failure-11-22-20-54-00.zip](https://github.com/milvus-io/milvus/files/7581113/querynode-pod-failure-11-22-20-54-00.zip)

**Comment by binbinlv** [comment]
@czs007 hello, zhenshan, could you help to assign this issue? Thanks

**Comment by czs007** [comment]
@xiaocai2333 is working on this.

**Comment by xige-16** [comment]
similar with #11275 , the probelem of search hang may has been fixed

**Comment by xige-16** [comment]
> similar with #11275 , the probelem of search hang may has been fixed

There is indeed a problem when recover querynode. If a querynode only watchDmchannel without load segment, dmchannel is not scheduled to other nodes when the query node down.

**Comment by xiaocai2333** [comment]
![image](https://user-images.githubusercontent.com/46207236/143242616-45a28938-1543-409e-b284-e28d6e79ba14.png)

![image](https://user-images.githubusercontent.com/46207236/143242914-55f0726e-23c8-403c-8e74-ef8dec08d367.png)

If a querynode only watches the DMchannel, the partition-related information will not be recorded by it, but the querycoord recovers the querynode by partitions, so the DMchannel corresponding to the down querynode will not be subscribed by other serviceable querynodes.

**Comment by xige-16** [comment]
I'll fix it

**Comment by zhuwenxing** [comment]
In version `master-20211130-2a0d646`, this issue is not reproduced.
But I didn't notice any PR to fix this issue.
[querynode-pod_failure-chaos-test-2021-11-30-15-27-54.zip](https://github.com/milvus-io/milvus/files/7623784/querynode-pod_failure-chaos-test-2021-11-30-15-27-54.zip)

**Comment by zhuwenxing** [comment]
The issue happens in `63ead50`.
@xige-16  Please check whether it is the same cause
[test-querynode-pod-failure.zip](https://github.com/milvus-io/milvus/files/7689834/test-querynode-pod-failure.zip)

**Comment by xige-16** [comment]
> 

Dmchannl recover failed when the querynode down

**Comment by xige-16** [comment]
The issue should has been fixed by pr #13543, trouble you check it. @zhuwenxing

**Comment by zhuwenxing** [comment]
Search hangs still exist!
[test-querynode-pod-failure-12-22-10-54-00.zip](https://github.com/milvus-io/milvus/files/7759674/test-querynode-pod-failure-12-22-10-54-00.zip)

[test-querynode-pod-kill-12-22-10-34-00.zip](https://github.com/milvus-io/milvus/files/7759676/test-querynode-pod-kill-12-22-10-34-00.zip)

**Comment by zhuwenxing** [comment]
Verified and passed in version `595692c`
check https://github.com/zhuwenxing/milvus/actions/runs/1610606525 and https://github.com/zhuwenxing/milvus/actions/runs/1610494488  for detail
