### ISSUE TITLE
[Bug]: collection.delete can't delete entity

### ISSUE THREAD

**Issue by liuhaiweicheer** [milvus-io/milvus#15201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.0.0-PreGA
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc9):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

con = Collection(name='qa_cp')
expr = "id in [ 430408969516748387, 430408969516748434, 430408969516748379 ]"
res =  con.delete(expr)

(insert count: 0, delete count: 3, upsert count: 0, timestamp: 430458026279829505)
[430408969516748387, 430408969516748434, 430408969516748379]

### Expected Behavior

I try to delete entity ,it is show delete.  but I  can search those,Do not know this is what reason

**Comment by liuhaiweicheer** [comment]
> @liuhaiweicheer Please try to wait for a few seconds before searching. Check #15101
> 
> /assign @liuhaiweicheer /unassign

I  wait for a few seconds before searching  can not search them, But delete the entity before it can be searced again after an hour .

**Comment by liuhaiweicheer** [comment]
@yanliang567
 I wait for a few seconds before searching can not search them, But delete the entity before it can be searced again after an hour .

After I manually executed the connection.compact() method, the the delete entity can not search,  Do I not understand why.

**Comment by yanliang567** [comment]
@liuhaiweicheer do you mean the deleted entities were able to be searched again after an hour?

**Comment by liuhaiweicheer** [comment]
@yanliang567 yes

**Comment by xiaofan-luan** [comment]
> @yanliang567 yes

Need to investigate on that, do we have any test cases to reproduce the issue?

**Comment by liuhaiweicheer** [comment]
@ @yanliang567 @xiaofan-luan 
I'm using the robot question answering system,  https://github.com/milvus-io/bootcamp/blob/master/solutions/question_answering_system/question_answering.ipynb. this is my methods.

When searching for a question, we first put the question through the same model to generate an embedding.   Then with that embedding vector we can search for similar embeddings in Milvus.

The query invalidation problem was found in this query method.

**Comment by yanliang567** [comment]
@liuhaiweicheer could you please upload the Milvus logs to help us address the issue?

**Comment by XuanYang-cn** [comment]
@liuhaiweicheer Please try Milvus2.0.0 and PyMilvus2.0.0. https://github.com/milvus-io/pymilvus/blob/2.0/examples/hello_milvus.ipynb

**Comment by excited-tiger** [comment]
I have save issue 
examples/hello_milvus.py  cannot work too.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/44421536/152676018-193dd58b-34e0-4945-a091-e5d81f4c1f69.png">

**environment:**
Milvus version: v2.0.0

**Comment by yanliang567** [comment]
@excited-tiger collection.num_entities() is not precise especially after delete ops.  But I believe that the deleted vectors are not available for search/query if you are in strong consistency level.  More info about consistency level: https://github.com/milvus-io/milvus/blob/master/docs/developer_guides/how-guarantee-ts-works.md

**Comment by excited-tiger** [comment]
> @excited-tiger collection.num_entities() is not precise especially after delete ops. But I believe that the deleted vectors are not available for search/query if you are in strong consistency level. More info about consistency level: https://github.com/milvus-io/milvus/blob/master/docs/developer_guides/how-guarantee-ts-works.md

thanks

**Comment by yanliang567** [comment]
@liuhaiweicheer could you please retry with milvus 2.0 release, we believe it was fixed in 2.0 release.

**Comment by excited-tiger** [comment]
yes, 
**Environment**
milvusdb/milvus:v2.0.0
pymilvus==2.0.0
collection.num_entities()  is still not precise after delete ops

I didn't find the **update** interface, so I replaced it with a delete and insert interface, but delete cannot worked, do you know some efficient ways?

**Comment by yanliang567** [comment]
@excited-tiger I think you need to set the collection consistency level to strong. Here is a blog that might help you: https://milvus.io/blog/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md

**Comment by xiaofan-luan** [comment]
collection.num_entities won‘t be exact matching until compaction I guess. 
If you delete entity and wait for a couple of seconds the entity should be invisible

**Comment by excited-tiger** [comment]
> @excited-tiger I think you need to set the collection consistency level to strong. Here is a blog that might help you: https://milvus.io/blog/2022-1-27-milvus-2-0-a-glimpse-at-new-features.md

thanks!

1. it's my fault. i found that :**the deletion within Milvus is asynchronous and logical, which means that entities won't be physically deleted.** 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/44421536/152732315-dc065b57-e7c4-46c0-9be6-86445108da5d.png">
and insert the same id as the primary key can be treated as updating the id data.

2. I found a bug:
when i use `partition.delete(expr)`
`AttributeError: 'Partition' object has no attribute '_partition_name'`
it worked with that: 
`collection.delete(expr, partition_name=partition_name)`

**Comment by yanliang567** [comment]
@excited-tiger great~ about the #2 issue, could you please file a new ticket, we would fix it ASAP

**Comment by XuanYang-cn** [comment]
It's fixed at https://github.com/milvus-io/pymilvus/commit/ac8c221c11d77cceb7b5af611457149e933dba85
