### ISSUE TITLE
[Bug]: Load balance failed when replica_number is larger than 1

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220424-5c663004
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):2.1.0.dev33
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The error message is ` unloaded segment 432747788991201281`, but `sealed_segment_ids` is from the return results of `get_query_segment_info(c_name)`,  so it should be loaded.

```
[2022-04-24 20:03:34 - DEBUG - ci_test]: (api_request)  : [load_balance] args: ['utility_VMloZb5v', 10, [9, 7, 12], [432747788991201281, 432747788991201282], 20, 'default'], kwargs: {} (api_request.py:55)
[2022-04-24 20:03:34 - ERROR - pymilvus.decorators]: RPC error: [load_balance], <MilvusException: (code=1, message=, loadBalanceTask: unloaded segment 432747788991201281)>, <Time:{'RPC start': '2022-04-24 20:03:34.290697', 'RPC error': '2022-04-24 20:03:34.342580'}> (decorators.py:73)
[2022-04-24 20:03:34 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
    res = func(*args, **kwargs)
  File "/Users/zilliz/workspace/backup/milvus/tests/python_client/utils/api_request.py", line 56, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/orm/utility.py", line 548, in load_balance
    return _get_connection(using).load_balance(collection_name, src_node_id, dst_node_ids, sealed_segment_ids, timeout)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/opt/anaconda3/envs/milvus/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 1086, in load_balance
    raise MilvusException(status.error_code, status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, loadBalanceTask: unloaded segment 432747788991201281)>
 (api_request.py:35)

```

### Expected Behavior

load-balance success.

### Steps To Reproduce

```markdown
@pytest.mark.tags(CaseLabel.L3)
    def test_load_balance_in_one_group(self):
        """
        target: test load balance of collection in one group
        method: init a collection, load with multi replicas and load balance among the querynodes in one group
        expected: load balance successfully
        """
        # init a collection
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        ms = MilvusSys()
        nb = 3000
        df = cf.gen_default_dataframe_data(nb)
        collection_w.insert(df)
        # get sealed segments
        collection_w.num_entities
        collection_w.load(replica_number=2)
        # get growing segments
        collection_w.insert(df)
        # get replicas information
        res, _ = collection_w.get_replicas()
        # prepare load balance params
        # find a group which has multi nodes
        group_nodes = []
        for g in res.groups:
            if len(g.group_nodes) >= 2:
                group_nodes = list(g.group_nodes)
                break
        src_node_id = group_nodes[0]
        dst_node_ids = group_nodes[1:]
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
        # load balance
        self.utility_wrap.load_balance(collection_w.name, src_node_id, dst_node_ids, sealed_segment_ids)
        # get segments distribution after load balance
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        sealed_segment_ids_after_load_banalce = segment_distribution[src_node_id]["sealed"]
        # assert
        assert sealed_segment_ids_after_load_banalce == []
        des_sealed_segment_ids = []
        for des_node_id in dst_node_ids:
            des_sealed_segment_ids += segment_distribution[des_node_id]["sealed"]
        # assert sealed_segment_ids is subset of des_sealed_segment_ids
        assert set(sealed_segment_ids).issubset(des_sealed_segment_ids)
```
```


### Anything else?


collection name:utility_VMloZb5v
log:[pod_log.zip](https://github.com/milvus-io/milvus/files/8549686/pod_log.zip)

**Comment by zhuwenxing** [comment]
It still have issue in version `master-20220505-333b439a`
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=, no available queryNode to allocate)>
 (api_request.py:35)
[2022-05-07 19:06:03 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=, no available queryNode to allocate)> (api_request.py:36)
```

client log:
[2022-05-07-19-10-04.zip](https://github.com/milvus-io/milvus/files/8645005/2022-05-07-19-10-04.zip)

server log:
[test-multi-replicas-05-07-19-19.zip](https://github.com/milvus-io/milvus/files/8645008/test-multi-replicas-05-07-19-19.zip)

**Comment by yah01** [comment]
Hi @zhuwenxing,
this has been fixed with #16921

**Comment by yah01** [comment]
hi @zhuwenxing 
A new PR has been merged, please check this

**Comment by zhuwenxing** [comment]
In version `master-20220518-b9568177`, the issue is still here
server log:
[test-multi-replicas-05-19-13-45.zip](https://github.com/milvus-io/milvus/files/8725385/test-multi-replicas-05-19-13-45.zip)

client log:
```
------------------------------------------------------------------------------------------------------------ live log setup ------------------------------------------------------------------------------------------------------------
[2022-05-19 13:38:14 - INFO - ci_test]: ################################################################################ (conftest.py:168)
[2022-05-19 13:38:14 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:169)
[2022-05-19 13:38:14 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:30)
[2022-05-19 13:38:14 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)
[2022-05-19 13:38:14 - INFO - ci_test]: [setup_method] Start setup test case test_load_balance_in_one_group. (client_base.py:37)
------------------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------------------
[2022-05-19 13:38:23 - INFO - ci_test]: before load balance, the segment distribution is defaultdict(<function get_segment_distribution.<locals>.<lambda> at 0x7fee596f5790>, {4: {'growing': [], 'sealed': [433307961607323649, 433307961607323650]}, 3: {'growing': [], 'sealed': [433307961607323649, 433307961607323650]}}) (test_utility.py:1702)
[2022-05-19 13:38:23 - INFO - ci_test]: load balance segments [433307961607323649, 433307961607323650] of collection utility_AoHtRSbn from node 3 to [5, 6] (test_utility.py:1705)
[2022-05-19 13:38:24 - INFO - ci_test]: after load balance, the segment distribution is defaultdict(<function get_segment_distribution.<locals>.<lambda> at 0x7fee596f5af0>, {5: {'growing': [], 'sealed': [433307961607323649, 433307961607323650]}, 3: {'growing': [], 'sealed': [433307961607323649, 433307961607323650]}, 4: {'growing': [], 'sealed': [433307961607323649, 433307961607323650]}}) (test_utility.py:1710)


―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― TestUtilityAdvanced.test_load_balance_in_one_group ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

self = <test_utility.TestUtilityAdvanced object at 0x7fee68a3aa30>

    @pytest.mark.tags(CaseLabel.L3)
    def test_load_balance_in_one_group(self):
        """
        target: test load balance of collection in one group
        method: init a collection, load with multi replicas and load balance among the querynodes in one group
        expected: load balance successfully
        """
        # init a collection
        c_name = cf.gen_unique_str(prefix)
        collection_w = self.init_collection_wrap(name=c_name)
        ms = MilvusSys()
        nb = 3000
        df = cf.gen_default_dataframe_data(nb)
        collection_w.insert(df)
        # get sealed segments
        collection_w.num_entities
        collection_w.load(replica_number=2)
        # get growing segments
        collection_w.insert(df)
        # get replicas information
        res, _ = collection_w.get_replicas()
        # prepare load balance params
        # find a group which has multi nodes
        group_nodes = []
        for g in res.groups:
            if len(g.group_nodes) >= 2:
                group_nodes = list(g.group_nodes)
                break
        src_node_id = group_nodes[0]
        dst_node_ids = group_nodes[1:]
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        log.info(f"before load balance, the segment distribution is {segment_distribution}")
        sealed_segment_ids = segment_distribution[src_node_id]["sealed"]
        # load balance
        log.info(f"load balance segments {sealed_segment_ids} of collection {collection_w.name} from node {src_node_id} to {dst_node_ids}")
        self.utility_wrap.load_balance(collection_w.name, src_node_id, dst_node_ids, sealed_segment_ids)
        # get segments distribution after load balance
        res, _ = self.utility_wrap.get_query_segment_info(c_name)
        segment_distribution = cf.get_segment_distribution(res)
        log.info(f"after load balance, the segment distribution is {segment_distribution}")
        sealed_segment_ids_after_load_banalce = segment_distribution[src_node_id]["sealed"]
        # assert
>       assert sealed_segment_ids_after_load_banalce == []
E       assert [433307961607323649, 433307961607323650] == []
E         Left contains 2 more items, first extra item: 433307961607323649
E         Full diff:
E         - []
E         + [433307961607323649, 433307961607323650]

testcases/test_utility.py:1713: AssertionError

```

**Comment by zhuwenxing** [comment]
in version `master-20220519-e05cfe19`, if we sleep 10s after load balance, the segments seem still in the source node.
```
[2022-05-19 19:57:50 - INFO - ci_test]: ################################################################################ (conftest.py:168)
[2022-05-19 19:57:50 - INFO - ci_test]: [initialize_milvus] Log cleaned up, start testing... (conftest.py:169)
[2022-05-19 19:57:50 - INFO - ci_test]: [setup_class] Start setup class... (client_base.py:30)
[2022-05-19 19:57:50 - INFO - ci_test]: *********************************** setup *********************************** (client_base.py:36)
[2022-05-19 19:57:50 - INFO - ci_test]: [setup_method] Start setup test case test_load_balance_in_one_group. (client_base.py:37)
------------------------------------------------------------------------------------------------------------ live log call -------------------------------------------------------------------------------------------------------------
[2022-05-19 19:58:05 - INFO - ci_test]: before load balance, the segment distribution is defaultdict(<function get_segment_distribution.<locals>.<lambda> at 0x7f9a9200d700>, {23: {'growing': [], 'sealed': [433313932933595137, 433313932933595138]}, 26: {'growing': [], 'sealed': [433313932933595137, 433313932933595138]}}) (test_utility.py:1702)
[2022-05-19 19:58:05 - INFO - ci_test]: load balance segments [433313932933595137, 433313932933595138] of collection utility_q6yUT51R from node 26 to [25, 24] (test_utility.py:1705)
[2022-05-19 19:58:06 - INFO - ci_test]: sleep some time to wait (test_utility.py:1707)
[2022-05-19 19:58:16 - INFO - ci_test]: sleep done (test_utility.py:1710)
[2022-05-19 19:58:16 - INFO - ci_test]: after load balance, the segment distribution is defaultdict(<function get_segment_distribution.<locals>.<lambda> at 0x7f9a9200dc10>, {23: {'growing': [], 'sealed': [433313932933595137, 433313932933595138]}, 26: {'growing': [], 'sealed': [433313932933595137, 433313932933595138]}, 25: {'growing': [], 'sealed': [433313932933595137, 433313932933595138]}}) (test_utility.py:1713)

```

client log: 
[2022-05-19-19-57.zip](https://github.com/milvus-io/milvus/files/8728900/2022-05-19-19-57.zip)
server log:
[test-multi-replicas-05-19-19-59.zip](https://github.com/milvus-io/milvus/files/8728916/test-multi-replicas-05-19-19-59.zip)

**Comment by yanliang567** [comment]
@yah01 any updates

**Comment by yah01** [comment]
@zhuwenxing 
this should be totally fixed by #17190 which just been merged
