### ISSUE TITLE
[Bug]: Load failed after Milvus upgrading

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:v2.0.2 --> master-20220507-c7935d1a
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev47
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

collection `task_2_IVF_PQ` load failed, but the previous one `task_2_ANNOY` successed

```
Traceback (most recent call last):
  File "action_after_upgrade.py", line 94, in <module>
    task_2(data_size, host)
  File "action_after_upgrade.py", line 33, in task_2
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 142, in load_and_search
    c.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 449, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 716, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 727, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 756, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 735, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection 43305033735838[1057](https://github.com/milvus-io/milvus/runs/6336709711?check_suite_focus=true#step:9:1057) has not been loaded to memory or load failed)>
```

### Expected Behavior

works well

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6336709711?check_suite_focus=true
```

### Anything else?

job: https://github.com/milvus-io/milvus/runs/6336709711?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6415795593/artifacts/234072629

**Comment by zhuwenxing** [comment]
This issue will appear steadily, so increase the critical level

The latest failed job: https://github.com/milvus-io/milvus/runs/6413296020?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6486637327/artifacts/240554490
```
load collection
Traceback (most recent call last):
  File "action_after_upgrade.py", line 94, in <module>
    task_2(data_size, host)
  File "action_after_upgrade.py", line 33, in task_2
    load_and_search(prefix)
  File "/home/runner/work/milvus/milvus/tests/python_client/deploy/scripts/utils.py", line 142, in load_and_search
    c.load()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 451, in load
    conn.load_collection(self._name, timeout=timeout, replica_number=replica_number, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 736, in load_collection
    self.wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 747, in wait_for_loading_collection
    return self._wait_for_loading_collection(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 776, in _wait_for_loading_collection
    progress = self.get_collection_loading_progress(collection_name, timeout)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 755, in get_collection_loading_progress
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=collection task_2_RHNSW_PQ has not been loaded to memory or load failed)>
```

**Comment by zhuwenxing** [comment]
It still happens, but it only for docker-compose
https://github.com/milvus-io/milvus/runs/6496690493?check_suite_focus=true

**Comment by sunby** [comment]
@zhuwenxing Fixed in https://github.com/milvus-io/milvus/pull/17132. Please verify it.

**Comment by zhuwenxing** [comment]
It still failed in version `d28a2db4` built in `Sun May 22 12:09:43 UTC 2022`
https://github.com/milvus-io/milvus/runs/6546104459?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6611384373/artifacts/248750417

/unassign 
/assign @sunby

**Comment by zhuwenxing** [comment]
failed job: https://github.com/zhuwenxing/milvus/runs/6589976754?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/6652378448/artifacts/251439696

**Comment by xiaocai2333** [comment]
The latest issue same as #16265 .

**Comment by zhuwenxing** [comment]
If add sleep time between two deployments, this issue will not happen.
see https://github.com/zhuwenxing/milvus/runs/6602863639?check_suite_focus=true.

So the problem may be that while the index creation task was running in the background, the Milvus upgrade interrupted the task, and after the upgrade, the failed index creation task did not resume, causing the load to fail.

But add some waiting time, wait for the background tasks to finish, then upgrade, and this issue will not happen.

**Comment by zhuwenxing** [comment]
> If add sleep time between two deployments, this issue will not happen. see https://github.com/zhuwenxing/milvus/runs/6602863639?check_suite_focus=true.
> 
> So the problem may be that while the index creation task was running in the background, the Milvus upgrade interrupted the task, and after the upgrade, the failed index creation task did not resume, causing the load to fail.
> 
> But add some waiting time, wait for the background tasks to finish, then upgrade, and this issue will not happen.


@yanliang567 
@xiaofan-luan 

Do you think this issue is still a bug? Can it be closed?
It should be reasonable to wait for background tasks to finish before upgrading.
The point that could be optimized is to provide an interface that tells the user whether there are background tasks currently executing and whether the upgrade operation can be performed.

**Comment by yanliang567** [comment]
@zhuwenxing what happens if a unscheduled reboot occurs instead of a planned upgrade? Also we are using k8s to upgrade milvus image, so I don't think it would be gracefully wait for the background tasks. In short, i think this is a bug and we shall fix it.

**Comment by zhuwenxing** [comment]
> @zhuwenxing what happens if a unscheduled reboot occurs instead of a planned upgrade? Also we are using k8s to upgrade milvus image, so I don't think it would be gracefully wait for the background tasks. In short, i think this is a bug and we shall fix it.


This should have been fixed in master branch

**Comment by xiaocai2333** [comment]
> @zhuwenxing what happens if a unscheduled reboot occurs instead of a planned upgrade? Also we are using k8s to upgrade milvus image, so I don't think it would be gracefully wait for the background tasks. In short, i think this is a bug and we shall fix it.

This bug is on v2.0.2, fix it on v2.0.2? @yanliang567

**Comment by yanliang567** [comment]
I think we could cherry pick the fix to 2.0.3 branch, if it is not complicated.
