### ISSUE TITLE
[Bug]: Search failed with error `fail to get shard leaders from QueryCoord: no replica available` after querynode pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#16900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220510-4ee78eb5
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev50
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search raise error when running hello_milvus.py after chaos.
```
Search...
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 114, in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 87, in hello_milvus
    res = collection.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 687, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line [41](https://github.com/milvus-io/milvus/runs/6375826869?check_suite_focus=true#step:14:41), in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 497, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 444, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line [43](https://github.com/milvus-io/milvus/runs/6375826869?check_suite_focus=true#step:14:43)5, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to get shard leaders from QueryCoord: no replica available)>
```

### Expected Behavior

all test case passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6375826869?check_suite_focus=true
```

### Anything else?

failed job: https://github.com/milvus-io/milvus/runs/6375826869?check_suite_focus=true
log: https://github.com/milvus-io/milvus/suites/6451788873/artifacts/236534825

**Comment by zhuwenxing** [comment]
It seems similar to https://github.com/milvus-io/milvus/issues/16941.

The following cases also have this issue
* standalone pod kill: https://github.com/milvus-io/milvus/runs/6393914499?check_suite_focus=true
* all cluster pod kill: https://github.com/milvus-io/milvus/runs/6393914403?check_suite_focus=true

But I think the root cause should be querynode pod kill.

**Comment by zhuwenxing** [comment]
It was blocked by https://github.com/milvus-io/milvus/issues/17016 when verifying it.
Before search, load has already failed, so we can't check the behavior of search

**Comment by zhuwenxing** [comment]
/unassign 

It was still blocked by https://github.com/milvus-io/milvus/issues/17016

**Comment by zhuwenxing** [comment]
After https://github.com/milvus-io/milvus/issues/17016 is fixed, all test cases passed for querynode pod kill chaos.
see https://github.com/milvus-io/milvus/runs/6614655517?check_suite_focus=true

This issue also has not happened, so remove the critical label, but leave it open and keep watching for a while.

**Comment by yanliang567** [comment]
close for now, please feel feel to reopen it still reproduced.
