### ISSUE TITLE
[Bug]: Search failed with error message `fail to Search, QueryNode ID=11, reason=channel  xxx leader is not here` after querynode pod failure chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220524-75ca64f8
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev61
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

search raise error when running `hello_milvus.py` after querynode pod failure chaos
collection name: `hello_milvus`

```
Search...
Traceback (most recent call last):
  File "chaos/scripts/hello_milvus.py", line 116, in <module>
    hello_milvus(args.host)
  File "chaos/scripts/hello_milvus.py", line 89, in hello_milvus
    res = collection.search(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 690, in search
    res = conn.search(self._name, data, anns_field, param, limit, expr,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 56, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 41, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 21, in handler
    return func(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 446, in search
    return self._execute_search_requests(requests, timeout, **_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 74, in handler
    raise e
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/decorators.py", line 70, in handler
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
    raise pre_err
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests
    raise MilvusException(response.status.error_code, response.status.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=11, reason=channel by-dev-rootcoord-dml_3_4334345615156[183](https://github.com/milvus-io/milvus/runs/6580336466?check_suite_focus=true#step:12:184)05v1 leader is not here)>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see https://github.com/milvus-io/milvus/runs/6580336466?check_suite_focus=true
```

### Milvus Log

failed job: https://github.com/milvus-io/milvus/runs/6580336466?check_suite_focus=true
logs: https://github.com/milvus-io/milvus/suites/6643359954/artifacts/250852121

failed job: https://github.com/milvus-io/milvus/runs/6561733951?check_suite_focus=true
logs: https://github.com/milvus-io/milvus/suites/6626010646/artifacts/249719586

### Anything else?

This issue happened in recent two days, it works well in version `master-20220522-d28a2db4`

**Comment by zhuwenxing** [comment]
It passed when running `test_e2e.py` after chaos but failed when running `hello_milvus.py`.
so it works well for the new collection, but not well for the old collections.

**Comment by yanliang567** [comment]
@congqixia could you please help to take a look at this issue?

/assign @congqixia 
/unassign

**Comment by zhuwenxing** [comment]
This issue is stably reproduced.
https://github.com/milvus-io/milvus/runs/6598903599?check_suite_focus=true

**Comment by congqixia** [comment]
Looks like the Shard leader inconsistent issue, maybe fixed by #17218

**Comment by yanliang567** [comment]
@zhuwenxing please help to retry with the pr above

**Comment by zhuwenxing** [comment]
It still happened in the latest version `master-20220526-3a63d6c9`
see https://github.com/milvus-io/milvus/runs/6615360839?check_suite_focus=true

**Comment by ownbylichaobao** [comment]
same problem,

**Comment by zhuwenxing** [comment]
I have tried twice, but none of them reproduces the problem.
The Milvus version is `master-20220527-73187021`.

https://github.com/milvus-io/milvus/runs/6648714345?check_suite_focus=true
https://github.com/zhuwenxing/milvus/runs/6648173556?check_suite_focus=true

**Comment by zhuwenxing** [comment]
Not reproduced yet, so close it.

**Comment by zhuwenxing** [comment]
This happened again, so reopen it.

Failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6505/pipeline
log: [artifacts-querynode-pod-failure-6505-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8905451/artifacts-querynode-pod-failure-6505-server-logs.tar.gz)

The search failed when running `hello_milvus.py`, error log:
```
22:13:15  Search...
22:13:15  Traceback (most recent call last):
22:13:15    File "scripts/hello_milvus.py", line 116, in <module>
22:13:15      hello_milvus(args.host)
22:13:15    File "scripts/hello_milvus.py", line 91, in hello_milvus
22:13:15      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 690, in search
22:13:15      partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
22:13:15      raise e
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
22:13:15      return func(self, *args, **kwargs)
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
22:13:15      raise e
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
22:13:15      return func(*args, **kwargs)
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 449, in search
22:13:15      return self._execute_search_requests(requests, timeout, **_kwargs)
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
22:13:15      raise e
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
22:13:15      return func(*args, **kwargs)
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
22:13:15      raise pre_err
22:13:15    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests
22:13:15      raise MilvusException(response.status.error_code, response.status.reason)
22:13:15  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=7, reason=channel by-dev-rootcoord-dml_2_433904833421115393v0 leader is not here)>
```

**Comment by zhuwenxing** [comment]
/assign @letian-jiang 
Please help to take a look

**Comment by letian-jiang** [comment]
Maybe fixed by #17560, please have it a verify
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
It still happened in version `master-20220616-53a49a92`

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6587/pipeline
log: [artifacts-querynode-pod-failure-6587-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8923941/artifacts-querynode-pod-failure-6587-server-logs.tar.gz)

**Comment by congqixia** [comment]
@zhuwenxing #17608 might fix this problem. Does this issue still persist in latest master version?

**Comment by zhuwenxing** [comment]
> @zhuwenxing #17608 might fix this problem. Does this issue still persist in latest master version?

I will check it soon

**Comment by zhuwenxing** [comment]
a failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6920/pipeline

but the error message is changed to `fail to Search, QueryNode ID=6, reason=ShardCluster for by-dev-rootcoord-dml_3_434053604802560001v1 replicaID 434053592586911766 is no available`

may related to https://github.com/milvus-io/milvus/issues/17627

**Comment by yah01** [comment]
It looks like QueryNode processes handoff request with the segments' NodeID, which is deprecated

**Comment by zhuwenxing** [comment]
It would be better to discuss the new issue at https://github.com/milvus-io/milvus/issues/17627.

And I would like to remove the critical label for this origin isssue

**Comment by zhuwenxing** [comment]
Not reproduced  yet with the error message `fail to Search, QueryNode ID=11, reason=channel xxx leader is not here`
