### ISSUE TITLE
[Bug]: Search failed when running `verify_all_collections.py` with error `fail to get shard leaders from QueryCoord: no replica available` after Milvus recovered from querynode pod kill chaos 

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20220614-f9553970
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.1.0.dev69
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Search failed when running `verify_all_collections.py`
```
21:34:47  check collection Checker__GXVbNbit
21:34:47  collection is exist
21:34:47  
21:34:47  Create collection...
21:34:47  
21:34:47  Insert 3000 vectors cost 0.2313 seconds
21:34:47  
21:34:47  Get collection entities...
21:34:47  6000
21:34:47  
21:34:47  Get collection entities cost 3.0336 seconds
21:34:47  
21:34:47  Create index...
21:34:47  
21:34:47  Create index cost 3.6182 seconds
21:34:47  
21:34:47  load collection...
21:34:47  
21:34:47  load collection cost 0.0094 seconds
21:34:47  
21:34:47  Search...
21:34:47  Traceback (most recent call last):
21:34:47    File "scripts/verify_all_collections.py", line 124, in <module>
21:34:47      hello_milvus(collection_name)
21:34:47    File "scripts/verify_all_collections.py", line 86, in hello_milvus
21:34:47      "int64 > 100", output_fields=["int64", "float"], timeout=TIMEOUT
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 690, in search
21:34:47      partition_names, output_fields, round_decimal, timeout=timeout, **kwargs)
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 61, in handler
21:34:47      raise e
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 44, in handler
21:34:47      return func(self, *args, **kwargs)
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
21:34:47      raise e
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
21:34:47      return func(*args, **kwargs)
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 449, in search
21:34:47      return self._execute_search_requests(requests, timeout, **_kwargs)
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 79, in handler
21:34:47      raise e
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 75, in handler
21:34:47      return func(*args, **kwargs)
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 411, in _execute_search_requests
21:34:47      raise pre_err
21:34:47    File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 402, in _execute_search_requests
21:34:47      raise MilvusException(response.status.error_code, response.status.reason)
21:34:47  pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=All attempts results:
21:34:47  attempt #1:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #2:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #3:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #4:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #5:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #6:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #7:fail to get shard leaders from QueryCoord: no replica available
21:34:47  attempt #8:context deadline exceeded
21:34:47  )>
```

### Expected Behavior

all test cases passed

### Steps To Reproduce

```markdown
see http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6493/pipeline
```

### Milvus Log

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6493/pipeline
log: [artifacts-querynode-pod-kill-6493-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8905531/artifacts-querynode-pod-kill-6493-server-logs.tar.gz)

if all logs during the chaos are needed, leave a comment.
 

### Anything else?

some related issues:

https://github.com/milvus-io/milvus/issues/17203
https://github.com/milvus-io/milvus/issues/17367

**Comment by zhuwenxing** [comment]
/assign @jiaoew1991

please help to take a look

**Comment by yah01** [comment]
/assign @zhuwenxing 
Should be fixed with #17560

**Comment by zhuwenxing** [comment]
It still happened in version `master-20220616-53a49a92`.
Please help to take a look
/assign @yah01 
/unassign

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6563/pipeline
log: [artifacts-querynode-pod-kill-6563-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8919196/artifacts-querynode-pod-kill-6563-server-logs.tar.gz)

**Comment by yah01** [comment]
/assign @zhuwenxing 
#17608 fix merged

**Comment by zhuwenxing** [comment]
@yah01 
with version `master-20220617-0f877636` which includes https://github.com/milvus-io/milvus/pull/17608, this issue happened in all standalone pod kill chaos test.

failed job: https://github.com/zhuwenxing/milvus/runs/6929125633?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/6971858615/artifacts/272446587

**Comment by yah01** [comment]
/assign @zhuwenxing 
There's an another problem, which is fixed with #17616, plz help verify this one more time, thanks

**Comment by zhuwenxing** [comment]
This issue happened in another chaos test.

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/6690/pipeline/
log: [artifacts-etcd-io-latency-6690-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8928797/artifacts-etcd-io-latency-6690-server-logs.tar.gz)

Although the name of this chaos is etc networks latency, the real impact of the chaos is that it makes the etcd and milvus components restart.
So this issue may be related to querynode restarting

**Comment by zhuwenxing** [comment]
failed job:
all standalone: https://github.com/zhuwenxing/milvus/runs/6957017267?check_suite_focus=true
querynode: https://github.com/zhuwenxing/milvus/runs/6950019524?check_suite_focus=true

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check this with #17663

**Comment by zhuwenxing** [comment]
/assign @yah01 
version `master-20220621-1e87b545`
failed job: https://github.com/zhuwenxing/milvus/runs/6980707145?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7019499119/artifacts/275848666

**Comment by zhuwenxing** [comment]
failed job: https://github.com/zhuwenxing/milvus/runs/6981695319?check_suite_focus=true
log: https://github.com/zhuwenxing/milvus/suites/7020430917/artifacts/275889677

**Comment by yah01** [comment]
/assign @zhuwenxing 
plz check with #17686

**Comment by zhuwenxing** [comment]
failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7025/pipeline/224
log:[artifacts-querynode-pod-failure-7025-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8963075/artifacts-querynode-pod-failure-7025-server-logs.tar.gz)

failed job: http://10.100.32.144:8080/blue/organizations/jenkins/chaos-test/detail/chaos-test/7013/pipeline/
log: [artifacts-querynode-pod-kill-7013-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8963086/artifacts-querynode-pod-kill-7013-server-logs.tar.gz)

**Comment by zhuwenxing** [comment]
@yah01 
Please help to take a look

**Comment by zhuwenxing** [comment]
not reproduced in `master-20220623-e8f53af7`
remove critical label
