### ISSUE TITLE
Copy index data from cpu to gpu memory get slower with nq increase

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#1976]
**Describe the bug**
Copy index data from cpu to gpu memory get slower with nq increase

**Steps/Code to reproduce behavior**
1. set gpu_search_threshold to 1 in server_config.yaml
2. start milvus(gpu edition)
3. create a collection, index_file_size = 1024MB, dimension = 1024
4. insert 1,000,000 vectors
5. create index sq8, nlist=16384
6. restart milvus server, preload the table, search, nq=**2**, topk=10, nprobe=16
result: from the log each index file load from cpu to gpu cost about **50ms**
7. restart milvus server, preload the table, search, nq=**200**, topk=10, nprobe=16
result: from the log each index file load from cpu to gpu cost about **300ms**
8. restart milvus server, preload the table, search, nq=**1000**, topk=10, nprobe=16
result: from the log each index file load from cpu to gpu cost about **1000ms**

**Comment by yhmo** [comment]
May relate to #1859

**Comment by yhmo** [comment]
NQ=2:

[2020-04-18 17:36:51,896][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:67 CPU2GPU0 file type:3 size:177184983 bytes from location: /tmp/milvus/db/tables/AAA/1587199082812170000/1587199155058234000 totally cost (0.252284 second [252.283570 ms])
[2020-04-18 17:36:51,971][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:30 CPU2GPU0 file type:3 size:324206499 bytes from location: /tmp/milvus/db/tables/AAA/1587199034790802000/1587199040353427000 totally cost (0.074705 second [74.704769 ms])
[2020-04-18 17:36:52,023][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:66 CPU2GPU0 file type:3 size:295930395 bytes from location: /tmp/milvus/db/tables/AAA/1587199072877446000/1587199089055715000 totally cost (0.052438 second [52.437936 ms])
[2020-04-18 17:36:52,062][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:52 CPU2GPU0 file type:3 size:310068447 bytes from location: /tmp/milvus/db/tables/AAA/1587199050475981000/1587199069253263000 totally cost (0.038413 second [38.413214 ms])

**Comment by yhmo** [comment]
NQ=200

[2020-04-18 17:07:36,606][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:67 CPU2GPU0 file type:3 size:177184983 bytes from location: /tmp/milvus/db/tables/AAA/1587199082812170000/1587199155058234000 totally cost (0.247752 second [247.752119 ms])
[2020-04-18 17:07:37,048][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:30 CPU2GPU0 file type:3 size:324206499 bytes from location: /tmp/milvus/db/tables/AAA/1587199034790802000/1587199040353427000 totally cost (0.442296 second [442.295970 ms])
[2020-04-18 17:07:37,390][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:66 CPU2GPU0 file type:3 size:295930395 bytes from location: /tmp/milvus/db/tables/AAA/1587199072877446000/1587199089055715000 totally cost (0.341967 second [341.966772 ms])
[2020-04-18 17:07:37,719][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:52 CPU2GPU0 file type:3 size:310068447 bytes from location: /tmp/milvus/db/tables/AAA/1587199050475981000/1587199069253263000 totally cost (0.328601 second [328.600636 ms])

**Comment by yhmo** [comment]
NQ=1000

[2020-04-18 17:08:37,763][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:67 CPU2GPU0 file type:3 size:177184983 bytes from location: /tmp/milvus/db/tables/AAA/1587199082812170000/1587199155058234000 totally cost (0.247395 second [247.395318 ms])
[2020-04-18 17:08:38,883][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:30 CPU2GPU0 file type:3 size:324206499 bytes from location: /tmp/milvus/db/tables/AAA/1587199034790802000/1587199040353427000 totally cost (1.119867 seconds [1119.867293 ms])
[2020-04-18 17:08:39,584][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:66 CPU2GPU0 file type:3 size:295930395 bytes from location: /tmp/milvus/db/tables/AAA/1587199072877446000/1587199089055715000 totally cost (0.700763 second [700.762662 ms])
[2020-04-18 17:08:41,173][DEBUG][SERVER][PrintTimeRecord][taskloader_th] [search][0]: Search task load file id:52 CPU2GPU0 file type:3 size:310068447 bytes from location: /tmp/milvus/db/tables/AAA/1587199050475981000/1587199069253263000 totally cost (1.589605 seconds [1589.605105 ms])

**Comment by cydrain** [comment]
From the log, it seems because search process and load process are competing for GPU resources.
Need do nvprof to check.

**Comment by cydrain** [comment]
![nvprof_nq_2000](https://user-images.githubusercontent.com/3992404/79966561-2fdfba00-84c0-11ea-963f-c77e9f326eaa.jpg)

**Comment by cydrain** [comment]
We add more timing info in GPU device level.
From the log we can see, after "Load 3" thread start, GPU blocked 107ms to launch "copyFrom", waiting for previous search process finish.
This is why we see CPU2GPU0 timing become longer.
By nvprof, HtoD memory copy rate does not change.
```
XSearchTask::Load start 5058028
faiss::IndexIVFScalarQuantizer copyFrom start 5386026
faiss::IndexIVFScalarQuantizer copyFrom finish 5388475
XSearchTask::Load 1 finish 5388741

XSearchTask::Load 2 start 5388799
XSearchTask::Execute 1 start 5388885
faiss::IndexIVFScalarQuantizer search start 5440180
faiss::IndexIVFScalarQuantizer copyFrom start 5440920
faiss::IndexIVFScalarQuantizer copyFrom finish 5473732
XSearchTask::Load 2 finish 5474671

XSearchTask::Load 3 start 5474730
faiss::IndexIVFScalarQuantizer search finish 5575808
faiss::IndexIVFScalarQuantizer copyFrom start 5581375  ====> wait 107ms
XSearchTask::Execute 1 finish 5582334
XSearchTask::Execute 2 start 5587393
faiss::IndexIVFScalarQuantizer search start 5615412
faiss::IndexIVFScalarQuantizer copyFrom finish 5616074
XSearchTask::Load 3 finish 5616991

XSearchTask::Load 4 start 5617046
faiss::IndexIVFScalarQuantizer search finish 5746883
faiss::IndexIVFScalarQuantizer copyFrom start 5752603
XSearchTask::Execute 2 finish 5753345
XSearchTask::Execute 3 start 5783708
faiss::IndexIVFScalarQuantizer search start 5784951
faiss::IndexIVFScalarQuantizer copyFrom finish 5784958
XSearchTask::Load 4 finish 5785282

faiss::IndexIVFScalarQuantizer search finish 5906778
XSearchTask::Execute 3 finish 5912777
XSearchTask::Execute 4 start 5914618
faiss::IndexIVFScalarQuantizer search start 5919704
faiss::IndexIVFScalarQuantizer search finish 6061483
XSearchTask::Execute 4 finish 6068434
```

**Comment by del-zhenwu** [comment]
for 4096-d vector, here is the performance data: 
`gpu_search_threshold`: 100
```
20:37:40  │  Nq/Top-k   │      1      │     10      │     100     │    1000     │
20:37:40  ├─────────────┼─────────────┼─────────────┼─────────────┼─────────────┤
20:37:40  │           1 │        0.25 │        0.22 │        0.22 │        0.25 │
20:37:40  │         100 │        0.86 │        0.83 │        0.81 │        0.79 │
20:37:40  │         200 │        1.07 │        1.12 │         1.1 │         1.1 │
20:37:40  │        1000 │        4.09 │        4.06 │        4.11 │        4.49 │
```

**Comment by cydrain** [comment]
```
XSearchTask::Load start 4379861
IVFSQ::CopyCpuToGpu is called 4379888
GetRes res [0 1] -> [1]
IVFSQ::CopyCpuToGpu get res 04379909
ResScope1 res 0 locked 4379911
 0 locked 4379913
IVFSQ::CopyCpuToGpu create ResScope 4379914
ToGpuCloner::clone_index is called 4379917
faiss::IndexIVFScalarQuantizer copyFrom start 4652212
faiss::IndexIVFScalarQuantizer copyFrom finish 4656735
MoveToIdle res [1] -> [1 0]
ResScope res 0 unlocked 4656758
XSearchTask::Load finish 4657371

XSearchTask::Load start 4657427
IVFSQ::CopyCpuToGpu is called 4657454
GetRes res [1 0] -> [0]
IVFSQ::CopyCpuToGpu get res 14657463
ResScope1 res 1 locked 4657466                           =======> Load lock res 1
 1 locked 4657468
IVFSQ::CopyCpuToGpu create ResScope 4657470
ToGpuCloner::clone_index is called 4657472
XSearchTask::Execute start 4657519                       ===========> Search lock res 0
ResScope3 res 0 locked 4701352
 0 locked 4701362
faiss::IndexIVFScalarQuantizer search start 4707708
faiss::IndexIVFScalarQuantizer copyFrom start 4708320
faiss::IndexIVFScalarQuantizer copyFrom finish 4744443    ======> Load free res 1
MoveToIdle res [0] -> [0 1]
ResScope res 1 unlocked 4744465
XSearchTask::Load finish 4745280

XSearchTask::Load start 4745337
IVFSQ::CopyCpuToGpu is called 4745361
GetRes res [0 1] -> [1]
IVFSQ::CopyCpuToGpu get res 04745371
ResScope1 res 0 locked 4745372                               ==========> Load attemp to get res 0
faiss::IndexIVFScalarQuantizer search finish 4854718
ResScope res 0 unlocked 4860898                             ==========> Search unlock res 0
 0 locked 4860929                                                        ==========> Load blocked 115ms to get res 0
IVFSQ::CopyCpuToGpu create ResScope 4860934
ToGpuCloner::clone_index is called 4860936
faiss::IndexIVFScalarQuantizer copyFrom start 4860951
XSearchTask::Execute finish 4861769
XSearchTask::Execute start 4866083
ResScope3 res 1 locked 4866218
 1 locked 4866223
faiss::IndexIVFScalarQuantizer search start 4870532
faiss::IndexIVFScalarQuantizer copyFrom finish 4905794
MoveToIdle res [1] -> [1 0]
ResScope res 0 unlocked 4905824
XSearchTask::Load finish 4906732
```

**Comment by cydrain** [comment]
current FaissGpuResourceMgr scheduler has following constrains:
1. one RES cannot be used by two SEARCH tasks concurrently
2. when LOAD task (get RES 0) finished, it will create a SEARCH task and pass ownership of RES 0 to it
3. when RES 0 is hold by a SEARCH task, LOAD task will be blocked if attempt to get RES 0

**Comment by cydrain** [comment]
When NQ is large, most of execution time is used in API faiss::gpu::ivfFlatScan, traceback is like following:
```
#0  faiss::gpu::ivfFlatScan<faiss::gpu::Codec<0, 1>, faiss::gpu::L2Metric> (queries=..., useResidual=true, residualBase=..., listIds=..., allListData=0x7ff9783d9a00, listLengths=0x7ff9783ebe00, codec=..., metric=..., prefixSumOffsets=..., distance=...) at gpu/impl/IVFFlatScan.cu:158
#1  0x0000563b73586232 in faiss::gpu::runIVFFlatScanTile (queries=..., listIds=..., bitset=..., listData=..., listIndices=..., indicesOptions=faiss::gpu::INDICES_64_BIT, listLengths=..., thrustMem=..., prefixSumOffsets=..., allDistances=..., heapDistances=..., heapIndices=..., k=10, metricType=faiss::METRIC_L2, useResidual=true, residualBase=..., scalarQ=0x7ff917c723f0, outDistances=..., outIndices=..., stream=0x7ff9a80045f0) at gpu/impl/IVFFlatScan.cu:250
#2  0x0000563b735881f9 in faiss::gpu::runIVFFlatScan (queries=..., listIds=..., bitset=..., listData=..., listIndices=..., indicesOptions=faiss::gpu::INDICES_64_BIT, listLengths=..., maxListLength=180, k=10, metric=faiss::METRIC_L2, useResidual=true, residualBase=..., scalarQ=0x7ff917c723f0, outDistances=..., outIndices=..., res=0x7ff9a8001320) at gpu/impl/IVFFlatScan.cu:496
#3  0x0000563b734eb7d3 in faiss::gpu::IVFFlat::query (this=0x7ff917307a30, queries=..., bitset=..., nprobe=16, k=10, outDistances=..., outIndices=...) at gpu/impl/IVFFlat.cu:373
#4  0x0000563b734e1b67 in faiss::gpu::GpuIndexIVFScalarQuantizer::searchImpl_ (this=0x7ff91358ba50, n=2000, x=0x7ff8da03a980, k=10, distances=0x7ff8da000000, labels=0x7ff8da013880, bitset=std::shared_ptr<faiss::ConcurrentBitset> (use count 5, weak count 0) = {...}) at gpu/GpuIndexIVFScalarQuantizer.cu:288
#5  0x0000563b734d3cc3 in faiss::gpu::GpuIndex::searchNonPaged_ (this=0x7ff91358ba50, n=2000, x=0x7ff9c17a87c0, k=10, outDistancesData=0x7ff8da000000, outIndicesData=0x7ff8da013880, bitset=std::shared_ptr<faiss::ConcurrentBitset> (use count 5, weak count 0) = {...}) at gpu/GpuIndex.cu:273
#6  0x0000563b734d39d8 in faiss::gpu::GpuIndex::search (this=0x7ff91358ba50, n=2000, x=0x7ff9c17a87c0, k=10, distances=0x7ff9fc0633a0, labels=0x7ff9fc03c290, bitset=std::shared_ptr<faiss::ConcurrentBitset> (use count 5, weak count 0) = {...}) at gpu/GpuIndex.cu:245
#7  0x0000563b73281c84 in milvus::knowhere::GPUIVF::QueryImpl (this=0x7ff9173047a0, n=2000, data=0x7ff9c17a87c0, k=10, distances=0x7ff9fc0633a0, labels=0x7ff9fc03c290, config=...) at /home/caiyd/vec/milvus/core/src/index/knowhere/knowhere/index/vector_index/gpu/IndexGPUIVF.cpp:148
#8  0x0000563b732aefa5 in milvus::knowhere::IVF::Query (this=0x7ff9173047a0, dataset_ptr=std::shared_ptr<milvus::knowhere::Dataset> (use count 1, weak count 0) = {...}, config=...) at /home/caiyd/vec/milvus/core/src/index/knowhere/knowhere/index/vector_index/IndexIVF.cpp:119
#9  0x0000563b72fdf3e6 in milvus::engine::ExecutionEngineImpl::Search (this=0x7ff9ac0042c0, n=2000, data=0x7ff9c17a87c0, k=10, extra_params=..., distances=0x7ff9fc077f80, labels=0x7ff9fc001340, hybrid=false) at /home/caiyd/vec/milvus/core/src/db/engine/ExecutionEngineImpl.cpp:1106
#10 0x0000563b72d50cf9 in milvus::scheduler::XSearchTask::Execute (this=0x7ff9ac004150) at /home/caiyd/vec/milvus/core/src/scheduler/task/SearchTask.cpp:318
```

**Comment by cydrain** [comment]
queryTileSize is related with "sizeAvailable", "nprobe", "maxListLength", but not related with dim.
```
  size_t sizeAvailable = mem.getSizeAvailable();

  // We run two passes of heap selection
  // This is the size of the first-level heap passes
  constexpr int kNProbeSplit = 8;
  int pass2Chunks = std::min(nprobe, kNProbeSplit);

  size_t sizeForFirstSelectPass =
    pass2Chunks * k * (sizeof(float) + sizeof(int));

  // How much temporary storage we need per each query
  size_t sizePerQuery =
    2 * // # streams
    ((nprobe * sizeof(int) + sizeof(int)) + // prefixSumOffsets
     nprobe * maxListLength * sizeof(float) + // allDistances
     sizeForFirstSelectPass);

  int queryTileSize = (int) (sizeAvailable / sizePerQuery);

  if (queryTileSize < kMinQueryTileSize) {
    queryTileSize = kMinQueryTileSize;
  } else if (queryTileSize > kMaxQueryTileSize) {
    queryTileSize = kMaxQueryTileSize;
  }
```

**Comment by tinkerlin** [comment]
Looks like the problem can only be solved in the schedule phase. @scsven

**Comment by cydrain** [comment]
use following command to do nvprof
```
sudo /usr/local/cuda/bin/nvprof -o $HOME/nvvp_workspace/%p-postgres.nvvp ../bin/milvus_server -c ../conf/server_config.yaml
```

test with master branch 2020-05-15, this issue still exists.

**Comment by shengjun1985** [comment]
We have fixed a bug that copy data from CPU to GPU in #4310.
Done.
