### ISSUE TITLE
[Bug]: Search failed with error `Search 4 failed, reason [UnexpectedError] Assert "Segment 436810941530840279 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395` after datanode pod kill chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20221020-e8ca754d
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev57
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2022-10-20T21:51:47.166Z] [2022-10-20 21:50:05 - INFO - ci_test]: assert index: 3.1685309410095215 (test_all_collections_after_chaos.py:61)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 20], kwargs: {} (api_request.py:56)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - INFO - ci_test]: [test][2022-10-20T21:50:05Z] [0.00736847s] Checker__NNy2pGfe load -> None (wrapper.py:30)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[0.12311772762946267, 0.14391062863434478, 0.002724963707897904, 0.10623696977447378, 0.10931200435311819, 0.11280386676015144, 0.10907040961945451, 0.03353639352682021, 0.04682647101292017, 0.10176897046538796, 0.05937553961729929, 0.041877334812036704, 0.061596429491749094, 0.1401389053807598, 0......, kwargs: {} (api_request.py:56)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 4 failed, reason [UnexpectedError] Assert "Segment 436810941530840279 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395

[2022-10-20T21:51:47.167Z]  err %!w(<nil>))>, <Time:{'RPC start': '2022-10-20 21:50:05.179440', 'RPC error': '2022-10-20 21:50:05.557977'}> (decorators.py:108)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - ERROR - ci_test]: Traceback (most recent call last):

[2022-10-20T21:51:47.167Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper

[2022-10-20T21:51:47.167Z]     res = func(*args, **_kwargs)

[2022-10-20T21:51:47.167Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request

[2022-10-20T21:51:47.167Z]     return func(*arg, **kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 720, in search

[2022-10-20T21:51:47.167Z]     partition_names, output_fields, round_decimal, timeout=timeout, schema=schema_dict, **kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 109, in handler

[2022-10-20T21:51:47.167Z]     raise e

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 105, in handler

[2022-10-20T21:51:47.167Z]     return func(*args, **kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 136, in handler

[2022-10-20T21:51:47.167Z]     ret = func(self, *args, **kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 85, in handler

[2022-10-20T21:51:47.167Z]     raise e

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 50, in handler

[2022-10-20T21:51:47.167Z]     return func(self, *args, **kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 476, in search

[2022-10-20T21:51:47.167Z]     return self._execute_search_requests(requests, timeout, **_kwargs)

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 440, in _execute_search_requests

[2022-10-20T21:51:47.167Z]     raise pre_err

[2022-10-20T21:51:47.167Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/client/grpc_handler.py", line 431, in _execute_search_requests

[2022-10-20T21:51:47.167Z]     raise MilvusException(response.status.error_code, response.status.reason)

[2022-10-20T21:51:47.167Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 4 failed, reason [UnexpectedError] Assert "Segment 436810941530840279 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segcore/SegmentSealedImpl.cpp:395

[2022-10-20T21:51:47.167Z]  err %!w(<nil>))>

[2022-10-20T21:51:47.167Z]  (api_request.py:39)

[2022-10-20T21:51:47.167Z] [2022-10-20 21:50:05 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=1, reason=Search 4 failed, reason [UnexpectedError] Assert "Segment 436810941530840279 System Field RowID or Timestamp is not loaded" at /go/src/github.com/milvus-io/milvus/internal/core/src/segc...... (api_request.py:40)
```

### Expected Behavior

all test cases passed

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test/detail/chaos-test/2327/pipeline

log:
[artifacts-datanode-pod-kill-2327-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835388/artifacts-datanode-pod-kill-2327-server-logs.tar.gz)

[artifacts-datanode-pod-kill-2327-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9835389/artifacts-datanode-pod-kill-2327-pytest-logs.tar.gz)

**Comment by soothing-rain** [comment]
Should be fixed by https://github.com/milvus-io/milvus/pull/19936

**Comment by zhuwenxing** [comment]
It is still reproduced in the Kafka version
see https://github.com/milvus-io/milvus/issues/19954

**Comment by zhuwenxing** [comment]
duplicated with https://github.com/milvus-io/milvus/issues/19954, so close this one
