### ISSUE TITLE
[Bug]: Search failed on disk index when search_list equal to limit

### ISSUE THREAD

**Issue by xige-16** [milvus-io/milvus#21092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. create collection
2. insert data
3. create diskAnn index
4. load collection
5. search with params  search_list ==  limit 

return error  
```
message=fail to search on all shard leaders, err=fail to Search, QueryNode ID=3, reason=Search 3 failed, reason [UnexpectedError] Assert "query_config.search_list_size > topk" at /home/xge/mac/milvus/internal/core/src/index/VectorDiskIndex.cpp:115
 => search_list should be greater than topk err %!w(<nil>))
```

### Expected Behavior

https://milvus.io/docs/disk_index.md#Index-and-search-settings
search  should succeed

**Comment by yanliang567** [comment]
seems that it was fixed.
@NicoYuan1986 could you please help to verify the issue, and check whether we need a new case for this scenarios in ci.

/assign @NicoYuan1986

**Comment by NicoYuan1986** [comment]
> seems that it was fixed. @NicoYuan1986 could you please help to verify the issue, and check whether we need a new case for this scenarios in ci.
> 
> /assign @NicoYuan1986

Not fixed yet. I'll add the case when it's fixed.

**Comment by xiaofan-luan** [comment]
> > seems that it was fixed. @NicoYuan1986 could you please help to verify the issue, and check whether we need a new case for this scenarios in ci.
> > /assign @NicoYuan1986
> 
> Not fixed yet. I'll add the case when it's fixed.

@xige-16 
any updates?

**Comment by yanliang567** [comment]
@NicoYuan1986 was it fixed?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 was it fixed?

Not fixed.
milvus: master-20230213-a2435cfc
pymilvus: 2.3.0.dev34

![image](https://user-images.githubusercontent.com/109071306/218400952-d464b38a-09d6-408d-9ea4-68f7f7214515.png)

**Comment by xige-16** [comment]
My pr to master branch was closed by mistake, sorry

**Comment by xige-16** [comment]
should has been fixed on master @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Not fixed.
milvus: master-20230216-b25b3ef4
pymilvus: 2.3.0.dev38
![image](https://user-images.githubusercontent.com/109071306/219343626-b3fef55e-6b82-4cf9-a576-eb0724d4f284.png)

**Comment by NicoYuan1986** [comment]
2.2:
milvus: 2.2.0-20230216-fa8a9224
pymilvus: 2.2.3.dev1
![image](https://user-images.githubusercontent.com/109071306/219346566-84b473e9-54ca-4a0e-b040-11d954353073.png)

**Comment by NicoYuan1986** [comment]
Verified fixed.
milvus: 2.2.0-20230308-69f4afe4
pymilvus: 2.2.3.dev5
![image](https://user-images.githubusercontent.com/109071306/223962147-27cdba82-76cb-4bca-aa9a-c4fd6cd31060.png)

**Comment by NicoYuan1986** [comment]
Also verified in master
milvus: master-20230309-90a5aa62
pymilvus: 2.3.0.dev47
