### ISSUE TITLE
[Bug]: Expected to raise exception when count(*) with pagination params

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#23368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230411-ad7f3d4c
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):  pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.4.0.dev4
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Currently, milvus ignore pagination params
Case:
```
    def test_count_with_pagination_param(self):
        """
        target: test count with pagination params
        method: count with pagination params: offset, limit
        expected: exception
        """
        # create -> insert -> index -> load
        collection_w = self.init_collection_general(insert_data=True)[0]

        # count with offset
        collection_w.query(expr=default_expr, output_fields=[ct.default_count_output], offset=10,
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "xxx"}
                           )
        # count with limit
        collection_w.query(expr=default_expr, output_fields=[ct.default_count_output], limit=10,
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "xxx"}
                           )
        # count with pagination params
        collection_w.query(default_expr, output_fields=[ct.default_count_output], params={"offset": 10, "limit": 10},
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "xxx"})
```

**Comment by binbinlv** [comment]
@ThreadDao 
Is it fixed now?

**Comment by ThreadDao** [comment]
/unassign
/assign @longjiquan 
not fully fixed
1. query with limit `collection.query(output_fields="count(*)"), limit=10` return exception
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=count entities with pagination is not allowed)>
```
2. query with limit `collection.query(output_fields="count(*)"), offset=10` succ
```
[{'count(*)': 3000}]
```
3. query with limit `collection.query(output_fields="count(*)"), offset=10, 'limit'=10` succ
```
[{'count(*)': 3000}]
```

Case:
```
    @pytest.mark.tags(CaseLabel.L2)
    def test_count_with_pagination_param(self):
        """
        target: test count with pagination params
        method: count with pagination params: offset, limit
        expected: exception
        """
        # create -> insert -> index -> load
        collection_w = self.init_collection_general(insert_data=True)[0]

        # count with offset
        collection_w.query(expr=default_expr, output_fields=[ct.default_count_output], offset=10,
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "xxx"}
                           )
        # count with limit
        collection_w.query(expr=default_expr, output_fields=[ct.default_count_output], limit=10,
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "count entities with pagination is not allowed"}
                           )
        # count with pagination params
        collection_w.query(default_expr, output_fields=[ct.default_count_output], params={"offset": 10, "limit": 10},
                           check_task=CheckTasks.err_res,
                           check_items={ct.err_code: 1, ct.err_msg: "xxx"})
```

**Comment by longjiquan** [comment]
```python
import time

import numpy as np
from pymilvus import (
    connections,
    utility,
    FieldSchema, CollectionSchema, DataType,
    Collection,
)

fmt = "\n=== {:30} ===\n"
num_entities, dim = 3000, 8

print(fmt.format("start connecting to Milvus"))
connections.connect("default", host="localhost", port="19530")

has = utility.has_collection("hello_milvus")
print(f"Does collection hello_milvus exist in Milvus: {has}")

fields = [
    FieldSchema(name="pk", dtype=DataType.VARCHAR, is_primary=True, auto_id=False, max_length=100),
    FieldSchema(name="random", dtype=DataType.DOUBLE),
    FieldSchema(name="embeddings", dtype=DataType.FLOAT_VECTOR, dim=dim)
]

schema = CollectionSchema(fields, "hello_milvus is the simplest demo to introduce the APIs")

print(fmt.format("Create collection `hello_milvus`"))
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")

print(fmt.format("Start inserting entities"))
rng = np.random.default_rng(seed=19530)
entities = [
    # provide the pk field because `auto_id` is set to False
    [str(i) for i in range(num_entities)],
    rng.random(num_entities).tolist(),  # field random, only supports list
    rng.random((num_entities, dim)),    # field embeddings, supports numpy.ndarray and list
]

insert_result = hello_milvus.insert(entities)

hello_milvus.flush()
print(f"Number of entities in Milvus: {hello_milvus.num_entities}")  # check the num_entites

print(fmt.format("Start Creating index IVF_FLAT"))
index = {
    "index_type": "IVF_FLAT",
    "metric_type": "L2",
    "params": {"nlist": 128},
}

hello_milvus.create_index("embeddings", index)

print(fmt.format("Start loading"))
hello_milvus.load()

# count with pagination.

def test(f):
    try:
        f()
        print(f"{f.__name__} end with no exception")
    except Exception as e:
        print(e)
        print(f"{f.__name__} end with exception")

def c1():
    print("case1")
    hello_milvus.query(expr="", output_fields=["count(*)"])

def c2():
    print("case2")
    hello_milvus.query(expr="random > 0.5", output_fields=["count(*)"])

def c3():
    print("case3")
    hello_milvus.query(expr="", offset=1, output_fields=["count(*)"])

def c4():
    print("case4")
    hello_milvus.query(expr="random > 0.5", offset=1, output_fields=["count(*)"])

def c5():
    print("case5")
    hello_milvus.query(expr="", limit=4, output_fields=["count(*)"])

def c6():
    print("case6")
    hello_milvus.query(expr="random > 0.5", limit=4, output_fields=["count(*)"])

def c7():
    print("case7")
    hello_milvus.query(expr="", limit=4, offset=1, output_fields=["count(*)"])

def c8():
    print("case8")
    hello_milvus.query(expr="random > 0.5", limit=4, offset=1, output_fields=["count(*)"])

test(c1)
test(c2)
test(c3)
test(c4)
test(c5)
test(c6)
test(c7)
test(c8)


###############################################################################
# 7. drop collection
# Finally, drop the hello_milvus collection
print(fmt.format("Drop collection `hello_milvus`"))
utility.drop_collection("hello_milvus")

```

**Comment by longjiquan** [comment]
I have tried the 8 cases, and all of them are as expected.

![image](https://github.com/milvus-io/milvus/assets/31589260/8003ced7-dd33-43b2-b758-eda9a90e6f63)

**Comment by longjiquan** [comment]
please recheck this, thx.
/assign @ThreadDao
