### ISSUE TITLE
[Bug]: Upsert should be allowed for autoid collection

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#25397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.3.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Create a collection with auto-id primary key.
insert some data
try call upsert() to update some rows by pk

error thrown:
pymilvus.exceptions.UpsertAutoIDTrueException: <UpsertAutoIDTrueException: (code=1, message=Upsert don't support autoid == true)>

### Expected Behavior

Upsert should be allowed for autoid collection

**Comment by xiaofan-luan** [comment]
@smellthemoon 
how is this pr works?

**Comment by xiaofan-luan** [comment]
this is fixed

**Comment by raodj** [comment]
I am still experiencing this issue with the Java SDK. I am using Milvus 2.5.15 with Milvus 2.5.11 Java SDK and I get the following error:

`
io.milvus.exception.ParamException: Upsert don't support autoID==True, collection: test_collection
	at io.milvus.param.ParamUtils$InsertBuilderWrapper.<init>(ParamUtils.java:532) ~[milvus-sdk-java-2.6.1.jar:na]
	at io.milvus.client.AbstractMilvusGrpcClient.buildUpsertRequest(AbstractMilvusGrpcClient.java:1735) ~[milvus-sdk-java-2.6.1.jar:na]
	at io.milvus.client.AbstractMilvusGrpcClient.upsert(AbstractMilvusGrpcClient.java:1763) ~[milvus-sdk-java-2.6.1.jar:na]
	at io.milvus.client.MilvusServiceClient.lambda$upsert$36(MilvusServiceClient.java:639) ~[milvus-sdk-java-2.6.1.jar:na]
	at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:334) ~[milvus-sdk-java-2.6.1.jar:na]
	at io.milvus.client.MilvusServiceClient.upsert(MilvusServiceClient.java:639) ~[milvus-sdk-java-2.6.1.jar:na]`

When I look at the source code for ParamUtils.java (from [https://github.com/milvus-io/milvus-sdk-java/blob/master/sdk-core/src/main/java/io/milvus/param/ParamUtils.java](https://github.com/milvus-io/milvus-sdk-java/blob/master/sdk-core/src/main/java/io/milvus/param/ParamUtils.java)), **I see the check is still there**:

`        public InsertBuilderWrapper(@NonNull UpsertParam requestParam,
                                    DescCollResponseWrapper wrapper) {
            String collectionName = requestParam.getCollectionName();

            // currently, not allow to upsert for collection whose primary key is auto-generated
            FieldType pk = wrapper.getPrimaryField();
            if (pk.isAutoID()) {
                throw new ParamException(String.format("Upsert don't support autoID==True, collection: %s",
                        requestParam.getCollectionName()));
            }

            // generate upsert request builder
            MsgBase msgBase = MsgBase.newBuilder().setMsgType(MsgType.Insert).build();
            upsertBuilder = UpsertRequest.newBuilder()
                    .setCollectionName(collectionName)
                    .setBase(msgBase)
                    .setNumRows(requestParam.getRowCount());
            if (StringUtils.isNotEmpty(requestParam.getDatabaseName())) {
                upsertBuilder.setDbName(requestParam.getDatabaseName());
            }
            fillFieldsData(requestParam, wrapper);
        }
`

**So, is this issue really fixed?**

**Comment by yhmo** [comment]
> I am still experiencing this issue with the Java SDK. I am using Milvus 2.5.15 with Milvus 2.5.11 Java SDK and I get the following error:
> 
> ` io.milvus.exception.ParamException: Upsert don't support autoID==True, collection: test_collection at io.milvus.param.ParamUtils$InsertBuilderWrapper.<init>(ParamUtils.java:532) ~[milvus-sdk-java-2.6.1.jar:na] at io.milvus.client.AbstractMilvusGrpcClient.buildUpsertRequest(AbstractMilvusGrpcClient.java:1735) ~[milvus-sdk-java-2.6.1.jar:na] at io.milvus.client.AbstractMilvusGrpcClient.upsert(AbstractMilvusGrpcClient.java:1763) ~[milvus-sdk-java-2.6.1.jar:na] at io.milvus.client.MilvusServiceClient.lambda$upsert$36(MilvusServiceClient.java:639) ~[milvus-sdk-java-2.6.1.jar:na] at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:334) ~[milvus-sdk-java-2.6.1.jar:na] at io.milvus.client.MilvusServiceClient.upsert(MilvusServiceClient.java:639) ~[milvus-sdk-java-2.6.1.jar:na]`
> 
> When I look at the source code for ParamUtils.java (from https://github.com/milvus-io/milvus-sdk-java/blob/master/sdk-core/src/main/java/io/milvus/param/ParamUtils.java), **I see the check is still there**:
> 
> ` public InsertBuilderWrapper([@nonnull](https://github.com/nonnull) UpsertParam requestParam, DescCollResponseWrapper wrapper) { String collectionName = requestParam.getCollectionName();
> 
> ```
>         // currently, not allow to upsert for collection whose primary key is auto-generated
>         FieldType pk = wrapper.getPrimaryField();
>         if (pk.isAutoID()) {
>             throw new ParamException(String.format("Upsert don't support autoID==True, collection: %s",
>                     requestParam.getCollectionName()));
>         }
> 
>         // generate upsert request builder
>         MsgBase msgBase = MsgBase.newBuilder().setMsgType(MsgType.Insert).build();
>         upsertBuilder = UpsertRequest.newBuilder()
>                 .setCollectionName(collectionName)
>                 .setBase(msgBase)
>                 .setNumRows(requestParam.getRowCount());
>         if (StringUtils.isNotEmpty(requestParam.getDatabaseName())) {
>             upsertBuilder.setDbName(requestParam.getDatabaseName());
>         }
>         fillFieldsData(requestParam, wrapper);
>     }
> ```
> 
> `
> 
> **So, is this issue really fixed?**

The Java SDK has two editions: MilvusClientV1 and MilvusClientV2
MilvusClientV2 is recommended.
This error is from MilvusClientV1, I will remove this checker later.

The MilvusClientV2 has no this error:
```
ConnectConfig config = ConnectConfig.builder()
                .uri("http://localhost:19530")
                .build();
MilvusClientV2 client = new MilvusClientV2(config);

JsonObject row = new JsonObject();
row.addProperty(ID_FIELD, ids.get(0));
List<Float> vector = CommonUtils.generateFloatVector(VECTOR_DIM);
row.add(VECTOR_FIELD, gson.toJsonTree(vector));
UpsertResp rr = client.upsert(UpsertReq.builder()
        .collectionName(COLLECTION_NAME)
        .data(Collections.singletonList(row))
        .build());
```

**Comment by raodj** [comment]
@yhmo Thank you for your quick response. I have one more follow up question -- Should I be using MilvusClientV2 in Java for all of my production work? Thanks.

**Comment by raodj** [comment]
Upsert is still not working even with MilvusClientV2 version -- I get the following exception:

`Caused by: io.milvus.v2.exception.MilvusClientException: the number of fields is less than needed: invalid parameter[expected=14][actual=15]
`
I have double-checked that the field values are correct and consistent with the schema. 

**Is this feature actually tested?**

**Comment by xiaofan-luan** [comment]
> io.milvus.v2.exception.MilvusClientException: the number of fields is less than needed: invalid parameter[expected=14][actual=15]


This means the data you give have 15 fields but your  schema only has 14 fields.

Can you share your schema and your api request?

**Comment by raodj** [comment]
Hello,

Sorry, I was traveling and could not respond earlier. I created a simple example to clearly illustrate and reproduce the problem. I am attaching the Java source code for this example. Here is the key information:

**Error message generated:**
```
Exception in thread "main" io.milvus.v2.exception.MilvusClientException: the number of fields is less than needed: invalid parameter[expected=2][actual=3]
	at io.milvus.v2.utils.RpcUtils.handleResponse(RpcUtils.java:63)
	at io.milvus.v2.service.vector.VectorService.upsert(VectorService.java:205)
	at io.milvus.v2.client.MilvusClientV2.lambda$upsert$30(MilvusClientV2.java:535)
	at io.milvus.v2.utils.RpcUtils.retry(RpcUtils.java:100)
	at io.milvus.v2.client.MilvusClientV2.upsert(MilvusClientV2.java:535)
	at milvus_test.milvus_upsert_test.upsertData(milvus_upsert_test.java:159)
	at milvus_test.milvus_upsert_test.main(milvus_upsert_test.java:167)
```

**Schema for the collection being used for testing:**
```
milvus_cli > list collections
['test_collection']
milvus_cli > show collection -c test_collection
+---------------+-----------------------------------------------------------------------+
| Name          | test_collection                                                       |
+---------------+-----------------------------------------------------------------------+
| Description   | A collection for testing upsert                                       |
+---------------+-----------------------------------------------------------------------+
| Is Empty      | True                                                                  |
+---------------+-----------------------------------------------------------------------+
| Entities      | 0                                                                     |
+---------------+-----------------------------------------------------------------------+
| Primary Field | data_id                                                               |
+---------------+-----------------------------------------------------------------------+
| Schema        | Description: A collection for testing upsert                          |
|               |                                                                       |
|               | Auto ID: True                                                         |
|               |                                                                       |
|               | Fields(* is the primary field):                                       |
|               |  - *data_id INT64  A auto generated numeric unique id for each record |
|               |  - info VARCHAR  Some information associated with each row            |
|               |  - embeddings FLOAT_VECTOR dim: 1500 The vector embeddings            |
+---------------+-----------------------------------------------------------------------+
| Partitions    | - _default                                                            |
+---------------+-----------------------------------------------------------------------+
| Indexes       | -                                                                     |
+---------------+-----------------------------------------------------------------------+
milvus_cli >
```

**The relevant fragment of the source code (using client version 2.6.1):**
```
	/**
	 * The tester method that tries to upsert data into the row.
	 */
	private static void upsertData() {
		// Create the record to be updated/inserted
		final JsonObject testRecord = new JsonObject();
		testRecord.addProperty("data_id", (Long) 123L);
		testRecord.addProperty("info", "Some test information");
		final List<Float> embeddings = new ArrayList<Float>(1500);
		for (int i = 0; i < 1500; i++) {
			embeddings.add(0.1f);
		}
		testRecord.add("embeddings", new Gson().toJsonTree(embeddings));
		// Create the list of object as required by Milvus API
		final ArrayList<JsonObject> upsertData = new ArrayList<>();
		upsertData.add(testRecord);
		// Create upsert request to add entry to Milvus
		UpsertReq upsertParam = UpsertReq.builder()
				.databaseName(MILVUS_DB_NAME)
				.collectionName(TEST_COLLECTION_NAME)
				.data(upsertData)
				.build();
		UpsertResp resp = getClient().upsert(upsertParam);
		System.out.println("Number of records upsert'ed = " + resp.getUpsertCnt());
	}

```


[milvus_upsert_test.java.txt](https://github.com/user-attachments/files/21740955/milvus_upsert_test.java.txt)

**Comment by raodj** [comment]
Any updates on this issue?

**Comment by yanliang567** [comment]
@raodj could you please file a new issue with you reproduce scripts, as we might miss the updates in a closed issue. 

@yhmo  could youplease  help to take a look first

**Comment by raodj** [comment]
@yanliang567 and @yhmo I have created a new bug ticket #44004 as per your instructions.
