### ISSUE TITLE
[Bug]: [benchmark][rolling update] milvus rolling upgrade from v2.2.14 to v2.3.0 was interrupted for about 1 minute

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#26683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: v2.2.14 -> v2.3.0
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka): kafka   
- deploy mode(helm or operator):  operator
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

upgrade argo : fouramf-jbm67
client test argo: fouramf-4fl9v

befoure upgrade:
```
fouramf-26ftm-op-8-1345-milvus-datacoord-9cdf88d64-nxplj       Running     0            2h25m     10.104.12.205     4am-node17     
fouramf-26ftm-op-8-1345-milvus-datanode-787bfcf84-d24dg        Running     0            2h25m     10.104.18.18      4am-node25     
fouramf-26ftm-op-8-1345-milvus-indexcoord-6c496c9756-lvldv     Running     0            2h25m     10.104.18.17      4am-node25     
fouramf-26ftm-op-8-1345-milvus-indexnode-6cb678d9-hcmwm        Running     0            2h25m     10.104.24.145     4am-node29     
fouramf-26ftm-op-8-1345-milvus-proxy-5594488bc9-tkjqh          Running     0            2h25m     10.104.18.16      4am-node25     
fouramf-26ftm-op-8-1345-milvus-querycoord-77c98755bd-m4djq     Running     0            2h25m     10.104.12.206     4am-node17     
fouramf-26ftm-op-8-1345-milvus-querynode-7766d979f9-gtgcf      Running     0            2h25m     10.104.18.20      4am-node25     
fouramf-26ftm-op-8-1345-milvus-querynode-7766d979f9-xvzrh      Running     0            2h25m     10.104.12.207     4am-node17     
fouramf-26ftm-op-8-1345-milvus-rootcoord-5f6b5599b4-f4l5q      Running     0            2h25m     10.104.18.19      4am-node25     
fouramf-26ftm-op-8-1345-etcd-0                                 Running     0            2h28m     10.104.18.10      4am-node25     
fouramf-26ftm-op-8-1345-etcd-1                                 Running     0            2h28m     10.104.14.138     4am-node18     
fouramf-26ftm-op-8-1345-etcd-2                                 Running     0            2h28m     10.104.4.212      4am-node11     
fouramf-26ftm-op-8-1345-kafka-0                                Running     3            2h28m     10.104.18.14      4am-node25     
fouramf-26ftm-op-8-1345-kafka-1                                Running     2            2h28m     10.104.6.172      4am-node13     
fouramf-26ftm-op-8-1345-kafka-2                                Running     0            2h28m     10.104.12.202     4am-node17     
fouramf-26ftm-op-8-1345-kafka-zookeeper-0                      Running     0            2h28m     10.104.18.15      4am-node25     
fouramf-26ftm-op-8-1345-kafka-zookeeper-1                      Running     0            2h28m     10.104.14.140     4am-node18     
fouramf-26ftm-op-8-1345-kafka-zookeeper-2                      Running     0            2h28m     10.104.4.216      4am-node11     
fouramf-26ftm-op-8-1345-minio-0                                Running     0            2h28m     10.104.18.11      4am-node25     
fouramf-26ftm-op-8-1345-minio-1                                Running     0            2h28m     10.104.21.91      4am-node24     
fouramf-26ftm-op-8-1345-minio-2                                Running     0            2h28m     10.104.4.214      4am-node11     
fouramf-26ftm-op-8-1345-minio-3                                Running     0            2h28m     10.104.6.171      4am-node13 
```

after upgrade:
```
fouramf-26ftm-op-8-1345-milvus-datacoord-569b54c898-64b42      Running     0            5m        10.104.23.189     4am-node27     
fouramf-26ftm-op-8-1345-milvus-datanode-74d45695cd-t6tgw       Running     0            3m        10.104.23.192     4am-node27     
fouramf-26ftm-op-8-1345-milvus-indexcoord-79dd8868f4-6mrbm     Running     0            6m        10.104.23.188     4am-node27     
fouramf-26ftm-op-8-1345-milvus-indexnode-74c9587df9-n9t6b      Running     0            3m        10.104.23.191     4am-node27     
fouramf-26ftm-op-8-1345-milvus-proxy-5594488bc9-tkjqh          Running     0            2h32m     10.104.18.16      4am-node25     
fouramf-26ftm-op-8-1345-milvus-proxy-7895878f49-zsqtd          Running     0            1m        10.104.18.111     4am-node25     
fouramf-26ftm-op-8-1345-milvus-querycoord-6cd4d7c998-4sz5d     Running     0            4m        10.104.23.190     4am-node27     
fouramf-26ftm-op-8-1345-milvus-querynode-6b5bf78877-82pc4      Running     0            2m        10.104.6.77       4am-node13     
fouramf-26ftm-op-8-1345-milvus-querynode-6b5bf78877-r9vxb      Running     0            3m        10.104.1.29       4am-node10     
fouramf-26ftm-op-8-1345-milvus-querynode-7766d979f9-gtgcf      Running     0            2h32m     10.104.18.20      4am-node25     
fouramf-26ftm-op-8-1345-milvus-querynode-7766d979f9-xvzrh      Running     0            2h32m     10.104.12.207     4am-node17     
fouramf-26ftm-op-8-1345-milvus-rootcoord-c4fc7bcfd-l4qpk       Running     0            7m        10.104.23.187     4am-node27     
fouramf-26ftm-op-8-1345-etcd-0                                 Running     0            2h35m     10.104.18.10      4am-node25     
fouramf-26ftm-op-8-1345-etcd-1                                 Running     0            2h35m     10.104.14.138     4am-node18     
fouramf-26ftm-op-8-1345-etcd-2                                 Running     0            2h35m     10.104.4.212      4am-node11     
fouramf-26ftm-op-8-1345-kafka-0                                Running     3            2h35m     10.104.18.14      4am-node25     
fouramf-26ftm-op-8-1345-kafka-1                                Running     2            2h35m     10.104.6.172      4am-node13     
fouramf-26ftm-op-8-1345-kafka-2                                Running     0            2h35m     10.104.12.202     4am-node17     
fouramf-26ftm-op-8-1345-kafka-zookeeper-0                      Running     0            2h35m     10.104.18.15      4am-node25     
fouramf-26ftm-op-8-1345-kafka-zookeeper-1                      Running     0            2h35m     10.104.14.140     4am-node18     
fouramf-26ftm-op-8-1345-kafka-zookeeper-2                      Running     0            2h35m     10.104.4.216      4am-node11     
fouramf-26ftm-op-8-1345-minio-0                                Running     0            2h35m     10.104.18.11      4am-node25     
fouramf-26ftm-op-8-1345-minio-1                                Running     0            2h35m     10.104.21.91      4am-node24     
fouramf-26ftm-op-8-1345-minio-2                                Running     0            2h35m     10.104.4.214      4am-node11     
fouramf-26ftm-op-8-1345-minio-3                                Running     0            2h35m     10.104.6.171      4am-node13   
```

client pod: fouramf-4fl9v-1340809859

There was a search failure on the client side for about 1 minute before it resumed. Time of interruption: 05:05:45  to 5:07:06

</b></b></b>
![image](https://github.com/milvus-io/milvus/assets/48523564/f8312d77-a72e-40bc-bd4a-c463d892162d)

### Steps To Reproduce

```markdown
1. deploy milvus and set enableActiveStandby to true
  2. create a collection  
  3. build an HNSW index on the vector column
  4. insert 50 million vectors
  5. flush collection
  6. build index on vector column with the same parameters  
  7. count the total number of rows
  8. load collection
  9. execute concurrent search, query,load,scene_test 
    (scene_test steps: 
       1） Create a collection 2） Insert 3000 pieces of data  3） flush collection 
       4） Create an index  5） drop collection)
  10. upgrading milvus while doing step 9
```

**Comment by weiliu1031** [comment]
please check the operator version @elstic

**Comment by weiliu1031** [comment]
> > please check the operator version @elstic
> 
> 0.8.0beta

for now,  during rolling upgrade progress, there will be about 1minute between stop dc and stop ic, so new dc will be unavailable during this period. we need to refine this.

**Comment by weiliu1031** [comment]
please verify this @elstic

**Comment by elstic** [comment]
> please verify this @elstic

upgrade argo task : fouramf-pnv2l
client argo task : fouramf-jnsbb

After upgrading from v2.2.14 to the latest master branch, most searches fail.
server before upgrade:
```
fouramf-jnsbb-op-89-1760-milvus-datacoord-b6447cfcc-l8rq6       Running     0            3h29m     10.104.17.40      4am-node23     
fouramf-jnsbb-op-89-1760-milvus-datanode-5cd484bb4f-g879v       Running     0            3h29m     10.104.13.233     4am-node16     
fouramf-jnsbb-op-89-1760-milvus-indexcoord-f8747c99c-szhq5      Running     0            3h29m     10.104.14.242     4am-node18     
fouramf-jnsbb-op-89-1760-milvus-indexnode-7b8cb6b8fb-qzfhj      Running     0            3h29m     10.104.19.69      4am-node28     
fouramf-jnsbb-op-89-1760-milvus-proxy-5c7744ffb4-cdzg5          Running     0            3h29m     10.104.17.39      4am-node23     
fouramf-jnsbb-op-89-1760-milvus-querycoord-8668484449-jpxds     Running     0            3h29m     10.104.19.68      4am-node28     
fouramf-jnsbb-op-89-1760-milvus-querynode-6fd9f447cd-ndm5k      Running     0            3h29m     10.104.24.9       4am-node29     
fouramf-jnsbb-op-89-1760-milvus-querynode-6fd9f447cd-vx646      Running     0            3h29m     10.104.18.65      4am-node25     
fouramf-jnsbb-op-89-1760-milvus-rootcoord-54b6dcfc7c-k72p8      Running     0            3h29m     10.104.18.64      4am-node25     
fouramf-jnsbb-op-89-1760-etcd-0                                 Running     0            3h30m     10.104.18.58      4am-node25     
fouramf-jnsbb-op-89-1760-etcd-1                                 Running     0            3h30m     10.104.24.5       4am-node29     
fouramf-jnsbb-op-89-1760-etcd-2                                 Running     0            3h30m     10.104.19.67      4am-node28     
fouramf-jnsbb-op-89-1760-kafka-0                                Running     2            3h30m     10.104.18.59      4am-node25     
fouramf-jnsbb-op-89-1760-kafka-1                                Running     0            3h30m     10.104.13.232     4am-node16     
fouramf-jnsbb-op-89-1760-kafka-2                                Running     1            3h30m     10.104.14.240     4am-node18     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-0                      Running     0            3h30m     10.104.24.6       4am-node29     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-1                      Running     0            3h30m     10.104.14.241     4am-node18     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-2                      Running     0            3h30m     10.104.18.63      4am-node25     
fouramf-jnsbb-op-89-1760-minio-0                                Running     0            3h30m     10.104.18.62      4am-node25     
fouramf-jnsbb-op-89-1760-minio-1                                Running     0            3h30m     10.104.13.231     4am-node16     
fouramf-jnsbb-op-89-1760-minio-2                                Running     0            3h30m     10.104.14.238     4am-node18     
fouramf-jnsbb-op-89-1760-minio-3                                Running     0            3h30m     10.104.24.8       4am-node29  
```
server - after upgrade: 
```
fouramf-jnsbb-op-89-1760-milvus-datacoord-648b4f7f4d-bk4tf      Running     0            2m        10.104.1.174      4am-node10     
fouramf-jnsbb-op-89-1760-milvus-datanode-69dd44947d-wfkfg       Running     0            2m        10.104.1.167      4am-node10     
fouramf-jnsbb-op-89-1760-milvus-indexcoord-7547ff87d-hzr8g      Running     0            2m        10.104.14.8       4am-node18     
fouramf-jnsbb-op-89-1760-milvus-indexnode-b9cbdcfc-h8lk4        Running     0            2m        10.104.14.7       4am-node18     
fouramf-jnsbb-op-89-1760-milvus-proxy-85d8c7d59-qq8br           Running     0            2m        10.104.12.50      4am-node17     
fouramf-jnsbb-op-89-1760-milvus-querycoord-5d54b54778-cdznw     Running     0            2m        10.104.12.51      4am-node17     
fouramf-jnsbb-op-89-1760-milvus-querynode-5898ddf567-fp2rp      Running     0            1m        10.104.5.116      4am-node12     
fouramf-jnsbb-op-89-1760-milvus-querynode-5898ddf567-jk5rz      Running     0            2m        10.104.12.52      4am-node17     
fouramf-jnsbb-op-89-1760-milvus-querynode-6fd9f447cd-ndm5k      Running     0            3h31m     10.104.24.9       4am-node29     
fouramf-jnsbb-op-89-1760-milvus-querynode-6fd9f447cd-vx646      Running     0            3h31m     10.104.18.65      4am-node25     
fouramf-jnsbb-op-89-1760-milvus-rootcoord-5f88dd5868-4kssp      Running     0            2m        10.104.1.168      4am-node10     
fouramf-jnsbb-op-89-1760-etcd-0                                 Running     0            3h32m     10.104.18.58      4am-node25     
fouramf-jnsbb-op-89-1760-etcd-1                                 Running     0            3h32m     10.104.24.5       4am-node29     
fouramf-jnsbb-op-89-1760-etcd-2                                 Running     0            3h32m     10.104.19.67      4am-node28     
fouramf-jnsbb-op-89-1760-kafka-0                                Running     2            3h32m     10.104.18.59      4am-node25     
fouramf-jnsbb-op-89-1760-kafka-1                                Running     0            3h32m     10.104.13.232     4am-node16     
fouramf-jnsbb-op-89-1760-kafka-2                                Running     1            3h32m     10.104.14.240     4am-node18     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-0                      Running     0            3h32m     10.104.24.6       4am-node29     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-1                      Running     0            3h32m     10.104.14.241     4am-node18     
fouramf-jnsbb-op-89-1760-kafka-zookeeper-2                      Running     0            3h32m     10.104.18.63      4am-node25     
fouramf-jnsbb-op-89-1760-minio-0                                Running     0            3h32m     10.104.18.62      4am-node25     
fouramf-jnsbb-op-89-1760-minio-1                                Running     0            3h32m     10.104.13.231     4am-node16     
fouramf-jnsbb-op-89-1760-minio-2                                Running     0            3h32m     10.104.14.238     4am-node18     
fouramf-jnsbb-op-89-1760-minio-3                                Running     0            3h32m     10.104.24.8       4am-node29     
```


client log :
![image](https://github.com/milvus-io/milvus/assets/48523564/9a960823-4f93-401a-a718-5e06dd8c3b60)
Almost all searches since 06:04:09 have failed with the error "query failed: segment not found". 
![image](https://github.com/milvus-io/milvus/assets/48523564/46fca78d-5285-4406-893b-1787e04f1138)

**Comment by weiliu1031** [comment]
'segment not found' already be fixed in #26908, please verify this with latest image @elstic

**Comment by elstic** [comment]
v2.2.14 -> master-20230914-edde3cf1

#### Serious problems still exist after rolling upgrade

After the upgrade, 93% of the load interfaces failed, and almost all scence_tests failed.


client error log:
![image](https://github.com/milvus-io/milvus/assets/48523564/7b00f58b-4515-42bd-bbaa-21ef012e14b4)
![image](https://github.com/milvus-io/milvus/assets/48523564/a57cd544-af37-4b74-9e0b-a62d05a9eeaf)
![image](https://github.com/milvus-io/milvus/assets/48523564/359b3375-03bd-49bf-b883-69558e25d8ca)
![image](https://github.com/milvus-io/milvus/assets/48523564/06f82334-0f5f-4127-8b83-75157aa34b83)
client pod: fouramf-rbr7f-1370010765

before upgrade:
```
fouramf-rbr7f-op-80-5852-milvus-datacoord-7449df7c5-x2pbg       Running     0            1h14m     10.104.13.150     4am-node16     
fouramf-rbr7f-op-80-5852-milvus-datanode-6dbb5c4bbc-5d5gv       Running     0            1h14m     10.104.19.165     4am-node28     
fouramf-rbr7f-op-80-5852-milvus-indexcoord-656dd7dc79-r4r5t     Running     0            1h14m     10.104.19.166     4am-node28     
fouramf-rbr7f-op-80-5852-milvus-indexnode-cfb99f5c4-l9ck9       Running     0            1h14m     10.104.4.96       4am-node11     
fouramf-rbr7f-op-80-5852-milvus-proxy-7bfbd8b4d-2zq9r           Running     0            1h14m     10.104.19.164     4am-node28     
fouramf-rbr7f-op-80-5852-milvus-querycoord-7585bf4b99-qgz9r     Running     0            1h14m     10.104.4.94       4am-node11     
fouramf-rbr7f-op-80-5852-milvus-querynode-567f68ddd-2qnvm       Running     0            1h14m     10.104.13.153     4am-node16     
fouramf-rbr7f-op-80-5852-milvus-querynode-567f68ddd-4sgvw       Running     0            1h14m     10.104.12.32      4am-node17     
fouramf-rbr7f-op-80-5852-milvus-rootcoord-6bffbb8fcf-4qp2d      Running     0            1h14m     10.104.12.30      4am-node17     
fouramf-rbr7f-op-80-5852-etcd-0                                 Running     0            1h17m     10.104.13.128     4am-node16     
fouramf-rbr7f-op-80-5852-etcd-1                                 Running     0            1h17m     10.104.12.12      4am-node17     
fouramf-rbr7f-op-80-5852-etcd-2                                 Running     0            1h17m     10.104.19.152     4am-node28     
fouramf-rbr7f-op-80-5852-kafka-0                                Running     0            1h17m     10.104.13.127     4am-node16     
fouramf-rbr7f-op-80-5852-kafka-1                                Running     0            1h17m     10.104.12.17      4am-node17     
fouramf-rbr7f-op-80-5852-kafka-2                                Running     0            1h17m     10.104.18.17      4am-node25     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-0                      Running     0            1h17m     10.104.13.129     4am-node16     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-1                      Running     0            1h17m     10.104.19.157     4am-node28     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-2                      Running     0            1h17m     10.104.12.18      4am-node17     
fouramf-rbr7f-op-80-5852-minio-0                                Running     0            1h17m     10.104.13.126     4am-node16     
fouramf-rbr7f-op-80-5852-minio-1                                Running     0            1h17m     10.104.12.14      4am-node17     
fouramf-rbr7f-op-80-5852-minio-2                                Running     0            1h17m     10.104.19.154     4am-node28     
fouramf-rbr7f-op-80-5852-minio-3                                Running     0            1h17m     10.104.14.224     4am-node18 
```

after upgrade:
```
fouramf-rbr7f-op-80-5852-milvus-datacoord-5d5b467bb6-dpzqx     Running     0            2m        10.104.13.51      4am-node16     
fouramf-rbr7f-op-80-5852-milvus-datanode-6dbb5c4bbc-5d5gv      Running     0            1h17m     10.104.19.165     4am-node28     
fouramf-rbr7f-op-80-5852-milvus-datanode-858954cb76-lwr86      Running     0            2m        10.104.24.94      4am-node29     
fouramf-rbr7f-op-80-5852-milvus-indexcoord-c745df7f6-vg2xz     Running     0            2m        10.104.6.126      4am-node13     
fouramf-rbr7f-op-80-5852-milvus-indexnode-77cc967947-8c5dm     Running     0            2m        10.104.13.49      4am-node16     
fouramf-rbr7f-op-80-5852-milvus-proxy-6b58955bcf-mqvpj         Running     0            2m        10.104.24.96      4am-node29     
fouramf-rbr7f-op-80-5852-milvus-querycoord-6465b59bd-dzlsk     Running     1            2m        10.104.24.97      4am-node29     
fouramf-rbr7f-op-80-5852-milvus-querynode-567f68ddd-2qnvm      Running     0            1h17m     10.104.13.153     4am-node16     
fouramf-rbr7f-op-80-5852-milvus-querynode-567f68ddd-4sgvw      Running     0            1h17m     10.104.12.32      4am-node17     
fouramf-rbr7f-op-80-5852-milvus-querynode-5bc86ddb5c-mtglc     Running     0            2m        10.104.24.98      4am-node29     
fouramf-rbr7f-op-80-5852-milvus-querynode-5bc86ddb5c-wbf7z     Running     0            1m        10.104.1.140      4am-node10     
fouramf-rbr7f-op-80-5852-milvus-rootcoord-58d8b5586b-kl49r     Running     0            2m        10.104.24.93      4am-node29     
fouramf-rbr7f-op-80-5852-milvus-rootcoord-6bffbb8fcf-4qp2d     Running     0            1h17m     10.104.12.30      4am-node17     
fouramf-rbr7f-op-80-5852-etcd-0                                Running     0            1h19m     10.104.13.128     4am-node16     
fouramf-rbr7f-op-80-5852-etcd-1                                Running     0            1h19m     10.104.12.12      4am-node17     
fouramf-rbr7f-op-80-5852-etcd-2                                Running     0            1h19m     10.104.19.152     4am-node28     
fouramf-rbr7f-op-80-5852-kafka-0                               Running     0            1h19m     10.104.13.127     4am-node16     
fouramf-rbr7f-op-80-5852-kafka-1                               Running     0            1h19m     10.104.12.17      4am-node17     
fouramf-rbr7f-op-80-5852-kafka-2                               Running     0            1h19m     10.104.18.17      4am-node25     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-0                     Running     0            1h19m     10.104.13.129     4am-node16     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-1                     Running     0            1h19m     10.104.19.157     4am-node28     
fouramf-rbr7f-op-80-5852-kafka-zookeeper-2                     Running     0            1h19m     10.104.12.18      4am-node17     
fouramf-rbr7f-op-80-5852-minio-0                               Running     0            1h19m     10.104.13.126     4am-node16     
fouramf-rbr7f-op-80-5852-minio-1                               Running     0            1h19m     10.104.12.14      4am-node17     
fouramf-rbr7f-op-80-5852-minio-2                               Running     0            1h19m     10.104.19.154     4am-node28     
fouramf-rbr7f-op-80-5852-minio-3                               Running     0            1h19m     10.104.14.224     4am-node18  
```

upgrade argo task : fouramf-tvg7w , client argo task: fouramf-rbr7f

#### The upgrade started at approximately 4:03:01 and ended at 4:04:41, but most interfaces failed after the upgrade.




#### Steps 
```
1. deploy milvus and set enableActiveStandby to true
  2. create a collection  
  3. build an HNSW index on the vector column
  4. insert 10 million vectors
  5. flush collection
  6. build index on vector column with the same parameters  
  7. count the total number of rows
  8. load collection
  9. execute concurrent search, query,load,scene_test 
    (scene_test steps: 
       1） Create a collection 2） Insert 3000 pieces of data  3） flush collection 
       4） Create an index  5） drop collection)
  10. upgrading milvus while doing step 9
```

**Comment by weiliu1031** [comment]
> fouramf-rbr7f-op-80-5852-milvus-datacoord-5d5b467bb6-dpzqx

rolling upgrade succeed, but after that, datacoord restarts again and again, which fails all the operation.

**Comment by weiliu1031** [comment]
> > fouramf-rbr7f-op-80-5852-milvus-datacoord-5d5b467bb6-dpzqx
> 
> rolling upgrade succeed, but after that, datacoord restarts again and again, which fails all the operation.

during the test progress, the collection num reach 8k, and then the kafka thread num reach the os limit, then datacoord panic. 
![image](https://github.com/milvus-io/milvus/assets/108661493/29914b1a-31bf-4d5b-b922-ad7ebbafb56f)

then datacoord try to recover, every time it start, the thread num inceases to 30k, then datacoord panic again.
![2Ki3tMYPuY](https://github.com/milvus-io/milvus/assets/108661493/050caac1-b7ea-4d21-95ac-a9dec6275ed3)

**Comment by weiliu1031** [comment]
> > > fouramf-rbr7f-op-80-5852-milvus-datacoord-5d5b467bb6-dpzqx
> > 
> > 
> > rolling upgrade succeed, but after that, datacoord restarts again and again, which fails all the operation.
> 
> during the test progress, the collection num reach 8k, and then the kafka thread num reach the os limit, then datacoord panic. ![image](https://user-images.githubusercontent.com/108661493/267954440-29914b1a-31bf-4d5b-b922-ad7ebbafb56f.png)
> 
> then datacoord try to recover, every time it start, the thread num inceases to 30k, then datacoord panic again. ![2Ki3tMYPuY](https://user-images.githubusercontent.com/108661493/267955030-050caac1-b7ea-4d21-95ac-a9dec6275ed3.jpg)

due to the  `GetFlushState` compatibility caused by #27077,  the scene test failed and it won't drop the collection, then the collection num increase to 8k, which causes the panic in datacoord.

please verify this with the latest 2.3 image, @elstic

**Comment by elstic** [comment]
client argo task : fouramf-72wjd , upgrade argo task : fouramf-jbvn4

milvus did not provide normal services between 03:46:50 ~ 3:48:07 and was interrupted for 1 minute and 17 seconds.

**Comment by yanliang567** [comment]
close, as it is acceptable when upgrading from 2.2.x to 2.3.x in a min
