### ISSUE TITLE
[Bug]: [benchmark][DiskANN] Memory leak when index build fails

### ISSUE THREAD

**Issue by elstic** [milvus-io/milvus#30669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240206-715f0429
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- Disk (NVMe or SATA): NVMe
```

### Current Behavior

After inserting 100 million 128d data, build an index and hang.

server :
```
spring-stability-test2-27-1263-etcd-0                             1/1     Running       0                 7m34s   10.104.21.230   4am-node24   <none>           <none>
spring-stability-test2-27-1263-etcd-1                             1/1     Running       0                 7m34s   10.104.19.156   4am-node28   <none>           <none>
spring-stability-test2-27-1263-etcd-2                             1/1     Running       0                 7m33s   10.104.17.96    4am-node23   <none>           <none>
spring-stability-test2-27-1263-milvus-datacoord-7f8975b955r47j2   1/1     Running       0                 7m34s   10.104.21.219   4am-node24   <none>           <none>
spring-stability-test2-27-1263-milvus-datanode-b668bf594-vrb4q    1/1     Running       1 (3m4s ago)      7m34s   10.104.23.32    4am-node27   <none>           <none>
spring-stability-test2-27-1263-milvus-indexcoord-78dc44676kjnlx   1/1     Running       0                 7m34s   10.104.17.92    4am-node23   <none>           <none>
spring-stability-test2-27-1263-milvus-indexnode-69c9f4cd94l4fwc   1/1     Running       0                 7m34s   10.104.31.114   4am-node34   <none>           <none>
spring-stability-test2-27-1263-milvus-proxy-f497fdb74-9thcv       1/1     Running       1 (3m3s ago)      7m34s   10.104.21.218   4am-node24   <none>           <none>
spring-stability-test2-27-1263-milvus-querycoord-65dff8dfbsnzbf   1/1     Running       1 (3m3s ago)      7m34s   10.104.21.220   4am-node24   <none>           <none>
spring-stability-test2-27-1263-milvus-querynode-6459785fc676qwl   1/1     Running       0                 7m34s   10.104.20.163   4am-node22   <none>           <none>
spring-stability-test2-27-1263-milvus-rootcoord-6fcfbb9f9fbv8ld   1/1     Running       1 (3m3s ago)      7m34s   10.104.21.221   4am-node24   <none>           <none>
spring-stability-test2-27-1263-minio-0                            1/1     Running       0                 7m34s   10.104.21.229   4am-node24   <none>           <none>
spring-stability-test2-27-1263-minio-1                            1/1     Running       0                 7m34s   10.104.19.154   4am-node28   <none>           <none>
spring-stability-test2-27-1263-minio-2                            1/1     Running       0                 7m34s   10.104.16.131   4am-node21   <none>           <none>
spring-stability-test2-27-1263-minio-3                            1/1     Running       0                 7m34s   10.104.17.94    4am-node23   <none>           <none>
spring-stability-test2-27-1263-pulsar-bookie-0                    1/1     Running       0                 7m34s   10.104.21.232   4am-node24   <none>           <none>
spring-stability-test2-27-1263-pulsar-bookie-1                    1/1     Running       0                 7m34s   10.104.19.157   4am-node28   <none>           <none>
spring-stability-test2-27-1263-pulsar-bookie-2                    1/1     Running       0                 7m33s   10.104.16.136   4am-node21   <none>           <none>
spring-stability-test2-27-1263-pulsar-bookie-init-kphwf           0/1     Completed     0                 7m34s   10.104.1.203    4am-node10   <none>           <none>
spring-stability-test2-27-1263-pulsar-broker-0                    1/1     Running       0                 7m34s   10.104.1.204    4am-node10   <none>           <none>
spring-stability-test2-27-1263-pulsar-proxy-0                     1/1     Running       0                 7m34s   10.104.12.146   4am-node17   <none>           <none>
spring-stability-test2-27-1263-pulsar-pulsar-init-tjpjp           0/1     Completed     0                 7m34s   10.104.1.206    4am-node10   <none>           <none>
spring-stability-test2-27-1263-pulsar-recovery-0                  1/1     Running       0                 7m34s   10.104.1.205    4am-node10   <none>           <none>
spring-stability-test2-27-1263-pulsar-zookeeper-0                 1/1     Running       0                 7m34s   10.104.21.233   4am-node24   <none>           <none>
spring-stability-test2-27-1263-pulsar-zookeeper-1                 1/1     Running       0                 6m41s   10.104.17.98    4am-node23   <none>           <none>
spring-stability-test2-27-1263-pulsar-zookeeper-2                 1/1     Running       0                 6m5s    10.104.19.159   4am-node28   <none>
```

![image](https://github.com/milvus-io/milvus/assets/48523564/a4f121e9-0aa1-4fd7-a373-73ccc1ffad9c)

indexnode memory usage:
![image](https://github.com/milvus-io/milvus/assets/48523564/919ed77f-1119-4b4b-823e-b18655cd647c)

indexnode resource: 8c64G

client log:
```
[2024-02-07 03:51:38,055 -  INFO - fouram]: [Base] Start inserting, ids: 99950000 - 99999999, data size: 100,000,000 (base.
py:342)
[2024-02-07 03:51:39,757 -  INFO - fouram]: [Time] Collection.insert run in 1.7009s (api_request.py:49)
[2024-02-07 03:51:39,760 -  INFO - fouram]: [Base] Number of vectors in the collection(fouram_GnQ56JJw): 99900000 (base.py:
491)
[2024-02-07 03:51:39,836 -  INFO - fouram]: [Base] Total time of insert: 3925.2201s, average number of vector bars inserted
 per second: 25476.2784, average time to insert 50000 vectors per time: 1.9626s (base.py:396)
[2024-02-07 03:51:39,837 -  INFO - fouram]: [Base] Start flush collection fouram_GnQ56JJw (base.py:307)
[2024-02-07 03:51:42,381 -  INFO - fouram]: [Base] Index params of fouram_GnQ56JJw:[{'float_vector': {'index_type': 'DISKAN
N', 'metric_type': 'L2', 'params': {}}}] (base.py:464)
[2024-02-07 03:51:42,381 -  INFO - fouram]: [Base] Start release collection fouram_GnQ56JJw (base.py:318)
[2024-02-07 03:51:42,388 -  INFO - fouram]: [Base] Start build index of DISKANN for field:float_vector collection:fouram_Gn
Q56JJw, params:{'index_type': 'DISKANN', 'metric_type': 'L2', 'params': {}} (base.py:445)
```
indexcoord - index task count:
![image](https://github.com/milvus-io/milvus/assets/48523564/553bc6e6-5cbd-4a60-9979-08ca008f95de)

### Steps To Reproduce

```markdown
1. create a collection 
  2. build an DiskANN index on the vector column
  3. insert 100 million vectors
  4. flush collection
  5. build index on vector column with the same parameters => fail
```

**Comment by yanliang567** [comment]
/assign @foxspy 
please assign back as the fix pr merged

**Comment by elstic** [comment]
> how large is the segment size?

default value, 2G

**Comment by xiaofan-luan** [comment]
/assign @liliu-z 
seems that there is memory leakage in diskann indexbuild?

**Comment by elstic** [comment]
This issue has been fixed.
Verify image:master-20240219-43e8cd53-amd64

**Comment by liliu-z** [comment]
Let's keep it open. 
We still don't know why there are memory leakage when index building get failed.
@elstic

**Comment by PwzXxm** [comment]
Reproduce and run with valgrind, shows the following, PR WIP
<img width="781" alt="image" src="https://github.com/milvus-io/milvus/assets/6563846/ee216c9a-7335-4483-b667-1e56040c90dd">

**Comment by elstic** [comment]
No recent problems with diskann build index failures
