### ISSUE TITLE
[Bug]:[most urgent]segment can not loaded beacuse of index_null_offset not existed.

### ISSUE THREAD

**Issue by melon1507** [milvus-io/milvus#39889]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.5.4
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):kafka
- SDK version(e.g. pymilvus v2.0.0rc2):2.5.4
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Step1. Using Milvus 2.5.0, a collection was created with 500 partitions. This collection includes an IVF_FLAT type index. The collection schema is as follows:
`schema = MilvusClient.create_schema(
    auto_id=False,
    enable_dynamic_field=True,
)

schema.add_field(field_name="image_id", datatype=DataType.VARCHAR, is_primary=True, max_length=50, auto_id=False)
schema.add_field(field_name="image_vector", datatype=DataType.FLOAT_VECTOR, dim=1024)
schema.add_field(field_name="image_desc", datatype=DataType.VARCHAR, max_length=150, enable_analyzer=True, enable_match=True, analyzer_params={"type": "chinese"})
schema.add_field(field_name="index", datatype=DataType.VARCHAR, max_length=50)

index_params = client.prepare_index_params()

index_params.add_index(
    field_name="image_vector",
    index_type="IVF_FLAT",
    index_name="image_vector_index",
    metric_type="COSINE"
)`
Step2.The program started normally, but after running for a month, it failed to load the partition, which caused the vector search to be unavailable.the reason likes as follows:
2025/02/14 06:44:40.286 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]

### Expected Behavior

The issue persists even after exporting the data from version 2.5.0 to the directory of version 2.5.4.I tried deleting the index and recreating it, but the issue was not resolved.

### Steps To Reproduce

```markdown
Created a collection in v2.5.0 or lower using the schema above and then upgrade Milvus to v2.5.4. Check if the collection can be loaded.
```

### Milvus Log

I20250214 06:44:39.216392   646 InvertedIndexTantivy.cpp:113] [SERVER][~InvertedIndexTantivy][CGO_LOAD][]inverted index remove path:
[2025/02/14 06:44:39.248 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]
[2025/02/14 06:44:39.248 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]
[2025/02/14 06:44:39.289 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]
I20250214 06:44:40.195726   646 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 100 with num_rows 1
I20250214 06:44:40.195737   675 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 101 with num_rows 1
I20250214 06:44:40.195974   646 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 100 task to thread pool
I20250214 06:44:40.195771   643 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 104 with num_rows 816
I20250214 06:44:40.195722   548 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 104 with num_rows 1
I20250214 06:44:40.195744   587 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 104 with num_rows 3
I20250214 06:44:40.196064   548 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 104 task to thread pool
I20250214 06:44:40.196076   587 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 104 task to thread pool
I20250214 06:44:40.195799   244 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 100 with num_rows 3
I20250214 06:44:40.196004   675 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 101 task to thread pool
I20250214 06:44:40.195820   586 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 100 with num_rows 816
I20250214 06:44:40.195833   553 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 103 with num_rows 1
I20250214 06:44:40.196048   643 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 104 task to thread pool
I20250214 06:44:40.196403   586 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 100 task to thread pool
I20250214 06:44:40.196481   244 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 100 task to thread pool
I20250214 06:44:40.196491   553 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 103 task to thread pool
I20250214 06:44:40.196635   646 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 100 mmap false done
I20250214 06:44:40.196679   675 IndexConfigGenerator.cpp:71] [SERVER][VecIndexConfig][CGO_LOAD][]VecIndexConfig: origin_index_type=IVF_FLAT, index_type=IVF_FLAT_CC, metric_type=COSINE, config={"metric_type":"COSINE","nlist":"128","ssize":"48"}
I20250214 06:44:40.196704   675 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 101 mmap false done
I20250214 06:44:40.196782   587 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 104 mmap false done
I20250214 06:44:40.196796   675 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 0 with num_rows 1
I20250214 06:44:40.196877   646 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 102 with num_rows 816
I20250214 06:44:40.197628   675 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 0 task to thread pool
I20250214 06:44:40.196887   548 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 104 mmap false done
I20250214 06:44:40.197664   646 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 102 task to thread pool
I20250214 06:44:40.197796   548 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 0 with num_rows 816
I20250214 06:44:40.197830   548 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 0 task to thread pool
I20250214 06:44:40.197836   675 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 0 mmap false done
I20250214 06:44:40.197031   244 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 100 mmap false done
I20250214 06:44:40.197440   586 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 100 mmap false done
I20250214 06:44:40.197953   587 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 101 with num_rows 3
I20250214 06:44:40.197986   587 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 101 task to thread pool
I20250214 06:44:40.197553   553 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 103 mmap false done
I20250214 06:44:40.197990   586 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 1 with num_rows 1
I20250214 06:44:40.198027   586 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 1 task to thread pool
I20250214 06:44:40.198040   244 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 0 with num_rows 3
I20250214 06:44:40.198071   244 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 0 task to thread pool
I20250214 06:44:40.198122   553 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 1 with num_rows 816
I20250214 06:44:40.198141   553 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 1 task to thread pool
I20250214 06:44:40.198184   643 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 104 mmap false done
I20250214 06:44:40.198313   675 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 103 with num_rows 3
I20250214 06:44:40.198355   675 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 103 task to thread pool
I20250214 06:44:40.198370   244 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 0 mmap false done
I20250214 06:44:40.198444   643 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 103 with num_rows 816
I20250214 06:44:40.198463   587 IndexConfigGenerator.cpp:71] [SERVER][VecIndexConfig][CGO_LOAD][]VecIndexConfig: origin_index_type=IVF_FLAT, index_type=IVF_FLAT_CC, metric_type=COSINE, config={"metric_type":"COSINE","nlist":"128","ssize":"48"}
I20250214 06:44:40.198508   587 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 101 mmap false done
I20250214 06:44:40.198534   586 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 1 mmap false done
I20250214 06:44:40.198565   244 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 1 with num_rows 3
I20250214 06:44:40.198590   643 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 103 task to thread pool
I20250214 06:44:40.198640   244 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 1 task to thread pool
I20250214 06:44:40.198699   553 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 1 mmap false done
I20250214 06:44:40.198450   548 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 0 mmap false done
I20250214 06:44:40.198683   586 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 102 with num_rows 1
I20250214 06:44:40.198815   586 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 submits load field 102 task to thread pool
I20250214 06:44:40.198827   675 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 103 mmap false done
I20250214 06:44:40.198916   675 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 101 with num_rows 816
I20250214 06:44:40.198941   675 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 submits load field 101 task to thread pool
I20250214 06:44:40.198982   244 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 1 mmap false done
I20250214 06:44:40.199023   646 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 102 mmap false done
I20250214 06:44:40.199025   548 ChunkedSegmentSealedImpl.cpp:268] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 102 with num_rows 3
I20250214 06:44:40.199105   548 ChunkedSegmentSealedImpl.cpp:282] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 submits load field 102 task to thread pool
I20250214 06:44:40.199169   586 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831877730 loads field 102 mmap false done
I20250214 06:44:40.199206   643 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 103 mmap false done
 => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51

I20250214 06:44:40.199466   643 InvertedIndexTantivy.cpp:113] [SERVER][~InvertedIndexTantivy][CGO_LOAD][]inverted index remove path:
I20250214 06:44:40.199766   548 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175827916719 loads field 102 mmap false done
 => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51

I20250214 06:44:40.203465   548 InvertedIndexTantivy.cpp:113] [SERVER][~InvertedIndexTantivy][CGO_LOAD][]inverted index remove path:
I20250214 06:44:40.206964   675 IndexConfigGenerator.cpp:71] [SERVER][VecIndexConfig][CGO_LOAD][]VecIndexConfig: origin_index_type=IVF_FLAT, index_type=IVF_FLAT_CC, metric_type=COSINE, config={"metric_type":"COSINE","nlist":"128","ssize":"48"}
I20250214 06:44:40.207391   675 ChunkedSegmentSealedImpl.cpp:293] [SERVER][LoadFieldData][CGO_LOAD][]segment 455305175831852528 loads field 101 mmap false done
 => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51

I20250214 06:44:40.214983   675 InvertedIndexTantivy.cpp:113] [SERVER][~InvertedIndexTantivy][CGO_LOAD][]inverted index remove path:
[2025/02/14 06:44:40.246 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175831877731/0/455210079704244207/455305175831877730/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]
[2025/02/14 06:44:40.286 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175831852529/0/455210079704241976/455305175831852528/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]
[2025/02/14 06:44:40.286 +00:00] [ERROR] [funcutil/parallel.go:89] [loadSegmentFunc] [error="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n"] [errorVerbose="At LoadSegment:  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/internal/querynodev2/segments.(*segmentLoader).Load.func5\n  | \t/workspace/source/internal/querynodev2/segments/segment_loader.go:348\n  | github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n  | \t/workspace/source/pkg/util/funcutil/parallel.go:87\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/src/runtime/asm_amd64.s:1695\nWraps: (2) At LoadSegment\nWraps: (3)  => invalid local path:/var/lib/milvus/data/index_files/455305175827916720/0/455210079704244993/455305175827916719/index_null_offset at /workspace/source/internal/core/src/storage/LocalChunkManager.cpp:51\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"] [idx=0] [stack="github.com/milvus-io/milvus/pkg/util/funcutil.ProcessFuncParallel.func3\n\t/workspace/source/pkg/util/funcutil/parallel.go:89"]

### Anything else?

Are there any other ways to temporarily avoid this problem? The inability to load data is causing the database to be unable to perform query operations, which has a significant impact.

**Comment by yanliang567** [comment]
@melon0803 please attach the milvus logs for investigation.
If you install Milvus with k8s, please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs.
If you install Milvus with docker-compose, please use docker-compose logs > milvus.log to export the logs.

/assign @melon0803

**Comment by melon0803** [comment]
[logs.tar.gz](https://github.com/user-attachments/files/18795351/logs.tar.gz)This is the k8s pod log I exported using export-milvus-log.sh.

**Comment by joenzx** [comment]
I have similar problems, waiting for solutions

**Comment by smellthemoon** [comment]
<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/c0df83cc-b6d0-46d2-bf7a-846053839b7c" />
From this log, we can see all the index files were missed. Text index will be build if you set **enable_match = true**, which can not be rebuild now. Are you rebuilding on a vector column? @melon0803

**Comment by smellthemoon** [comment]
It related with https://github.com/milvus-io/milvus/issues/39635. Try to load on dropped segment, which has gced index binlog.

**Comment by smellthemoon** [comment]
you can try to release it and load collection again. @melon0803

**Comment by Andy6132024** [comment]
@smellthemoon release and load didn't work for us. It still got stuck. Also drop/recreate indexes didn't help either.

**Comment by melon0803** [comment]
> <img alt="Image" width="1350" src="https://private-user-images.githubusercontent.com/64083300/413265294-c0df83cc-b6d0-46d2-bf7a-846053839b7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk1MjkyMTUsIm5iZiI6MTczOTUyODkxNSwicGF0aCI6Ii82NDA4MzMwMC80MTMyNjUyOTQtYzBkZjgzY2MtYjZkMC00NmQyLWJmN2EtODQ2MDUzODM5YjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjE0VDEwMjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkN2MzNGRmOTBiMDA2Zjg3Mzk3MGEwZTg3N2Q4ODNjYzkzMDQwMGRmMDBiZGM0ODdkYzFkN2U0ZGNiMzY3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5VvK6bYhZN8zvy1E_gr-2gktjnInOCLgIWKIupzTgPo"> From this log, we can see all the index files were missed. Text index will be build if you set **enable_match = true**, which can not be rebuild now. Are you rebuilding on a vector column? [@melon0803](https://github.com/melon0803)

yes, you are right. I have two fields.
1. The first one is image_desc, with the schema defined as follows:
schema.add_field(field_name="image_desc", datatype=DataType.VARCHAR, max_length=150, enable_analyzer=True, enable_match=True, analyzer_params={"type": "chinese"})
2. The second field is image_vector, with the schema defined as:
schema.add_field(field_name="image_vector", datatype=DataType.FLOAT_VECTOR, dim=1024)
index_params.add_index(
    field_name="image_vector",
    index_type="IVF_FLAT",
    index_name="image_vector_index",
    metric_type="COSINE"
)

**Comment by melon0803** [comment]
> It related with [#39635](https://github.com/milvus-io/milvus/issues/39635). Try to load on dropped segment, which has gced index binlog.
can you tell me how to load data onto a dropped segment?

**Comment by smellthemoon** [comment]
> > It related with [#39635](https://github.com/milvus-io/milvus/issues/39635). Try to load on dropped segment, which has gced index binlog.
> > can you tell me how to load data onto a dropped segment?

sorry. I meant the root cause of this issue is that load on dropped segment.

**Comment by melon0803** [comment]
> > [@smellthemoon](https://github.com/smellthemoon) release and load didn't work for us. It still got stuck at loading. Also drop/recreate indexes didn't help either.
> 
> drop/recreate vector index will do no effect, because the index is build in scalar field. And text index can not be rebuild now. If release collection and load collection not work to you, could you help to provide your log?

[logs.tar.gz](https://github.com/user-attachments/files/18797972/logs.tar.gz) this is my log in k8s，log only for release collection and load collection.

**Comment by melon0803** [comment]
> > [@smellthemoon](https://github.com/smellthemoon) release and load didn't work for us. It still got stuck at loading. Also drop/recreate indexes didn't help either.
> 
> drop/recreate vector index will do no effect, because the index is build in scalar field. And text index can not be rebuild now. If release collection and load collection not work to you, could you help to provide your log for investigation?

but index_null_offset param, if normal, the value is IVF_FLAT file. what this means?

**Comment by smellthemoon** [comment]
> > > [@smellthemoon](https://github.com/smellthemoon) release and load didn't work for us. It still got stuck at loading. Also drop/recreate indexes didn't help either.
> > 
> > 
> > drop/recreate vector index will do no effect, because the index is build in scalar field. And text index can not be rebuild now. If release collection and load collection not work to you, could you help to provide your log for investigation?
> 
> but index_null_offset param, if normal, the value is IVF_FLAT file. what this means?

If a field set **enable_match=True**, will create a text index which is built on "image_desc" field.  IVF_FLAT is built on "image_vector". Now we can not drop the text index by DropIndex request. when create text index, will generate index_null_offset param. IVF_FLAT files will be genereated  when build vector vector. They are two separate columns.

**Comment by melon0803** [comment]
> > > > [@smellthemoon](https://github.com/smellthemoon) release and load didn't work for us. It still got stuck at loading. Also drop/recreate indexes didn't help either.
> > > 
> > > 
> > > drop/recreate vector index will do no effect, because the index is build in scalar field. And text index can not be rebuild now. If release collection and load collection not work to you, could you help to provide your log for investigation?
> > 
> > 
> > but index_null_offset param, if normal, the value is IVF_FLAT file. what this means?
> 
> If a field set **enable_match=True**, will create a text index which is built on "image_desc" field. IVF_FLAT is built on "image_vector". Now we can not drop the text index by DropIndex request. when create text index, will generate index_null_offset param. IVF_FLAT files will be genereated when build vector vector. They are two separate columns.

Thank you. I understand. But index_null_param is not created, how to solve the problem? Can you share your thoughts?

**Comment by xiaofan-luan** [comment]
@yanliang567 
We need to reproduce an fixed it in 2.5.5

**Comment by yanliang567** [comment]
@melon0803 could you please refer to this doc: https://github.com/milvus-io/birdwatcher to backup etcd backup with birdwatcher, and attache the birdwatcher backup file for investigation?

**Comment by congqixia** [comment]
@melon0803 quick question
do you have any other index except vector and text match field?

**Comment by melon0803** [comment]
> [@melon0803](https://github.com/melon0803) quick question do you have any other index except vector and text match field?
I only have 4 fields in a collection, like this:

**Comment by melon0803** [comment]
> [@melon0803](https://github.com/melon0803) could you please refer to this doc: https://github.com/milvus-io/birdwatcher to backup etcd backup with birdwatcher, and attache the birdwatcher backup file for investigation?

Ok, I'll try

**Comment by melon0803** [comment]
> [@melon0803](https://github.com/melon0803) could you please refer to this doc: https://github.com/milvus-io/birdwatcher to backup etcd backup with birdwatcher, and attache the birdwatcher backup file for investigation?

![Image](https://github.com/user-attachments/assets/23562b1a-c64a-4644-a990-92bae16159d5) like this picture, when i execute go install , etcd binary file is not generate success.

**Comment by melon0803** [comment]
> [@melon0803](https://github.com/melon0803) could you please refer to this doc: https://github.com/milvus-io/birdwatcher to backup etcd backup with birdwatcher, and attache the birdwatcher backup file for investigation?

hello, backup file has uploaded.

[bw_etcd_ALL.250217-064143.bak.gz](https://github.com/user-attachments/files/18820956/bw_etcd_ALL.250217-064143.bak.gz)

**Comment by melon1705** [comment]
> [@melon1705](https://github.com/melon1705) after some digging of the backup file, we found that `index_null_offset` for text match index used wrong prefix and got GCed unintentionally. We shall fix this bug in next release. As for your case, you could try compact our collection with this issue, in which could trigger regeneration of index file

Thank you for your answer. but how to compact the specified collection？

**Comment by yanliang567** [comment]
collection.compact() will issue a manual compaction request to the collection. 

> > [@melon1705](https://github.com/melon1705) after some digging of the backup file, we found that `index_null_offset` for text match index used wrong prefix and got GCed unintentionally. We shall fix this bug in next release. As for your case, you could try compact our collection with this issue, in which could trigger regeneration of index file
> 
> Thank you for your answer. but how to compact the specified collection？

**Comment by melon1705** [comment]
> collection.compact() will issue a manual compaction request to the collection.
> 
> > > [@melon1705](https://github.com/melon1705) after some digging of the backup file, we found that `index_null_offset` for text match index used wrong prefix and got GCed unintentionally. We shall fix this bug in next release. As for your case, you could try compact our collection with this issue, in which could trigger regeneration of index file
> > 
> > 
> > Thank you for your answer. but how to compact the specified collection？

sorry, I did it(collection.compact()), but no index rebuild was triggered

**Comment by yanliang567** [comment]
@melon1705  please try 
```
client=MilvusClient(uri="http://10.10.xx.xxx:19530")
client.compact(collection_name)
```
Also I have verified the fix on master-20250219-f47320e0-amd64, which will be released with Milvus 2.5.5 in one day or two

**Comment by melon1705** [comment]
> [@melon1705](https://github.com/melon1705) please try
> 
> ```
> client=MilvusClient(uri="http://10.10.xx.xxx:19530")
> client.compact(collection_name)
> ```
> 
> Also I have verified the fix on master-20250219-f47320e0-amd64, which will be released with Milvus 2.5.5 in one day or two

That's great! After the repair and update, can the historical data be loaded back? Is historical data still available?

**Comment by yanliang567** [comment]
Yes, a manual compaction request shall be issued to fix the existing data.

**Comment by melon1705** [comment]
> Yes, a manual compaction request shall be issued to fix the existing data.

thanks,When will version 2.5.5 be released?

**Comment by melon1705** [comment]
> [@melon1705](https://github.com/melon1705) please try
> 
> ```
> client=MilvusClient(uri="http://10.10.xx.xxx:19530")
> client.compact(collection_name)
> ```
> 
> Also I have verified the fix on master-20250219-f47320e0-amd64, which will be released with Milvus 2.5.5 in one day or two

hello，What is the current situation?

**Comment by melon1705** [comment]
> [@melon1705](https://github.com/melon1705) after some digging of the backup file, we found that `index_null_offset` for text match index used wrong prefix and got GCed unintentionally. We shall fix this bug in next release. As for your case, you could try compact our collection with this issue, in which could trigger regeneration of index file
Our production environment needs to solve this problem quickly. Do you have plans to release 2.5.5 version?

**Comment by Andy6132024** [comment]
We just upgraded to v2.5.5 and followed the instructions to compact the collection first, but we still could not load the collection. It's the same error as before -- could not find `index_null_offset` index file in object storage. This is a very urgent issue.

@yanliang567 @xiaofan-luan Please advise.

**Comment by yanliang567** [comment]
@Andy6132024 please make sure all the compaction tasks completed before reloading the collection. Also you can try to compact the collection with birdwatcher

**Comment by Andy6132024** [comment]
Hi @yanliang567, I just used birdwatcher to compact the collection. I think the compaction is complete. However, I still could not load the collection due to missing index files.

This is what birdwatcher showed, but not sure what `cleaned` represents here.
```
Milvus(by-dev) > show compactions
JobID: 455538097353132783       TaskID: 455538097353132785       Type:MixCompaction      State:completed         StartTime: 1737739994
JobID: 455538097353132783       TaskID: 455538097353132804       Type:MixCompaction      State:completed         StartTime: 1737739994
JobID: 455538097355003746       TaskID: 455538097355003749       Type:MixCompaction      State:completed         StartTime: 1737741134
JobID: 456259722134326253       TaskID: 456259722134326254       Type:MixCompaction      State:cleaned   StartTime: 1740580675
JobID: 456259722135441685       TaskID: 456259722135441694       Type:MixCompaction      State:cleaned   StartTime: 1740600535
JobID: 456259722135442079       TaskID: 456259722135442083       Type:MixCompaction      State:cleaned   StartTime: 1740600595
JobID: 456299533517026725       TaskID: 456299533517026726       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517026725       TaskID: 456299533517026737       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517026725       TaskID: 456299533517026748       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517026725       TaskID: 456299533517026759       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517026725       TaskID: 456299533517026770       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517026725       TaskID: 456299533517026781       Type:MixCompaction      State:cleaned   StartTime: 1740645222
JobID: 456299533517331071       TaskID: 456299533517331073       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517331071       TaskID: 456299533517331084       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517331071       TaskID: 456299533517331096       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517331071       TaskID: 456299533517331107       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517331071       TaskID: 456299533517331118       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517331071       TaskID: 456299533517331129       Type:MixCompaction      State:cleaned   StartTime: 1740647070
JobID: 456299533517640635       TaskID: 456299533517640636       Type:MixCompaction      State:cleaned   StartTime: 1740649766
JobID: 456299533517640635       TaskID: 456299533517640647       Type:MixCompaction      State:cleaned   StartTime: 1740649766
JobID: 456299533517640635       TaskID: 456299533517640658       Type:MixCompaction      State:cleaned   StartTime: 1740649766
JobID: 456299533517640635       TaskID: 456299533517640669       Type:MixCompaction      State:cleaned   StartTime: 1740649766
JobID: 456299533517640635       TaskID: 456299533517640680       Type:MixCompaction      State:cleaned   StartTime: 1740649766
JobID: 456299533517640635       TaskID: 456299533517640691       Type:MixCompaction      State:cleaned   StartTime: 1740649766
--- Total compactions:  24       Matched compactions:  24
```

I assume the goal of compaction is to generate new segments from old segments to circumvent the issue, but some segments remained even after compaction (for example, their size has reached the limit and could not be compacted) so the issue is still there.

**Comment by Andy6132024** [comment]
segment info
```
===============================CollectionID: 454664253305745951===========================
SegmentID: 455418772542458813 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:358370,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455418772542981548 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:360900,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455418772561420656 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:312107,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455538097354393873 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:300722,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455538097355005123 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:347857,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455539520454783778 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:308965,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065933171053 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:295026,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065935348116 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:281882,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065941523546 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065946749079 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065952540238 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455988019627808588 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:343928,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517026727 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517026738 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517026749 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517042820 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517042855 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517099876 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517331085 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517331097 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517331108 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517347439 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517347471 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517402592 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517640670 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517640681 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517640692 PartitionID: 454664253305745956 State: Dropped, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517656459 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:244295,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517713816 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:236325,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517768960 PartitionID: 454664253305745956 State: Flushed, Level: L1, Row Count:262252,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065935609225 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517026760 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517027258 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517331074 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517331364 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517640659 PartitionID: 454664253305745959 State: Dropped, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517640897 PartitionID: 454664253305745959 State: Flushed, Level: L1, Row Count:63845,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065935904939 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517026782 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517147685 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517331130 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517402602 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517640637 PartitionID: 454664253305745960 State: Dropped, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517713840 PartitionID: 454664253305745960 State: Flushed, Level: L1, Row Count:229463,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455601065967157239 PartitionID: 454664253305745967 State: Flushed, Level: L1, Row Count:272573,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 455961976829461428 PartitionID: 454664253305745967 State: Flushed, Level: L1, Row Count:325000,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456259722127505999 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517026771 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517042837 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517331119 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517347458 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: true 
SegmentID: 456299533517640648 PartitionID: 454664253305745967 State: Dropped, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: false 
SegmentID: 456299533517768978 PartitionID: 454664253305745967 State: Flushed, Level: L1, Row Count:202141,  PartitionStatsVersion:0, IsSorted: true 

--- Growing: 0, Sealed: 0, Flushed: 101, Dropped: 48
--- Small Segments: 78, row count: 594914        Other Segments: 23, row count: 6102347
--- Total Segments: 101, row count: 6697261
```

**Comment by xiaofan-luan** [comment]
this is fixed on 2.5.5

**Comment by Andy6132024** [comment]
Hi @xiaofan-luan, with all due respect, I believe the issue was not resolved completely. Could you check the last 5-6 comments, it showed that a couple segments remained (weren't changed to new segments) after **force compaction** through birdwatcher. As I mentioned earlier that I understood the purpose of compaction was to generate new segments to get around this issue; however it seems to me there could still be edge cases that weren't covered. Therefore, the querynode still reported that `index_null_offset` index files were missing and we could not load the collection.

Apart from identifying the root cause, could Milvus team provide temporary resolutions to users who have encountered this issue? For example, what can users do to be unblocked? What other things can they try besides force compaction? 

I tried to backup and restore. The new collection can be loaded properly but it has more entities than the original collection. This is somewhat puzzling but we are willing to get to the bottom of it. We really appreciate the team can take a closer look at this issue again.

cc @congqixia @LoveEachDay

**Comment by congqixia** [comment]
@Andy6132024 sorry for the inconvenience. 
Surely we'd like to help fix this problem. Could you please provide the log during the compaction period and birdwatcher backup file for you instance?

**Comment by Andy6132024** [comment]
@congqixia Much appreciated. I wonder why after every manual-triggered compaction, there always have been same segments which got compacted into new segments (recreated and dropped, no merging happening). My assumption is that they fit into the segment maxSize limit whereas the ones which remained all the way through each compaction apparently exceed the limit. So I read the code related to manual-triggered compaction and maxSize seems to play a key factor. I also need some data to support my point so I went ahead to get the memory size of all Flushed segments. 
```
package main

import (
	"context"
	"log"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/milvus-io/birdwatcher/proto/v2.2/datapb" // use proto from birdwatcher
	clientv3 "go.etcd.io/etcd/client/v3"
)

const dialTimeout = 5 * time.Second

var (
	endpoints = []string{"http://10.233.128.13:2379"}
	segmentPrefixes = map[string][]string{
		"455418772542458813": []string{
			"by-dev/meta/datacoord-meta/binlog/454664253305745951/454664253305745956/455418772542458813",
			"by-dev/meta/datacoord-meta/statslog/454664253305745951/454664253305745956/455418772542458813",
		},
		"456321822546080805": []string{
			"by-dev/meta/datacoord-meta/binlog/454664253305745951/454664253305745959/456321822546080805",
			"by-dev/meta/datacoord-meta/statslog/454664253305745951/454664253305745959/456321822546080805",
		},
                ...
	}
)

func main() {

	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   endpoints,
		DialTimeout: dialTimeout,
	})

	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	ctx := context.Background()

	for segment, prefixes := range segmentPrefixes {
		var size int64
		for _, prefix := range prefixes {
			resp, err := cli.Get(ctx, prefix, clientv3.WithPrefix())
			if err != nil {
				log.Fatal(err)
			}
			
			for _, ev := range resp.Kvs {
				fieldBinlog := &datapb.FieldBinlog{}
				err = proto.Unmarshal(ev.Value, fieldBinlog)
				if err != nil {
					log.Fatal(err)
				}
				for _, binLog := range fieldBinlog.GetBinlogs() {
					size += binLog.MemorySize
				}
			}
		}
		log.Printf("segment: %s, size: %d bytes\n", segment, size)
	}
}
```
It aligned with my assumption that the segments never got compacted are larger than segment maxSize (2Gi). I am not sure if you agree with it. In any case, I plan to increase segment maxSize to see if it can help my case.

**Comment by Andy6132024** [comment]
Update: the collection was loaded successfully after setting segment maxSize from 2Gi to 3Gi. Thanks a lot! @xiaofan-luan @congqixia @LoveEachDay @yanliang567

**Comment by yanliang567** [comment]
> Update: the collection was loaded successfully after setting segment maxSize from 2Gi to 3Gi. Thanks a lot! [@xiaofan-luan](https://github.com/xiaofan-luan) [@congqixia](https://github.com/congqixia) [@LoveEachDay](https://github.com/LoveEachDay) [@yanliang567](https://github.com/yanliang567)

good idea. Updating the segment maxSize will trigger the segment compaction as well.

**Comment by Andy6132024** [comment]
> > Update: the collection was loaded successfully after setting segment maxSize from 2Gi to 3Gi. Thanks a lot! [@xiaofan-luan](https://github.com/xiaofan-luan) [@congqixia](https://github.com/congqixia) [@LoveEachDay](https://github.com/LoveEachDay) [@yanliang567](https://github.com/yanliang567)
> 
> good idea. Updating the segment maxSize will trigger the segment compaction as well.

I still manually triggered the compaction.

**Comment by congqixia** [comment]
@Andy6132024 Thanks for the quick feedback! Based on the information you provided, the compaction behavior seemed abnormal. We'll look into the compaction issue next. Thanks again!

**Comment by congqixia** [comment]
The root cause why compaction task cannot be generated is tracked in this issue #40343

**Comment by yanliang567** [comment]
the manual compaction issue will be fixed in Milvus 2.5.6
