### ISSUE TITLE
[Bug]: [json-inverted] Negative numbers cannot be filtered out by equal expressions ==

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#40707]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: JsDove-polish_jsonstats-4d5cedd-20250314
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2): go
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

-config
```
  config:
    common:
      enabledGrowingSegmentJSONKeyStats: true
      enabledJsonKeyStats: true
    dataCoord:
      enableActiveStandby: true
      enabledJSONKeyStatsInSort: true
    indexCoord:
      enableActiveStandby: true

```
-  case
```
func TestQueryNumberJsonExpr(t *testing.T) {
	ctx := hp.CreateContext(t, time.Second*common.DefaultTimeout)
	mc := hp.CreateDefaultMilvusClient(ctx, t)
	prepare, schema := hp.CollPrepare.CreateCollection(ctx, t, mc, hp.NewCreateCollectionParams(hp.Int64VecJSON), hp.TNewFieldsOption(), hp.TNewSchemaOption())
	prepare.CreateIndex(ctx, t, mc, hp.TNewIndexParams(schema))
	prepare.Load(ctx, t, mc, hp.NewLoadParams(schema.CollectionName))

	// Generate test data with boundary values
	pkColumn := hp.GenColumnData(common.DefaultNb, entity.FieldTypeInt64, *hp.TNewDataOption())
	vecColumn := hp.GenColumnData(common.DefaultNb, entity.FieldTypeFloatVector, *hp.TNewDataOption())
	jsonValues := make([][]byte, 0, common.DefaultNb)

	// Define boundary values for different numeric types
	boundaryValues := map[string]interface{}{
		"int8_min":     int8(-128),
		"int8_max":     int8(127),
		"int16_min":    int16(-32768),
		"int16_max":    int16(32767),
		"int32_min":    int32(-2147483648),
		"int32_max":    int32(2147483647),
		"int64_min":    int64(-9223372036854775808),
		"int64_max":    int64(9223372036854775807),
		"float_min":    float32(-3.402823e+38),
		"float_max":    float32(3.402823e+38),
		"double_min":   float64(-1.7976931348623157e+308),
		"double_max":   float64(1.7976931348623157e+308),
		"array_int8":   []int8{-128, 127},
		"array_int16":  []int16{-32768, 32767},
		"array_int32":  []int32{-2147483648, 2147483647},
		"array_int64":  []int64{-9223372036854775808, 9223372036854775807},
		"array_float":  []float64{-3.402823e+38, 3.402823e+38},
		"array_double": []float64{-1.7976931348623157e+308, 1.7976931348623157e+308},
	}

	// Generate JSON documents
	expCount := 100
	for i := 0; i < common.DefaultNb; i++ {
		m := make(map[string]interface{})
		if i < expCount {
			for k, v := range boundaryValues {
				m[k] = v
			}
		} else {
			// Rest documents contain regular values
			m["val1"] = 0e+1
			m["val2"] = 1e22
			m["val3"] = -0.000000000000000000000000000000000000000000000000000000000000000000000000000001
			m["val4"] = -0
			m["val5"] = -123
			m["val6"] = 123.456e78
			m["val7"] = 123.456789
		}
		bs, _ := json.Marshal(&m)
		jsonValues = append(jsonValues, bs)
	}
	jsonColumn := column.NewColumnJSONBytes(common.DefaultJSONFieldName, jsonValues)
	_, err := mc.Insert(ctx, client.NewColumnBasedInsertOption(schema.CollectionName, pkColumn, vecColumn, jsonColumn))
	common.CheckErr(t, err, true)

	// Test queries with boundary values
	testCases := []struct {
		expr  string
		count int
	}{
		// Test int8 boundary values
		{expr: fmt.Sprintf("%s['int8_min'] == -128", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int8_max'] == 127", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int8'][0] < 0", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int8'][0] == -128", common.DefaultJSONFieldName), count: expCount},

		// Test int16 boundary values
		{expr: fmt.Sprintf("%s['int16_min'] == -32768", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int16_max'] == 32767", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int16'][0] == -32767", common.DefaultJSONFieldName), count: expCount},

		// Test int32 boundary values
		{expr: fmt.Sprintf("%s['int32_min'] == -2147483648", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int32_max'] == 2147483647", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int32'][0] == -2147483647", common.DefaultJSONFieldName), count: expCount},

		// Test int64 boundary values
		{expr: fmt.Sprintf("%s['int64_min'] == -9223372036854775808", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int64_max'] == 9223372036854775807", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int64'][0] == -9223372036854775807", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int64'][1] == 9223372036854775807", common.DefaultJSONFieldName), count: expCount},

		// Test float boundary values (approximate comparison due to floating point precision)
		{expr: fmt.Sprintf("%s['float_min'] <= -3.402823e+38", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['float_max'] >= 3.402823e+38", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_float'][0] == -3.402823e+38", common.DefaultJSONFieldName), count: expCount},

		// Test double boundary values (approximate comparison due to floating point precision)
		{expr: fmt.Sprintf("%s['double_min'] <= -1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['double_max'] >= 1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_double'][0] == -1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_double'][1] == 1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},

		// Test regular value queries
		{expr: fmt.Sprintf("%s['val1'] == 0e+1", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val2'] == 1e22", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val3'] < 0", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val4'] == 0", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val5'] == -123", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val6'] == 123.456e78", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val7'] == 123.456789", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
	}

	for _, tc := range testCases {
		t.Run(tc.expr, func(t *testing.T) {
			countRes, err := mc.Query(ctx, client.NewQueryOption(schema.CollectionName).
				WithConsistencyLevel(entity.ClStrong).
				WithFilter(tc.expr).
				WithOutputFields(common.QueryCountFieldName))
			common.CheckErr(t, err, true)
			count, _ := countRes.Fields[0].GetAsInt64(0)
			require.EqualValues(t, tc.count, count, "Query expression: %s", tc.expr)
		})
	}

```
- result
```
c.query("json['int8_min'] < 0", output_fields=["count(*)"])
data: ["{'count(*)': 0}"]
c.query("json['int8_min'] == -128", output_fields=["count(*)"])
data: ["{'count(*)': 0}"]

c.query("int64 == 101", output_fields=["json"])
data: ["{'int64': 101, 'json': {'val1': 0, 'val2': 1e+22, 'val3': -1e-78, 'val4': 0, 'val5': -123, 'val6': 1.23456e+80, 'val7': 123.456789}}"]
-1e-78 < 0
True
c.query("json['val3'] < 0", output_fields=["json"])
data: []
```

### Steps To Reproduce

```markdown

```

### Milvus Log

pods:
```
zong-json-milvus-datanode-68b4f99b8b-2wxk4                 1/1     Running     0                2m10s   10.104.16.218   4am-node21   <none>           <none>
zong-json-milvus-indexnode-8577ddbfcb-cxt4l                1/1     Running     0                2m10s   10.104.34.44    4am-node37   <none>           <none>
zong-json-milvus-indexnode-8577ddbfcb-xbr5h                1/1     Running     0                89s     10.104.9.245    4am-node14   <none>           <none>
zong-json-milvus-mixcoord-7877c4bc64-gl9jf                 1/1     Running     0                2m10s   10.104.16.219   4am-node21   <none>           <none>
zong-json-milvus-proxy-69448684fb-x5tjc                    1/1     Running     0                2m10s   10.104.15.138   4am-node20   <none>           <none>
zong-json-milvus-querynode-1-55884997b6-pjpjn              1/1     Running     0                115s    10.104.6.133    4am-node13   <none>           <none>
zong-json-milvus-querynode-1-55884997b6-rp9n5              1/1     Running     0                54s     10.104.16.220   4am-node21   <none>           <none>
```

**Comment by JsDove** [comment]
It has been fixed. The reason is that when converting to store values in binary format, the negative values were removed. It was fixed by converting from uint to int.

**Comment by ThreadDao** [comment]
@JsDove Not fixed yet. image: 2.5-20250318-8de5174e-amd64
```
func TestQueryNumberJsonExpr(t *testing.T) {
	//t.Skip("https://github.com/milvus-io/milvus/issues/40707")
	ctx := hp.CreateContext(t, time.Second*common.DefaultTimeout)
	mc := hp.CreateDefaultMilvusClient(ctx, t)
	prepare, schema := hp.CollPrepare.CreateCollection(ctx, t, mc, hp.NewCreateCollectionParams(hp.Int64VecJSON), hp.TNewFieldsOption(), hp.TNewSchemaOption())

	// Generate test data with boundary values
	pkColumn := hp.GenColumnData(common.DefaultNb, entity.FieldTypeInt64, *hp.TNewDataOption())
	vecColumn := hp.GenColumnData(common.DefaultNb, entity.FieldTypeFloatVector, *hp.TNewDataOption())
	jsonValues := make([][]byte, 0, common.DefaultNb)

	// Define boundary values for different numeric types
	boundaryValues := map[string]interface{}{
		"int8_min":     int8(-128),
		"int8_max":     int8(127),
		"int16_min":    int16(-32768),
		"int16_max":    int16(32767),
		"int32_min":    int32(-2147483648),
		"int32_max":    int32(2147483647),
		"int64_min":    int64(-9223372036854775808),
		"int64_max":    int64(9223372036854775807),
		"float_min":    float32(-3.402823e+38),
		"float_max":    float32(3.402823e+38),
		"double_min":   float64(-1.7976931348623157e+308),
		"double_max":   float64(1.7976931348623157e+308),
		"array_int8":   []int8{-128, 127},
		"array_int16":  []int16{-32768, 32767},
		"array_int32":  []int32{-2147483648, 2147483647},
		"array_int64":  []int64{-9223372036854775808, 9223372036854775807},
		"array_float":  []float64{-3.402823e+38, 3.402823e+38},
		"array_double": []float64{-1.7976931348623157e+308, 1.7976931348623157e+308},
	}

	// Generate JSON documents
	expCount := 100
	for i := 0; i < common.DefaultNb; i++ {
		m := make(map[string]interface{})
		if i < expCount {
			for k, v := range boundaryValues {
				m[k] = v
			}
		} else {
			// Rest documents contain regular values
			m["val1"] = 0e+1
			m["val2"] = 1e22
			m["val3"] = -0.000000000000000000000000000000000000000000000000000000000000000000000000000001
			m["val4"] = -0
			m["val5"] = -123
			m["val6"] = 123.456e78
			m["val7"] = 123.456789
		}
		bs, _ := json.Marshal(&m)
		jsonValues = append(jsonValues, bs)
	}
	jsonColumn := column.NewColumnJSONBytes(common.DefaultJSONFieldName, jsonValues)
	_, err := mc.Insert(ctx, client.NewColumnBasedInsertOption(schema.CollectionName, pkColumn, vecColumn, jsonColumn))
	common.CheckErr(t, err, true)
	prepare.CreateIndex(ctx, t, mc, hp.TNewIndexParams(schema))
	prepare.Load(ctx, t, mc, hp.NewLoadParams(schema.CollectionName))

	// Test queries with boundary values
	testCases := []struct {
		expr  string
		count int
	}{
		// Test int8 boundary values
		{expr: fmt.Sprintf("%s['int8_min'] == -128", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int8_max'] == 127", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int8'][0] < 0", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int8'][0] == -128", common.DefaultJSONFieldName), count: expCount},

		// Test int16 boundary values
		{expr: fmt.Sprintf("%s['int16_min'] == -32768", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int16_max'] == 32767", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int16'][0] == -32767", common.DefaultJSONFieldName), count: expCount},

		// Test int32 boundary values
		{expr: fmt.Sprintf("%s['int32_min'] == -2147483648", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int32_max'] == 2147483647", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int32'][0] == -2147483647", common.DefaultJSONFieldName), count: expCount},

		// Test int64 boundary values
		{expr: fmt.Sprintf("%s['int64_min'] == -9223372036854775808", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['int64_max'] == 9223372036854775807", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int64'][0] == -9223372036854775808", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_int64'][1] == 9223372036854775807", common.DefaultJSONFieldName), count: expCount},

		// Test float boundary values (approximate comparison due to floating point precision)
		{expr: fmt.Sprintf("%s['float_min'] <= -3.402823e+38", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['float_max'] >= 3.402823e+38", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_float'][0] == -3.402823e+38", common.DefaultJSONFieldName), count: expCount},

		// Test double boundary values (approximate comparison due to floating point precision)
		{expr: fmt.Sprintf("%s['double_min'] <= -1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['double_max'] >= 1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_double'][0] == -1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},
		{expr: fmt.Sprintf("%s['array_double'][1] == 1.7976931348623157e+308", common.DefaultJSONFieldName), count: expCount},

		// Test regular value queries
		{expr: fmt.Sprintf("%s['val1'] == 0e+1", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val2'] == 1e22", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val3'] < 0", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val4'] == 0", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val5'] == -123", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val6'] == 123.456e78", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
		{expr: fmt.Sprintf("%s['val7'] == 123.456789", common.DefaultJSONFieldName), count: common.DefaultNb - expCount},
	}

	for _, tc := range testCases {
		t.Run(tc.expr, func(t *testing.T) {
			countRes, err := mc.Query(ctx, client.NewQueryOption(schema.CollectionName).
				WithConsistencyLevel(entity.ClStrong).
				WithFilter(tc.expr).
				WithOutputFields(common.QueryCountFieldName))
			common.CheckErr(t, err, true)
			count, _ := countRes.Fields[0].GetAsInt64(0)
			require.EqualValues(t, tc.count, count, "Query expression: %s", tc.expr)
		})
	}
}
```

![Image](https://github.com/user-attachments/assets/56713817-3e01-41e5-9f94-237ea4cee815)

**Comment by ThreadDao** [comment]
maybe same as https://github.com/milvus-io/milvus/issues/40729, only min num case failed

**Comment by ThreadDao** [comment]
fixed 2.5-20250319-2710eb3f-amd64
