### ISSUE TITLE
Must_not query check failed in dsl

### ISSUE THREAD

**Issue by fishpenguin** [milvus-io/milvus#4170]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
When using query like below: 
`{
  "bool": {
    "must": [
      {
        "must": [
          {
            "vector": {
              "embedding": {
                "metric_type": "L2", 
                "query": [
                  [
                    -0.0882435888051987, ... 0.0524853430688381
                  ]
                ], 
                "topk": 100
              }
            }
          }
        ]
      }, 
      {
        "must_not": [
          {
            "term": {
              "customer_id": [
                -2020600124
              ]
            }
          }
        ]
      }
    ]
  }
}`
Server will return error status.

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by fishpenguin** [comment]
fixed.

**Comment by tailtq** [comment]
@fishpenguin I tried the hopefully newest version which is `milvusdb/daily-build:0.11.1-centos7-gpu-20210113` and I still encountered error. This is the error message `One layer cannot include bool query and leaf query`.

This is my query.
`       {
            "bool": {
                "must": [
                    {
                        "vector": {
                            "vector": {"topk": topk, "query": vectors, "metric_type": metric_type}
                        }
                    },
                    {
                        "must_not": [
                            {
                                "term": {
                                    "uuid": new_uuids
                                }
                            }
                        ]
                    }
                ],
            },
        }`
Could you please show me the correct query? I applied the syntax in Pymilvus but couldn't show this problem. Thanks.

**Comment by tailtq** [comment]
Sorry, my syntax wasn't correct. I edited according to yours and now it is working nicely. But I highly recommend that you add this syntax to the Pymilvus and other clients. Thanks.
