### ISSUE TITLE
[Bug]: [storage-v2] After upgrading from 2.5 to 2.6, the number of segments and the row count in the query and write path are inconsistent

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#43186]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.5-20250707-e13b55fc-amd64 -> master-20250707-ab818dcb-amd64
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### server config
```
    common:
      enabledJsonKeyStats: true
      enabledOptimizeExpr: false
      storage:
        enablev2: true
    dataCoord:
      compaction:
        clustering:
          autoEnable: true
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
    log:
      level: debug
    queryCoord:
      enableActiveStandby: true
    rootCoord:
      enableActiveStandby: true
```
### client
1. create collection with schema:
```
{'auto_id': False,
 'description': '',
 'fields': [{'name': 'id', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float_vector', 'description': '', 'type': <DataType.FLOAT_VECTOR: 101>, 'params': {'dim': 128}},
            {'name': 'int32_1', 'description': '', 'type': <DataType.INT32: 4>}, {'name': 'float32_1', 'description': '', 'type': <DataType.FLOAT: 10>, 'is_clustering_key': True},
            {'name': 'varchar_1', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100}},
            {'name': 'varchar_2', 'description': '', 'type': <DataType.VARCHAR: 21>, 'params': {'max_length': 100, 'enable_match': True, 'enable_analyzer': True}},
            {'name': 'array_varchar_1', 'description': '', 'type': <DataType.ARRAY: 22>, 'params': {'max_length': 100, 'max_capacity': 10}, 'element_type': <DataType.VARCHAR: 21>},
            {'name': 'json_1', 'description': '', 'type': <DataType.JSON: 23>}, {'name': 'binary_vector', 'description': '', 'type': <DataType.BINARY_VECTOR: 100>, 'params': {'dim': 128}},
            {'name': 'float16_vector', 'description': '', 'type': <DataType.FLOAT16_VECTOR: 102>, 'params': {'dim': 128}}, {'name': 'bfloat16_vector', 'description': '', 'type': <DataType.BFLOAT16_VECTOR: 103>, 'params': {'dim': 128}}],
 'enable_dynamic_field': False} (base.py:329)
```
2. create vector and scalar index -> insert 5m -> flush -> index again -> load
3. concurrent requests: insert + delete + flush + query + search + hybrid_search
<img width="2058" height="1330" alt="Image" src="https://github.com/user-attachments/assets/93da00c2-a216-4031-b8c8-ec06f25ae805" />

### upgrading image from 2.5 -> 2.6 and enable storageV2
2.5-20250707-e13b55fc-amd64 -> master-20250707-ab818dcb-amd64

### result
1. data row count
- count(*) 
```
get_count("10.104.25.217")
collection fouram_p9BjSDJ0 count(*):
data: ["{'count(*)': 6636140}"]
```
- birdwatcher scan-binlog
<img width="2080" height="1800" alt="Image" src="https://github.com/user-attachments/assets/87469a6a-621c-4fed-9ffb-8d59eff9c4b5" />

2. segment num
- queryNode
<img width="956" height="542" alt="Image" src="https://github.com/user-attachments/assets/63c68168-bf0c-4761-8db6-c8cdb5cfec51" />
- dataCoord

<img width="936" height="520" alt="Image" src="https://github.com/user-attachments/assets/659dbf00-15b1-4182-b9c2-6c4a62fc3f3b" />

### Steps To Reproduce

```markdown

```

### Milvus Log

- argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/5d388040-68a9-431f-b91f-1e5bf7464ce9?nodeId=zong-roll-storage-base-1
- pods:
```
zong-roll-storage-base-1-milvus-datanode-dd6fd6ff8-28gds          1/1     Running       0               16h     10.104.24.232   4am-node29   <none>           <none>
zong-roll-storage-base-1-milvus-datanode-dd6fd6ff8-tvh7b          1/1     Running       0               16h     10.104.25.221   4am-node30   <none>           <none>
zong-roll-storage-base-1-milvus-mixcoord-64f67c7c9d-cjll9         1/1     Running       0               16h     10.104.24.230   4am-node29   <none>           <none>
zong-roll-storage-base-1-milvus-proxy-5b47d7c68d-2h49z            1/1     Running       0               16h     10.104.25.217   4am-node30   <none>           <none>
zong-roll-storage-base-1-milvus-querynode-1-7ff654bd5-27wzk       1/1     Running       0               16h     10.104.24.241   4am-node29   <none>           <none>
zong-roll-storage-base-1-milvus-querynode-1-7ff654bd5-2rzfw       1/1     Running       0               16h     10.104.21.119   4am-node24   <none>           <none>
zong-roll-storage-base-1-milvus-querynode-1-7ff654bd5-6vx44       1/1     Running       0               16h     10.104.6.94     4am-node13   <none>           <none>
zong-roll-storage-base-1-milvus-streamingnode-7488746f66-jqs4q    1/1     Running       0               16h     10.104.24.234   4am-node29   <none>           <none>
```

**Comment by ThreadDao** [comment]
@xiaocai2333 another issues: clustering compaction failed
[Loki logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D~%5C%22zong-roll-storage-base-1-milvus-.%2A%5C%22%7D%20%7C%3D%20%5C%22clustering_compact%5C%22%20%7C%3D%20%5C%22WARN%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221751870580395%22,%22to%22:%221751967015750%22%7D%7D%7D&schemaVersion=1&orgId=1)
```
[2025/07/07 11:17:08.092 +00:00] [WARN] [compactor/clustering_compactor.go:916] ["compact wrong, failed to iter through data"] [error="parse magic number failed, expected: 16775868, actual: 827474256"]
```

**Comment by xiaocai2333** [comment]
<img width="1823" height="1187" alt="Image" src="https://github.com/user-attachments/assets/2b1e4069-076f-4a5b-beed-218526c8f8c8" />

The clustering compaction request did not include the segment's storage version, causing the datanode to read a storage v2 segment using the storage v1 logic.

**Comment by xiaocai2333** [comment]
clustering compaction failed
```
[2025/07/07 09:48:12.846 +00:00] [WARN] [storage/remote_chunk_manager.go:207] ["failed to read object"] [path=files/part_stats/459243767018292072/459243767018292073/459243767041449853] [error="The specified key does not exist.: key not found[key=files/part_stats/459243767018292072/459243767018292073/459243767041449853]"] [errorVerbose="The specified key does not exist.: key not found[key=files/part_stats/459243767018292072/459243767018292073/459243767041449853]\n(1) attached stack trace\n  -- stack trace:\n  | github.com/milvus-io/milvus/pkg/v2/util/merr.WrapErrIoKeyNotFound\n  | \t/workspace/source/pkg/util/merr/utils.go:898\n  | github.com/milvus-io/milvus/internal/storage.checkObjectStorageError\n  | \t/workspace/source/internal/storage/remote_chunk_manager.go:424\n  | github.com/milvus-io/milvus/internal/storage.(*RemoteChunkManager).Read.func1\n  | \t/workspace/source/internal/storage/remote_chunk_manager.go:205\n  | github.com/milvus-io/milvus/pkg/v2/util/retry.Do\n  | \t/workspace/source/pkg/util/retry/retry.go:44\n  | github.com/milvus-io/milvus/internal/storage.(*RemoteChunkManager).Read\n  | \t/workspace/source/internal/storage/remote_chunk_manager.go:194\n  | github.com/milvus-io/milvus/internal/datacoord.(*clusteringCompactionTask).regeneratePartitionStats\n  | \t/workspace/source/internal/datacoord/compaction_task_clustering.go:389\n  | github.com/milvus-io/milvus/internal/datacoord.(*clusteringCompactionTask).processStats\n  | \t/workspace/source/internal/datacoord/compaction_task_clustering.go:358\n  | github.com/milvus-io/milvus/internal/datacoord.(*clusteringCompactionTask).retryableProcess\n  | \t/workspace/source/internal/datacoord/compaction_task_clustering.go:174\n  | github.com/milvus-io/milvus/internal/datacoord.(*clusteringCompactionTask).Process\n  | \t/workspace/source/internal/datacoord/compaction_task_clustering.go:94\n  | github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).checkCompaction\n  | \t/workspace/source/internal/datacoord/compaction.go:735\n  | github.com/milvus-io/milvus/internal/datacoord.(*compactionPlanHandler).loopCheck\n  | \t/workspace/source/internal/datacoord/compaction.go:447\n  | runtime.goexit\n  | \t/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.linux-amd64/src/runtime/asm_amd64.s:1700\nWraps: (2) The specified key does not exist.\nWraps: (3) key not found[key=files/part_stats/459243767018292072/459243767018292073/459243767041449853]\nError types: (1) *withstack.withStack (2) *errutil.withPrefix (3) merr.milvusError"]
```

<img width="2102" height="978" alt="Image" src="https://github.com/user-attachments/assets/d5559ffb-4776-4b73-98d4-3a44b948af7e" />

When compaction is in the `statistic` state, a recovered ClusteringCompactionTask after restart does not restore its plan member. However, the channel from the plan is still used when generating the partitionStats file, resulting in an incorrect path.
The correct behavior should be to use the channel from taskProto.

**Comment by xiaocai2333** [comment]
<img width="2201" height="1253" alt="Image" src="https://github.com/user-attachments/assets/c00efa04-d657-4e71-8bce-c051377f288d" />

<img width="1981" height="1388" alt="Image" src="https://github.com/user-attachments/assets/cdd5df1f-c7d4-4ca7-9f6b-903a7469685a" />

The persistence of `resultSegments` occurs after `regeneratePartitionStats`. If `regeneratePartitionStats` fails, the `resultSegments` are never saved, and therefore are not marked as Dropped during task cleanup. Fortunately, these segments remain invisible and will not be loaded.

**Comment by xiaocai2333** [comment]
it has been fixed. please verify it.
/assign @ThreadDao

**Comment by ThreadDao** [comment]
assign @xiaocai2333 
- image: master-20250710-07745439-amd64
- release: zong-roll-parallel-vgfdm-1

### segment info with storage v1
8-L2 + 2-L1

<img width="1314" height="304" alt="Image" src="https://github.com/user-attachments/assets/134fd0cb-d4ed-4838-b46c-30d07047f4df" />

### client operation
1. upgrade release and enable storageV2
2. call `c.compact()` and `c.compact(is_clustering=True)`

### segment info after compact and storageV2
1. Intermediate state: 8-L1-v2 + 8-L2-V1 and binlogs row-count double
<img width="1356" height="868" alt="Image" src="https://github.com/user-attachments/assets/4d0b3bcb-2981-4f3e-aae9-cfd684d320d7" />
2. final state: 6-L1-v2, binlog row-count is 2231500 (correct)
<img width="1302" height="511" alt="Image" src="https://github.com/user-attachments/assets/663f21ef-f205-4842-bf76-4223d3401836" />

There are two problems:
1. The process status is incorrect
2. Why was the L2 segments finally compacted into the L1 segments?
[metrics of zong-roll-parallel-vgfdm-1](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1752130789655&to=1752135028312&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-roll-parallel-vgfdm-1&var-collection=All&var-app_name=milvus)

**Comment by xiaocai2333** [comment]
The clustering compaction process works as follows: segments are first clustered into temporary L2 segments, which are unsorted. Then, a sort compaction is triggered to sort them. Once sorting is complete, new sorted L2 segments are generated as the final segments, and the input segments are marked as Dropped.

During the intermediate state, the number of segments in the data view may temporarily double, but they are all invisible and won't affect queries.

As for why all resulting segments end up as L1, that's because sort compaction currently marks them all as L1 by default. I will fix this.

**Comment by xiaocai2333** [comment]
has been fixed, please verify. @ThreadDao

**Comment by ThreadDao** [comment]
@xiaocai2333 I think there is still a problem that has not been fixed. After all compaction tasks are completed, dataCoord shows that there are 21 L2-segments, but why qn only loads 12 L2-segments
[metrics](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-roll-storage-a1-2&var-collection=All&var-app_name=milvus&from=1752559607008&to=1752563207008)

<img width="793" height="244" alt="Image" src="https://github.com/user-attachments/assets/bd76969b-6944-467e-bb17-65b4dfc9c052" />

<img width="809" height="253" alt="Image" src="https://github.com/user-attachments/assets/debaff75-ea17-46f5-9698-18c3e178d1c2" />
-argo: [zong-roll-storage-a1-2533859044](https://argo-workflows.zilliz.cc/archived-workflows/qa/903d97e6-d1ef-44c5-97f5-b907c498aa55?nodeId=zong-roll-storage-a1-2533859044)

**Comment by xiaocai2333** [comment]
It seems the indexing failed, causing it to get stuck in the indexing stage. Since the compaction hasn't finished yet, the intermediate segments won't be cleaned up.
```
W20250715 07:03:35.498450   125 ivf.cc:475] [KNOWHERE][Train][milvus] faiss internal error: faiss::FaissException: Error in void faiss::Clustering::train_encoded(faiss::idx_t, const uint8_t*, const faiss::Index*, faiss::Index&, const float*) at /workspace/source/cmake_build/thirdparty/knowhere/knowhere-src/thirdparty/faiss/faiss/Clustering.cpp:435: Error: '!(std::isfinite(x[i]))' failed: input contains NaN's or Inf's
I20250715 07:03:35.509506   125 time_recorder.cc:49] [KNOWHERE][PrintTimeRecord][milvus] Build index: done (130.251830 ms)
 => failed to build index, faiss inner error at /workspace/source/internal/core/src/index/VectorMemIndex.cpp:299
[2025/07/15 07:03:35.516 +00:00] [WARN] [indexcgowrapper/helper.go:73] ["failed to create index, C Runtime Exception:  => failed to build index, faiss inner error at /workspace/source/internal/core/src/index/VectorMemIndex.cpp:299\n\n"]
```

**Comment by shaoting-huang** [comment]
checked binlog it does write NaN into float vector. Need to diagnose write path, include sync, compaction, and sort.

**Comment by tedxu** [comment]
According to offline discussion, the reproduction is blocked by #43293 .

**Comment by ThreadDao** [comment]
@tedxu @xiaocai2333 
### tests
1. The release `zong-sn-base-op-99-3795` has some storage-v1 L2 segments
2. upgrading image to `master-20250723-d64dceea-amd64`
3. call `compact(is_clustering=True)`
### results
[metrics of zong-sn-base-op-99-3795](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1753260210596&to=1753263248632&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-sn-base-op-99-3795&var-collection=All&var-app_name=milvus)
- Why are only part L2-segments clustering-compaction to storage-v2?
- queryNode loaded 70 L2-segments while dataCoord has 104 L2-segments
<img width="823" height="283" alt="Image" src="https://github.com/user-attachments/assets/d6ef2cfc-8cdb-4445-941b-b8b11ee6bc32" />
<img width="822" height="334" alt="Image" src="https://github.com/user-attachments/assets/e1b97f37-6ac3-4c7e-95c4-632216c2d84e" />
3. dataNode oom
<img width="2467" height="1231" alt="Image" src="https://github.com/user-attachments/assets/4e3f2c36-2980-4d47-b0fc-f8303ea5cdcc" />

```
zong-sn-base-op-99-3795-milvus-datanode-7d8fb975c7-vdh8h          1/1     Running     1 (172m ago)    3h3m    10.104.15.85    4am-node20   <none>           <none>
zong-sn-base-op-99-3795-milvus-datanode-7d8fb975c7-vdl5m          1/1     Running     1 (171m ago)    3h4m    10.104.9.48     4am-node14   <none>           <none>
zong-sn-base-op-99-3795-milvus-mixcoord-c9cc674d8-svf7j           1/1     Running     0               3h15m   10.104.9.45     4am-node14   <none>           <none>
zong-sn-base-op-99-3795-milvus-proxy-67c7ff7c5c-rlrpp             1/1     Running     0               3h2m    10.104.6.7      4am-node13   <none>           <none>
zong-sn-base-op-99-3795-milvus-querynode-0-d95f44f84-lkcj2        1/1     Running     0               3h12m   10.104.15.78    4am-node20   <none>           <none>
zong-sn-base-op-99-3795-milvus-querynode-0-d95f44f84-pvfz9        1/1     Running     0               3h5m    10.104.23.111   4am-node27   <none>           <none>
zong-sn-base-op-99-3795-milvus-querynode-0-d95f44f84-sccr6        1/1     Running     0               3h9m    10.104.9.46     4am-node14   <none>           <none>
zong-sn-base-op-99-3795-milvus-querynode-0-d95f44f84-zztcg        1/1     Running     0               3h11m   10.104.27.189   4am-node31   <none>           <none>
zong-sn-base-op-99-3795-milvus-streamingnode-58bb84579f-kkrxx     1/1     Running     0               3h14m   10.104.34.197   4am-node37   <none>           <none>
zong-sn-base-op-99-3795-milvus-streamingnode-58bb84579f-zktxg     1/1     Running     0               3h13m   10.104.30.226   4am-node38   <none>           <none>
```

**Comment by ThreadDao** [comment]
fixed `master-20250728-64899418-amd64`
[etrics of zong-sn-base-op-43-1125](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1753685316777&to=1753688347319&var-datasource=P1809F7CD0C75ACF3&var-namespace=qa-milvus&var-instance=zong-sn-base-op-43-1125&var-collection=All&var-app_name=milvus)
- L2 segments with storage_v1 -> enable storage_v2 -> compact(is_clustering=True)
The new storage-v2 L2 segments successfully completed the indexing and other tasks and was handoff on the querynode. However, the problem of high dataNode memory usage is still being tracked in other issues.
<img width="819" height="539" alt="Image" src="https://github.com/user-attachments/assets/28be0074-b937-4bd1-99c8-206d50d2a19f" />

<img width="2486" height="1165" alt="Image" src="https://github.com/user-attachments/assets/4c45b2fd-5562-4559-a049-b3d8e456d492" />
