### ISSUE TITLE
[Bug]: After Milvus recovers from many chaos tests, a large number of timeout failures in search/full text search/hybrid search still occur

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#43573]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:milvus-io-master-5cebc9f-20250725
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2025-07-25T11:29:07.606Z] [2025-07-25 11:27:00 - ERROR - ci_test]: Traceback (most recent call last):

[2025-07-25T11:29:07.606Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2025-07-25T11:29:07.606Z]     res = func(*args, **_kwargs)

[2025-07-25T11:29:07.606Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 53, in api_request

[2025-07-25T11:29:07.606Z]     return func(*arg, **kwargs)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 803, in search

[2025-07-25T11:29:07.606Z]     resp = conn.search(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 155, in handler

[2025-07-25T11:29:07.606Z]     raise e from e

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler

[2025-07-25T11:29:07.606Z]     return func(*args, **kwargs)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 173, in handler

[2025-07-25T11:29:07.606Z]     return func(self, *args, **kwargs)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 90, in handler

[2025-07-25T11:29:07.606Z]     raise e from e

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 86, in handler

[2025-07-25T11:29:07.606Z]     return func(*args, **kwargs)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 970, in search

[2025-07-25T11:29:07.606Z]     return self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 905, in _execute_search

[2025-07-25T11:29:07.606Z]     raise e from e

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py", line 893, in _execute_search

[2025-07-25T11:29:07.606Z]     response = self._stub.Search(request, timeout=timeout, metadata=_api_level_md(**kwargs))

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 277, in __call__

[2025-07-25T11:29:07.606Z]     response, ignored_call = self._with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2025-07-25T11:29:07.606Z]     return call.result(), call

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 440, in result

[2025-07-25T11:29:07.606Z]     raise self

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2025-07-25T11:29:07.606Z]     response, call = self._thunk(new_method).with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 343, in with_call

[2025-07-25T11:29:07.606Z]     return self._with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2025-07-25T11:29:07.606Z]     return call.result(), call

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 440, in result

[2025-07-25T11:29:07.606Z]     raise self

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2025-07-25T11:29:07.606Z]     response, call = self._thunk(new_method).with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 343, in with_call

[2025-07-25T11:29:07.606Z]     return self._with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 332, in _with_call

[2025-07-25T11:29:07.606Z]     return call.result(), call

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 440, in result

[2025-07-25T11:29:07.606Z]     raise self

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_interceptor.py", line 315, in continuation

[2025-07-25T11:29:07.606Z]     response, call = self._thunk(new_method).with_call(

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1198, in with_call

[2025-07-25T11:29:07.606Z]     return _end_unary_response_blocking(state, call, True, None)

[2025-07-25T11:29:07.606Z]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking

[2025-07-25T11:29:07.606Z]     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable

[2025-07-25T11:29:07.606Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

[2025-07-25T11:29:07.606Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2025-07-25T11:29:07.606Z] 	details = "Deadline Exceeded"

[2025-07-25T11:29:07.606Z] 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Deadline Exceeded", grpc_status:4, created_time:"2025-07-25T11:27:00.193549586+00:00"}"

[2025-07-25T11:29:07.606Z] >

[2025-07-25T11:29:07.606Z]  (api_request.py:35)

[2025-07-25T11:29:07.606Z] [2025-07-25 11:27:00 - ERROR - ci_test]: (api_response) : <_InactiveRpcError of RPC that terminated with:

[2025-07-25T11:29:07.606Z] 	status = StatusCode.DEADLINE_EXCEEDED

[2025-07-25T11:29:07.606Z] 	details = "Deadline Exceeded"

[2025-07-25T11:29:07.606Z] 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Deadline Exceeded", grpc_status:4, created_time:"2025-07-25T11:27:00.193549586+00:00"}"

[2025-07-25T11:29:07.606Z] > (api_request.py:36)
```

For the chaos related to the etcd follower, it does not cause any Milvus components to restart. However, issues still occurred, so this problem is unrelated to chaos and is likely related to request load.

### Steps To Reproduce

```markdown

```

### Milvus Log

failed job： https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21914/pipeline
log: 

[artifacts-etcd-followers-pod-failure-21914-server-logs.tar.gz](https://github.com/user-attachments/files/21433416/artifacts-etcd-followers-pod-failure-21914-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing
pods
```
19:29:16  + kubectl get pods -o wide
19:29:16  + grep etcd-followers-pod-failure-21914
19:29:16  etcd-followers-pod-failure-21914-0                                1/1     Running            0                 68m     10.104.24.43    4am-node29   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-1                                1/1     Running            2 (46m ago)       68m     10.104.23.202   4am-node27   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-2                                1/1     Running            0                 68m     10.104.25.115   4am-node30   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-datanode-57b7b5b85fsz66   1/1     Running            2 (67m ago)       68m     10.104.18.111   4am-node25   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-datanode-57b7b5b85s2s4p   1/1     Running            2 (67m ago)       68m     10.104.23.200   4am-node27   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-mixcoord-7cc64cf84rbgx8   1/1     Running            2 (67m ago)       68m     10.104.18.114   4am-node25   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-proxy-6b9c7476b-qbncz     1/1     Running            2 (67m ago)       68m     10.104.18.112   4am-node25   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-querynode-7b4b5f7788kv9   1/1     Running            2 (67m ago)       68m     10.104.15.110   4am-node20   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-querynode-7b4b5f77gmjzt   1/1     Running            2 (67m ago)       68m     10.104.18.113   4am-node25   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-querynode-7b4b5f77rkd4q   1/1     Running            2 (67m ago)       68m     10.104.34.41    4am-node37   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-streamingnode-7b786t4rz   1/1     Running            2 (67m ago)       68m     10.104.15.114   4am-node20   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-milvus-streamingnode-7b78tlxj6   1/1     Running            2 (67m ago)       68m     10.104.30.47    4am-node38   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-minio-0                          1/1     Running            0                 68m     10.104.18.116   4am-node25   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-minio-1                          1/1     Running            0                 68m     10.104.32.180   4am-node39   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-minio-2                          1/1     Running            0                 68m     10.104.17.232   4am-node23   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-minio-3                          1/1     Running            0                 68m     10.104.19.242   4am-node28   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-bookie-0                1/1     Running            0                 68m     10.104.25.117   4am-node30   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-bookie-1                1/1     Running            0                 68m     10.104.20.193   4am-node22   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-bookie-2                1/1     Running            0                 68m     10.104.24.47    4am-node29   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-bookie-init-zr4sz       0/1     Completed          0                 68m     10.104.25.109   4am-node30   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-broker-0                1/1     Running            0                 68m     10.104.14.32    4am-node18   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-broker-1                1/1     Running            0                 68m     10.104.24.41    4am-node29   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-proxy-0                 1/1     Running            0                 68m     10.104.25.110   4am-node30   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-proxy-1                 1/1     Running            0                 68m     10.104.6.76     4am-node13   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-pulsar-init-lbvkj       0/1     Completed          0                 68m     10.104.15.113   4am-node20   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-recovery-0              1/1     Running            0                 68m     10.104.14.33    4am-node18   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-zookeeper-0             1/1     Running            0                 68m     10.104.20.190   4am-node22   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-zookeeper-1             1/1     Running            0                 68m     10.104.24.44    4am-node29   <none>           <none>
19:29:16  etcd-followers-pod-failure-21914-pulsarv3-zookeeper-2             1/1     Running            0                 68m     10.104.25.116   4am-node30   <none>           <none>
```

**Comment by weiliu1031** [comment]
<img width="5098" height="1244" alt="Image" src="https://github.com/user-attachments/assets/347c1b1a-d1fe-40fd-9fa5-b7f4ceb362d3" />

query failed due to `failed to wait tSafe`,  same as #43431, please take a look @tinswzy

**Comment by weiliu1031** [comment]
same as #43592, delete. cgo call latency call tsafe latency, then query failed due to `failed to wait tSafe`

**Comment by tedxu** [comment]
@weiliu1031 shall we mark this one duplicated?

**Comment by weiliu1031** [comment]
> [@weiliu1031](https://github.com/weiliu1031) shall we mark this one duplicated?

yes, different behavior of same problem

**Comment by weiliu1031** [comment]
should be fixed by https://github.com/milvus-io/milvus/pull/43640

please verify this with latest image

**Comment by zhuwenxing** [comment]
still reproduced in etcd-leader chaos test with `master-20250731-708e426b-amd64`

<img width="4692" height="1408" alt="Image" src="https://github.com/user-attachments/assets/023ebc01-5bff-469e-b34c-3d7d2c6a54a8" />

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21969/pipeline
log: 

[artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz](https://github.com/user-attachments/files/21526208/artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz)


cluster: 4am
ns: chaos-testing
pods
```
[2025-07-31T08:26:14.612Z] + grep etcd-leader-pod-failure-21969
[2025-07-31T08:26:14.613Z] + kubectl get pods -o wide
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-0                                   1/1     Running       2 (45m ago)     68m     10.104.26.252   4am-node32   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-1                                   1/1     Running       0               68m     10.104.24.64    4am-node29   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-2                                   1/1     Running       0               68m     10.104.30.64    4am-node38   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-cf2sl    1/1     Running       4 (67m ago)     68m     10.104.20.137   4am-node22   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-s2xk8    1/1     Running       4 (67m ago)     68m     10.104.15.129   4am-node20   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-mixcoord-66c9cc888f-vtzhp    1/1     Running       4 (67m ago)     68m     10.104.17.125   4am-node23   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-proxy-c565d8cbc-r9nd4        1/1     Running       4 (66m ago)     68m     10.104.33.136   4am-node36   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-lbflv    1/1     Running       4 (67m ago)     68m     10.104.27.226   4am-node31   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-svhzn    1/1     Running       4 (67m ago)     68m     10.104.13.102   4am-node16   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-xwzkr    1/1     Running       4 (66m ago)     68m     10.104.22.33    4am-node26   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645b4pmwf   1/1     Running       4 (66m ago)     68m     10.104.6.246    4am-node13   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645bbqc56   1/1     Running       4 (66m ago)     68m     10.104.23.226   4am-node27   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-0                             1/1     Running       0               68m     10.104.34.181   4am-node37   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-1                             1/1     Running       0               68m     10.104.17.142   4am-node23   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-2                             1/1     Running       0               68m     10.104.26.254   4am-node32   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-3                             1/1     Running       0               68m     10.104.23.235   4am-node27   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-0                   1/1     Running       0               68m     10.104.26.253   4am-node32   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-1                   1/1     Running       0               68m     10.104.25.17    4am-node30   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-2                   1/1     Running       0               68m     10.104.24.67    4am-node29   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-init-5j9g6          0/1     Completed     0               68m     10.104.33.137   4am-node36   <none>           <none>
[2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-broker-0                   1/1     Running       0               68m     10.104.34.171   4am-node37   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-broker-1                   1/1     Running       0               68m     10.104.15.131   4am-node20   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-0                    1/1     Running       0               68m     10.104.17.127   4am-node23   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-1                    1/1     Running       0               68m     10.104.26.240   4am-node32   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-pulsar-init-44xsm          0/1     Completed     0               68m     10.104.17.126   4am-node23   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-recovery-0                 1/1     Running       0               68m     10.104.14.219   4am-node18   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-0                1/1     Running       0               68m     10.104.34.179   4am-node37   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-1                1/1     Running       0               68m     10.104.30.62    4am-node38   <none>           <none>
[2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-2                1/1     Running       0               68m     10.104.24.63    4am-node29   <none>           <none>
```

**Comment by zhuwenxing** [comment]
/unassign 
/assign @weiliu1031 
PTAL

**Comment by weiliu1031** [comment]
> still reproduced in etcd-leader chaos test with `master-20250731-708e426b-amd64`
> 
> <img alt="Image" width="2000" height="1408" src="https://private-user-images.githubusercontent.com/12268675/472891022-023ebc01-5bff-469e-b34c-3d7d2c6a54a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwMTU1NjcsIm5iZiI6MTc1NDAxNTI2NywicGF0aCI6Ii8xMjI2ODY3NS80NzI4OTEwMjItMDIzZWJjMDEtNWJmZi00NjllLWIzNGMtM2Q3ZDJjNmE1NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDAyMjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmM2MWJmNmEyM2JmYzkwMmQ4ZTk2MzFmNWFlNDIxMWZmMmY3NGM5ZjY1ZTQ3YWE1OTYzYWFiZDA2OTRkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6PNteE9fhjpgTDC8wLmUi8vtYQ_Jzw_kgfsMcLsXi8w">
> failed job: [qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21969/pipeline](https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21969/pipeline) log:
> 
> [artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz](https://github.com/user-attachments/files/21526208/artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz)
> 
> cluster: 4am ns: chaos-testing pods
> 
> ```
> [2025-07-31T08:26:14.612Z] + grep etcd-leader-pod-failure-21969
> [2025-07-31T08:26:14.613Z] + kubectl get pods -o wide
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-0                                   1/1     Running       2 (45m ago)     68m     10.104.26.252   4am-node32   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-1                                   1/1     Running       0               68m     10.104.24.64    4am-node29   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-2                                   1/1     Running       0               68m     10.104.30.64    4am-node38   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-cf2sl    1/1     Running       4 (67m ago)     68m     10.104.20.137   4am-node22   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-s2xk8    1/1     Running       4 (67m ago)     68m     10.104.15.129   4am-node20   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-mixcoord-66c9cc888f-vtzhp    1/1     Running       4 (67m ago)     68m     10.104.17.125   4am-node23   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-proxy-c565d8cbc-r9nd4        1/1     Running       4 (66m ago)     68m     10.104.33.136   4am-node36   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-lbflv    1/1     Running       4 (67m ago)     68m     10.104.27.226   4am-node31   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-svhzn    1/1     Running       4 (67m ago)     68m     10.104.13.102   4am-node16   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-xwzkr    1/1     Running       4 (66m ago)     68m     10.104.22.33    4am-node26   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645b4pmwf   1/1     Running       4 (66m ago)     68m     10.104.6.246    4am-node13   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645bbqc56   1/1     Running       4 (66m ago)     68m     10.104.23.226   4am-node27   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-0                             1/1     Running       0               68m     10.104.34.181   4am-node37   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-1                             1/1     Running       0               68m     10.104.17.142   4am-node23   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-2                             1/1     Running       0               68m     10.104.26.254   4am-node32   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-3                             1/1     Running       0               68m     10.104.23.235   4am-node27   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-0                   1/1     Running       0               68m     10.104.26.253   4am-node32   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-1                   1/1     Running       0               68m     10.104.25.17    4am-node30   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-2                   1/1     Running       0               68m     10.104.24.67    4am-node29   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-init-5j9g6          0/1     Completed     0               68m     10.104.33.137   4am-node36   <none>           <none>
> [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-broker-0                   1/1     Running       0               68m     10.104.34.171   4am-node37   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-broker-1                   1/1     Running       0               68m     10.104.15.131   4am-node20   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-0                    1/1     Running       0               68m     10.104.17.127   4am-node23   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-1                    1/1     Running       0               68m     10.104.26.240   4am-node32   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-pulsar-init-44xsm          0/1     Completed     0               68m     10.104.17.126   4am-node23   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-recovery-0                 1/1     Running       0               68m     10.104.14.219   4am-node18   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-0                1/1     Running       0               68m     10.104.34.179   4am-node37   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-1                1/1     Running       0               68m     10.104.30.62    4am-node38   <none>           <none>
> [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-2                1/1     Running       0               68m     10.104.24.63    4am-node29   <none>           <none>
> ```

new issue found, insert cgo call stuck for more than 15s, which cause query failed to wait tSafe, the insert cgo call issue is still in investigating

<img width="1706" height="468" alt="Image" src="https://github.com/user-attachments/assets/df3b36b0-8e01-475a-bf82-a480a0e30e81" />

**Comment by weiliu1031** [comment]
> > still reproduced in etcd-leader chaos test with `master-20250731-708e426b-amd64`
> > <img alt="Image" width="2000" height="1408" src="https://private-user-images.githubusercontent.com/12268675/472891022-023ebc01-5bff-469e-b34c-3d7d2c6a54a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQwMTU1NjcsIm5iZiI6MTc1NDAxNTI2NywicGF0aCI6Ii8xMjI2ODY3NS80NzI4OTEwMjItMDIzZWJjMDEtNWJmZi00NjllLWIzNGMtM2Q3ZDJjNmE1NGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODAxVDAyMjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MmM2MWJmNmEyM2JmYzkwMmQ4ZTk2MzFmNWFlNDIxMWZmMmY3NGM5ZjY1ZTQ3YWE1OTYzYWFiZDA2OTRkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6PNteE9fhjpgTDC8wLmUi8vtYQ_Jzw_kgfsMcLsXi8w">
> > failed job: [qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21969/pipeline](https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21969/pipeline) log:
> > [artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz](https://github.com/user-attachments/files/21526208/artifacts-etcd-leader-pod-failure-21969-server-logs.tar.gz)
> > cluster: 4am ns: chaos-testing pods
> > ```
> > [2025-07-31T08:26:14.612Z] + grep etcd-leader-pod-failure-21969
> > [2025-07-31T08:26:14.613Z] + kubectl get pods -o wide
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-0                                   1/1     Running       2 (45m ago)     68m     10.104.26.252   4am-node32   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-1                                   1/1     Running       0               68m     10.104.24.64    4am-node29   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-2                                   1/1     Running       0               68m     10.104.30.64    4am-node38   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-cf2sl    1/1     Running       4 (67m ago)     68m     10.104.20.137   4am-node22   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-datanode-6996486888-s2xk8    1/1     Running       4 (67m ago)     68m     10.104.15.129   4am-node20   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-mixcoord-66c9cc888f-vtzhp    1/1     Running       4 (67m ago)     68m     10.104.17.125   4am-node23   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-proxy-c565d8cbc-r9nd4        1/1     Running       4 (66m ago)     68m     10.104.33.136   4am-node36   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-lbflv    1/1     Running       4 (67m ago)     68m     10.104.27.226   4am-node31   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-svhzn    1/1     Running       4 (67m ago)     68m     10.104.13.102   4am-node16   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-querynode-dfdb4dd59-xwzkr    1/1     Running       4 (66m ago)     68m     10.104.22.33    4am-node26   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645b4pmwf   1/1     Running       4 (66m ago)     68m     10.104.6.246    4am-node13   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-milvus-streamingnode-6b9645bbqc56   1/1     Running       4 (66m ago)     68m     10.104.23.226   4am-node27   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-0                             1/1     Running       0               68m     10.104.34.181   4am-node37   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-1                             1/1     Running       0               68m     10.104.17.142   4am-node23   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-2                             1/1     Running       0               68m     10.104.26.254   4am-node32   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-minio-3                             1/1     Running       0               68m     10.104.23.235   4am-node27   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-0                   1/1     Running       0               68m     10.104.26.253   4am-node32   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-1                   1/1     Running       0               68m     10.104.25.17    4am-node30   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-2                   1/1     Running       0               68m     10.104.24.67    4am-node29   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-bookie-init-5j9g6          0/1     Completed     0               68m     10.104.33.137   4am-node36   <none>           <none>
> > [2025-07-31T08:26:14.613Z] etcd-leader-pod-failure-21969-pulsarv3-broker-0                   1/1     Running       0               68m     10.104.34.171   4am-node37   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-broker-1                   1/1     Running       0               68m     10.104.15.131   4am-node20   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-0                    1/1     Running       0               68m     10.104.17.127   4am-node23   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-proxy-1                    1/1     Running       0               68m     10.104.26.240   4am-node32   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-pulsar-init-44xsm          0/1     Completed     0               68m     10.104.17.126   4am-node23   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-recovery-0                 1/1     Running       0               68m     10.104.14.219   4am-node18   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-0                1/1     Running       0               68m     10.104.34.179   4am-node37   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-1                1/1     Running       0               68m     10.104.30.62    4am-node38   <none>           <none>
> > [2025-07-31T08:26:14.614Z] etcd-leader-pod-failure-21969-pulsarv3-zookeeper-2                1/1     Running       0               68m     10.104.24.63    4am-node29   <none>           <none>
> > ```
> 
> new issue found, insert cgo call stuck for more than 15s, which cause query failed to wait tSafe, the insert cgo call issue is still in investigating
> 
> <img alt="Image" width="1706" height="468" src="https://private-user-images.githubusercontent.com/108661493/473258487-df3b36b0-8e01-475a-bf82-a480a0e30e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQyODkyMTEsIm5iZiI6MTc1NDI4ODkxMSwicGF0aCI6Ii8xMDg2NjE0OTMvNDczMjU4NDg3LWRmM2IzNmIwLThlMDEtNDc1YS1iZjgyLWE0ODBhMGUzMGU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwNFQwNjI4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWVkYjdkYzlhODJkMWZiYzQxNmVkNmNiMDUxODZkMmJhMTBiNzFiZTBmMTA0NGQ2ZDkwNmU1NzE0MTUxNWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g10dbeglTnbwR9Y-sR_jDxIio0cxg-N2A-RXjGdmBpI">

Please re-trigger this test for verification. Our investigation found that during the time of the failure, all monitoring metrics for the physical machine where the stream node was located were missing, suggesting a potential issue with the physical machine itself. /cc @zhuwenxing 

![Image](https://github.com/user-attachments/assets/e3e8f023-0f82-419f-a4e9-590d623158bf)

**Comment by zhuwenxing** [comment]
verified and fixed in `master-20250807-c297a003-amd64`
