### ISSUE TITLE
[Bug]: Load still timeout(180s) when Milvus recovered from querynode pod failure chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#43592]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250725-d23205b7-amd64
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[-0.05070855376196274, -0.1419267744695419, -0.05344790287181644, 0.13098817533890988, -0.012415264375338304, 0.015213501444577863, -0.12410524879383658, 0.026834349092479084, 0.08812804972274499, 0.14713071956128898, -0.01097350670763702, -0.07668002928348125, -0.15039018663361933, 0.003258089992......, kwargs: {} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 1753444164441285, 'distance': 1.298689365386963, 'entity': {}}]]  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - INFO - ci_test]: assert search: 0.019837379455566406 (test_all_collections_after_chaos.py:104)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [['Within cover easy for participant control. Congress relationship space somebody lead. Many size administration base.'], 'text_sparse_emb', {'metric_type': 'BM25', 'params': {}}, 1, None, None, None, 180, -1], kwargs: {} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 1753444010877816, 'distance': 17.20558738708496, 'entity': {}}]]  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - INFO - ci_test]: assert full text search: 0.011144161224365234 (test_all_collections_after_chaos.py:116)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:03:59 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:00 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2999}", "{'int64': -2998}", "{'int64': -2997}", "{'int64': -2996}", "{'int64': -2995}", "{'int64': -2994}", "{'int64': -2993}", "{'int64': -2992}", "{'int64': -2991}"] ..., extra_info: {}  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:00 - INFO - ci_test]: assert query result 2000: 1.5359721183776855 (test_all_collections_after_chaos.py:124)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:00 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["text_match(document, 'Civil agency movement our chance everybody. Clear every too career firm reality suffer beat. Evening money paper long stop. Family both civil hold word line. Course drive but huge friend.')", None, None, 180], kwargs: {} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:00 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2996}", "{'int64': -2991}", "{'int64': -2988}", "{'int64': -2987}", "{'int64': -2986}", "{'int64': -2982}", "{'int64': -2981}", "{'int64': -2980}", "{'int64': -2979}"] ..., extra_info: {}  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:00 - INFO - ci_test]: assert text match: 0.13755512237548828 (test_all_collections_after_chaos.py:135)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:05 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': 0, 'float': 0.15379593, 'varchar': 'szrzsmppcyd', 'document': None, 'text': 'Another keep key. Game power those. Nor late spring him.\nPerform high response ground impact range particularly.', 'json_field': {'name': 'Ann Smith', 'address': '03028 Meghan Well Apt. 581\nLauraside, WI 98056......, kwargs: {'timeout': 180} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:06 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 459655098269696009, success count: 2000, err count: 0  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:06 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:07 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:04:07 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:07:07 - ERROR - ci_test]: Traceback (most recent call last):

[2025-07-25T12:12:33.922Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2025-07-25T12:12:33.922Z]     res = func(*args, **_kwargs)

[2025-07-25T12:12:33.922Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 53, in api_request

[2025-07-25T12:12:33.922Z]     return func(*arg, **kwargs)

[2025-07-25T12:12:33.922Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 429, in load

[2025-07-25T12:12:33.922Z]     conn.load_collection(

[2025-07-25T12:12:33.922Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler

[2025-07-25T12:12:33.922Z]     raise e from e

[2025-07-25T12:12:33.922Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler

[2025-07-25T12:12:33.922Z]     return func(*args, **kwargs)

[2025-07-25T12:12:33.922Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 173, in handler

[2025-07-25T12:12:33.922Z]     return func(self, *args, **kwargs)

[2025-07-25T12:12:33.922Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 107, in handler

[2025-07-25T12:12:33.922Z]     raise MilvusException(

[2025-07-25T12:12:33.922Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__tXYr8XEw)>

[2025-07-25T12:12:33.922Z]  (api_request.py:35)

[2025-07-25T12:12:33.922Z] [2025-07-25 12:07:07 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__tXYr8XEw)> (api_request.py:36)
```

load --> search --> release --> load (timeout in this step)

### Expected Behavior

load sucess

### Steps To Reproduce

```markdown

```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-kafka-cron/detail/chaos-test-kafka-cron/20421/pipeline
log：  [artifacts-querynode-pod-failure-20421-server-logs.tar.gz](https://github.com/user-attachments/files/21459185/artifacts-querynode-pod-failure-20421-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing
pods
```
querynode-pod-failure-20421-etcd-0                                1/1     Running            0               76m     10.104.17.30    4am-node23   <none>           <none>
 querynode-pod-failure-20421-etcd-1                                1/1     Running            0               76m     10.104.32.216   4am-node39   <none>           <none>
 querynode-pod-failure-20421-etcd-2                                1/1     Running            0               76m     10.104.30.67    4am-node38   <none>           <none>
 querynode-pod-failure-20421-kafka-0                               2/2     Running            2 (75m ago)     76m     10.104.17.29    4am-node23   <none>           <none>
 querynode-pod-failure-20421-kafka-1                               2/2     Running            2 (75m ago)     76m     10.104.32.217   4am-node39   <none>           <none>
 querynode-pod-failure-20421-kafka-2                               2/2     Running            2 (75m ago)     76m     10.104.34.91    4am-node37   <none>           <none>
 querynode-pod-failure-20421-kafka-exporter-cdffdbfc9-hms7m        1/1     Running            5 (75m ago)     76m     10.104.13.8     4am-node16   <none>           <none>
 querynode-pod-failure-20421-milvus-datanode-844745667b-7jvjv      1/1     Running            2 (76m ago)     76m     10.104.33.98    4am-node36   <none>           <none>
 querynode-pod-failure-20421-milvus-datanode-844745667b-kvwz6      1/1     Running            2 (76m ago)     76m     10.104.19.253   4am-node28   <none>           <none>
 querynode-pod-failure-20421-milvus-mixcoord-9f696657-8mk96        1/1     Running            2 (76m ago)     76m     10.104.27.234   4am-node31   <none>           <none>
 querynode-pod-failure-20421-milvus-proxy-65b84c879f-qr8hz         1/1     Running            2 (76m ago)     76m     10.104.27.233   4am-node31   <none>           <none>
 querynode-pod-failure-20421-milvus-querynode-5456b555f-c7hkz      1/1     Running            5 (47m ago)     76m     10.104.21.92    4am-node24   <none>           <none>
 querynode-pod-failure-20421-milvus-querynode-5456b555f-p5gtf      1/1     Running            5 (47m ago)     76m     10.104.27.235   4am-node31   <none>           <none>
 querynode-pod-failure-20421-milvus-querynode-5456b555f-wzljw      1/1     Running            5 (47m ago)     76m     10.104.23.217   4am-node27   <none>           <none>
 querynode-pod-failure-20421-milvus-streamingnode-854c77fdckscsb   1/1     Running            2 (76m ago)     76m     10.104.6.104    4am-node13   <none>           <none>
 querynode-pod-failure-20421-milvus-streamingnode-854c77fdcr267f   1/1     Running            2 (76m ago)     76m     10.104.24.72    4am-node29   <none>           <none>
 querynode-pod-failure-20421-minio-0                               1/1     Running            0               76m     10.104.26.86    4am-node32   <none>           <none>
 querynode-pod-failure-20421-minio-1                               1/1     Running            0               76m     10.104.16.158   4am-node21   <none>           <none>
 querynode-pod-failure-20421-minio-2                               1/1     Running            0               76m     10.104.32.218   4am-node39   <none>           <none>
 querynode-pod-failure-20421-minio-3                               1/1     Running            0               76m     10.104.17.33    4am-node23   <none>           <none>
 querynode-pod-failure-20421-zookeeper-0                           1/1     Running            0               76m     10.104.32.212   4am-node39   <none>           <none>
 querynode-pod-failure-20421-zookeeper-1                           1/1     Running            0               76m     10.104.17.32    4am-node23   <none>           <none>
 querynode-pod-failure-20421-zookeeper-2                           1/1     Running            0               76m     10.104.24.74    4am-node29   <none>           <none>
```

### Anything else?

This issue also reproduced in some other components  chaos test

**Comment by weiliu1031** [comment]
<img width="4978" height="712" alt="Image" src="https://github.com/user-attachments/assets/6036e587-86c0-4dc2-9334-2cdf9095543b" />

<img width="4304" height="1152" alt="Image" src="https://github.com/user-attachments/assets/21727f2f-c536-4ead-9c19-4539c5321eb6" />

1. load segment is too slow, because apply delete cause more than 30s
2. apply delete stuck at cgo func call, which stuck for more than 30s

**Comment by weiliu1031** [comment]
should be fixed by https://github.com/milvus-io/milvus/pull/43640

please verify this with latest image

**Comment by zhuwenxing** [comment]
still reproduced in pulsar pod failure chaos test  with `master-20250731-708e426b-amd64`

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21965/pipeline
log: 

[artifacts-pulsar-pod-failure-21965-server-logs.tar.gz](https://github.com/user-attachments/files/21525518/artifacts-pulsar-pod-failure-21965-server-logs.tar.gz)

```
[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[-0.019305144567644355, 0.13534748232492966, 0.11781800861779226, -0.13332264235381044, -0.06931295771854956, 0.0907605343064362, -0.03463697085606006, 0.05015528101180931, -0.10769676260834375, 0.12995878152521737, 0.13536880665986123, 0.08940299953233173, -0.1257463634372558, 0.12210886895467592......, kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 1753944440120805, 'distance': 1.3167352676391602, 'entity': {}}]]  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert search: 0.47228097915649414 (test_all_collections_after_chaos.py:104)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [['Once door job only if. Writer PM reflect avoid memory.\nStandard bag stuff. Meet animal fly news movie marriage strategy measure. Believe window be then apply.\nStep front series vote threat just.'], 'text_sparse_emb', {'metric_type': 'BM25', 'params': {}}, 1, None, None, None, 180, -1], kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 175394571327933, 'distance': 21.254215240478516, 'entity': {}}]]  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert full text search: 0.10006237030029297 (test_all_collections_after_chaos.py:116)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2999}", "{'int64': -2998}", "{'int64': -2997}", "{'int64': -2996}", "{'int64': -2995}", "{'int64': -2994}", "{'int64': -2993}", "{'int64': -2992}", "{'int64': -2991}"] ..., extra_info: {}  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert query result 2000: 0.8938496112823486 (test_all_collections_after_chaos.py:124)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["text_match(document, 'Success bit respond themselves he. Value yet sound decision. Want yes its Mr. Indeed necessary bag effort door word. Father area interesting eye bit. Any drive market now.')", None, None, 180], kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -2999}", "{'int64': -2995}", "{'int64': -2992}", "{'int64': -2991}", "{'int64': -2988}", "{'int64': -2987}", "{'int64': -2986}", "{'int64': -2984}", "{'int64': -2983}", "{'int64': -2980}"] ..., extra_info: {}  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert text match: 0.0317082405090332 (test_all_collections_after_chaos.py:135)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': 0, 'float': 0.31371024, 'varchar': 'evsbfnkgg', 'document': 'They public senior space local increase. Behavior eight through travel.\nAir policy world number cup light marriage. Great black stuff nearly relationship mean.', 'text': 'Rise happy whatever because treatment. Author whose pra......, kwargs: {'timeout': 180} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 459786352800039925, success count: 2000, err count: 0  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: Traceback (most recent call last):

[2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2025-07-31T07:12:10.177Z]     res = func(*args, **_kwargs)

[2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 53, in api_request

[2025-07-31T07:12:10.177Z]     return func(*arg, **kwargs)

[2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 429, in load

[2025-07-31T07:12:10.177Z]     conn.load_collection(

[2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler

[2025-07-31T07:12:10.177Z]     raise e from e

[2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler

[2025-07-31T07:12:10.177Z]     return func(*args, **kwargs)

[2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 173, in handler

[2025-07-31T07:12:10.177Z]     return func(self, *args, **kwargs)

[2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 107, in handler

[2025-07-31T07:12:10.177Z]     raise MilvusException(

[2025-07-31T07:12:10.177Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)>

[2025-07-31T07:12:10.177Z]  (api_request.py:35)

[2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)> (api_request.py:36)
```


cluster: 4am
ns: chaos-testing
pods
```
[2025-07-31T07:16:25.292Z] + kubectl get pods -o wide
[2025-07-31T07:16:25.293Z] + grep pulsar-pod-failure-21965
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-0                                   1/1     Running       0               47m     10.104.27.202   4am-node31   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-1                                   1/1     Running       0               47m     10.104.19.240   4am-node28   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-2                                   1/1     Running       0               47m     10.104.30.177   4am-node38   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-nn7qc         1/1     Running       2 (47m ago)     47m     10.104.27.191   4am-node31   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-tg8tl         1/1     Running       2 (47m ago)     47m     10.104.9.3      4am-node14   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-mixcoord-5694b4db6b-lxk8b         1/1     Running       2 (47m ago)     47m     10.104.24.21    4am-node29   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-proxy-768789b57b-zslz7            1/1     Running       2 (47m ago)     47m     10.104.24.20    4am-node29   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-fmphq        1/1     Running       2 (47m ago)     47m     10.104.27.189   4am-node31   <none>           <none>
[2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-m9zbp        1/1     Running       2 (47m ago)     47m     10.104.24.16    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-wf6pk        1/1     Running       2 (47m ago)     47m     10.104.14.202   4am-node18   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-bsxbb    1/1     Running       2 (47m ago)     47m     10.104.24.17    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-xhzbb    1/1     Running       2 (47m ago)     47m     10.104.19.236   4am-node28   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-0                                  1/1     Running       0               47m     10.104.24.24    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-1                                  1/1     Running       0               47m     10.104.27.201   4am-node31   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-2                                  1/1     Running       0               47m     10.104.19.242   4am-node28   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-3                                  1/1     Running       0               47m     10.104.30.179   4am-node38   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-0                        1/1     Running       8 (23m ago)     47m     10.104.27.200   4am-node31   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-1                        1/1     Running       8 (23m ago)     47m     10.104.30.178   4am-node38   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-2                        1/1     Running       8 (23m ago)     47m     10.104.24.27    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-init-v8k2d               0/1     Completed     0               47m     10.104.24.19    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-0                        1/1     Running       8 (22m ago)     47m     10.104.9.8      4am-node14   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-1                        1/1     Running       8 (22m ago)     47m     10.104.14.203   4am-node18   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-0                         1/1     Running       8 (23m ago)     47m     10.104.24.18    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-1                         1/1     Running       8 (23m ago)     47m     10.104.9.6      4am-node14   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-pulsar-init-tbhkx               0/1     Completed     0               47m     10.104.24.22    4am-node29   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-recovery-0                      1/1     Running       8 (23m ago)     47m     10.104.9.7      4am-node14   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-0                     1/1     Running       8 (23m ago)     47m     10.104.27.198   4am-node31   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-1                     1/1     Running       8 (23m ago)     47m     10.104.30.172   4am-node38   <none>           <none>
[2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-2                     1/1     Running       8 (23m ago)     47m     10.104.19.241   4am-node28   <none>           <none>
```

**Comment by zhuwenxing** [comment]
/unassign @zhuwenxing 

/assign @weiliu1031 
PTAL

**Comment by weiliu1031** [comment]
> still reproduced in pulsar pod failure chaos test with `master-20250731-708e426b-amd64`
> 
> failed job: [qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21965/pipeline](https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21965/pipeline) log:
> 
> [artifacts-pulsar-pod-failure-21965-server-logs.tar.gz](https://github.com/user-attachments/files/21525518/artifacts-pulsar-pod-failure-21965-server-logs.tar.gz)
> 
> ```
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[-0.019305144567644355, 0.13534748232492966, 0.11781800861779226, -0.13332264235381044, -0.06931295771854956, 0.0907605343064362, -0.03463697085606006, 0.05015528101180931, -0.10769676260834375, 0.12995878152521737, 0.13536880665986123, 0.08940299953233173, -0.1257463634372558, 0.12210886895467592......, kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 1753944440120805, 'distance': 1.3167352676391602, 'entity': {}}]]  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert search: 0.47228097915649414 (test_all_collections_after_chaos.py:104)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [['Once door job only if. Writer PM reflect avoid memory.\nStandard bag stuff. Meet animal fly news movie marriage strategy measure. Believe window be then apply.\nStep front series vote threat just.'], 'text_sparse_emb', {'metric_type': 'BM25', 'params': {}}, 1, None, None, None, 180, -1], kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 175394571327933, 'distance': 21.254215240478516, 'entity': {}}]]  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert full text search: 0.10006237030029297 (test_all_collections_after_chaos.py:116)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2999}", "{'int64': -2998}", "{'int64': -2997}", "{'int64': -2996}", "{'int64': -2995}", "{'int64': -2994}", "{'int64': -2993}", "{'int64': -2992}", "{'int64': -2991}"] ..., extra_info: {}  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert query result 2000: 0.8938496112823486 (test_all_collections_after_chaos.py:124)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["text_match(document, 'Success bit respond themselves he. Value yet sound decision. Want yes its Mr. Indeed necessary bag effort door word. Father area interesting eye bit. Any drive market now.')", None, None, 180], kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -2999}", "{'int64': -2995}", "{'int64': -2992}", "{'int64': -2991}", "{'int64': -2988}", "{'int64': -2987}", "{'int64': -2986}", "{'int64': -2984}", "{'int64': -2983}", "{'int64': -2980}"] ..., extra_info: {}  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert text match: 0.0317082405090332 (test_all_collections_after_chaos.py:135)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': 0, 'float': 0.31371024, 'varchar': 'evsbfnkgg', 'document': 'They public senior space local increase. Behavior eight through travel.\nAir policy world number cup light marriage. Great black stuff nearly relationship mean.', 'text': 'Rise happy whatever because treatment. Author whose pra......, kwargs: {'timeout': 180} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 459786352800039925, success count: 2000, err count: 0  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: Traceback (most recent call last):
> 
> [2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
> 
> [2025-07-31T07:12:10.177Z]     res = func(*args, **_kwargs)
> 
> [2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 53, in api_request
> 
> [2025-07-31T07:12:10.177Z]     return func(*arg, **kwargs)
> 
> [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 429, in load
> 
> [2025-07-31T07:12:10.177Z]     conn.load_collection(
> 
> [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler
> 
> [2025-07-31T07:12:10.177Z]     raise e from e
> 
> [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler
> 
> [2025-07-31T07:12:10.177Z]     return func(*args, **kwargs)
> 
> [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 173, in handler
> 
> [2025-07-31T07:12:10.177Z]     return func(self, *args, **kwargs)
> 
> [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 107, in handler
> 
> [2025-07-31T07:12:10.177Z]     raise MilvusException(
> 
> [2025-07-31T07:12:10.177Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)>
> 
> [2025-07-31T07:12:10.177Z]  (api_request.py:35)
> 
> [2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)> (api_request.py:36)
> ```
> 
> cluster: 4am ns: chaos-testing pods
> 
> ```
> [2025-07-31T07:16:25.292Z] + kubectl get pods -o wide
> [2025-07-31T07:16:25.293Z] + grep pulsar-pod-failure-21965
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-0                                   1/1     Running       0               47m     10.104.27.202   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-1                                   1/1     Running       0               47m     10.104.19.240   4am-node28   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-2                                   1/1     Running       0               47m     10.104.30.177   4am-node38   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-nn7qc         1/1     Running       2 (47m ago)     47m     10.104.27.191   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-tg8tl         1/1     Running       2 (47m ago)     47m     10.104.9.3      4am-node14   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-mixcoord-5694b4db6b-lxk8b         1/1     Running       2 (47m ago)     47m     10.104.24.21    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-proxy-768789b57b-zslz7            1/1     Running       2 (47m ago)     47m     10.104.24.20    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-fmphq        1/1     Running       2 (47m ago)     47m     10.104.27.189   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-m9zbp        1/1     Running       2 (47m ago)     47m     10.104.24.16    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-wf6pk        1/1     Running       2 (47m ago)     47m     10.104.14.202   4am-node18   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-bsxbb    1/1     Running       2 (47m ago)     47m     10.104.24.17    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-xhzbb    1/1     Running       2 (47m ago)     47m     10.104.19.236   4am-node28   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-0                                  1/1     Running       0               47m     10.104.24.24    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-1                                  1/1     Running       0               47m     10.104.27.201   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-2                                  1/1     Running       0               47m     10.104.19.242   4am-node28   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-3                                  1/1     Running       0               47m     10.104.30.179   4am-node38   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-0                        1/1     Running       8 (23m ago)     47m     10.104.27.200   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-1                        1/1     Running       8 (23m ago)     47m     10.104.30.178   4am-node38   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-2                        1/1     Running       8 (23m ago)     47m     10.104.24.27    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-init-v8k2d               0/1     Completed     0               47m     10.104.24.19    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-0                        1/1     Running       8 (22m ago)     47m     10.104.9.8      4am-node14   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-1                        1/1     Running       8 (22m ago)     47m     10.104.14.203   4am-node18   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-0                         1/1     Running       8 (23m ago)     47m     10.104.24.18    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-1                         1/1     Running       8 (23m ago)     47m     10.104.9.6      4am-node14   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-pulsar-init-tbhkx               0/1     Completed     0               47m     10.104.24.22    4am-node29   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-recovery-0                      1/1     Running       8 (23m ago)     47m     10.104.9.7      4am-node14   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-0                     1/1     Running       8 (23m ago)     47m     10.104.27.198   4am-node31   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-1                     1/1     Running       8 (23m ago)     47m     10.104.30.172   4am-node38   <none>           <none>
> [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-2                     1/1     Running       8 (23m ago)     47m     10.104.19.241   4am-node28   <none>           <none>
> ```
new issue found, schema change blocks target update, will fix it
![Image](https://github.com/user-attachments/assets/b56bece1-3cfa-45e2-838a-b5c906bd7c2d)

**Comment by weiliu1031** [comment]
> > still reproduced in pulsar pod failure chaos test with `master-20250731-708e426b-amd64`
> > failed job: [qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21965/pipeline](https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21965/pipeline) log:
> > [artifacts-pulsar-pod-failure-21965-server-logs.tar.gz](https://github.com/user-attachments/files/21525518/artifacts-pulsar-pod-failure-21965-server-logs.tar.gz)
> > ```
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [[[-0.019305144567644355, 0.13534748232492966, 0.11781800861779226, -0.13332264235381044, -0.06931295771854956, 0.0907605343064362, -0.03463697085606006, 0.05015528101180931, -0.10769676260834375, 0.12995878152521737, 0.13536880665986123, 0.08940299953233173, -0.1257463634372558, 0.12210886895467592......, kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 1753944440120805, 'distance': 1.3167352676391602, 'entity': {}}]]  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert search: 0.47228097915649414 (test_all_collections_after_chaos.py:104)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.search] args: [['Once door job only if. Writer PM reflect avoid memory.\nStandard bag stuff. Meet animal fly news movie marriage strategy measure. Believe window be then apply.\nStep front series vote threat just.'], 'text_sparse_emb', {'metric_type': 'BM25', 'params': {}}, 1, None, None, None, 180, -1], kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_response) : data: [[{'int64': 175394571327933, 'distance': 21.254215240478516, 'entity': {}}]]  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - INFO - ci_test]: assert full text search: 0.10006237030029297 (test_all_collections_after_chaos.py:116)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:56 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ['int64 in [-3000, -2999, -2998, -2997, -2996, -2995, -2994, -2993, -2992, -2991, -2990, -2989, -2988, -2987, -2986, -2985, -2984, -2983, -2982, -2981, -2980, -2979, -2978, -2977, -2976, -2975, -2974, -2973, -2972, -2971, -2970, -2969, -2968, -2967, -2966, -2965, -2964, -2963, -2962, -2961, -2960, -......, kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -3000}", "{'int64': -2999}", "{'int64': -2998}", "{'int64': -2997}", "{'int64': -2996}", "{'int64': -2995}", "{'int64': -2994}", "{'int64': -2993}", "{'int64': -2992}", "{'int64': -2991}"] ..., extra_info: {}  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert query result 2000: 0.8938496112823486 (test_all_collections_after_chaos.py:124)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_request)  : [Collection.query] args: ["text_match(document, 'Success bit respond themselves he. Value yet sound decision. Want yes its Mr. Indeed necessary bag effort door word. Father area interesting eye bit. Any drive market now.')", None, None, 180], kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - DEBUG - ci_test]: (api_response) : data: ["{'int64': -2999}", "{'int64': -2995}", "{'int64': -2992}", "{'int64': -2991}", "{'int64': -2988}", "{'int64': -2987}", "{'int64': -2986}", "{'int64': -2984}", "{'int64': -2983}", "{'int64': -2980}"] ..., extra_info: {}  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:08:57 - INFO - ci_test]: assert text match: 0.0317082405090332 (test_all_collections_after_chaos.py:135)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.insert] args: [[{'int64': 0, 'float': 0.31371024, 'varchar': 'evsbfnkgg', 'document': 'They public senior space local increase. Behavior eight through travel.\nAir policy world number cup light marriage. Great black stuff nearly relationship mean.', 'text': 'Rise happy whatever because treatment. Author whose pra......, kwargs: {'timeout': 180} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_response) : (insert count: 2000, delete count: 0, upsert count: 0, timestamp: 459786352800039925, success count: 2000, err count: 0  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:02 - DEBUG - ci_test]: (api_request)  : [Collection.release] args: [], kwargs: {'timeout': 180} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_response) : None  (api_request.py:27)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:09:04 - DEBUG - ci_test]: (api_request)  : [Collection.load] args: [None, 1, 180], kwargs: {} (api_request.py:52)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: Traceback (most recent call last):
> > 
> > [2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
> > 
> > [2025-07-31T07:12:10.177Z]     res = func(*args, **_kwargs)
> > 
> > [2025-07-31T07:12:10.177Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 53, in api_request
> > 
> > [2025-07-31T07:12:10.177Z]     return func(*arg, **kwargs)
> > 
> > [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/orm/collection.py", line 429, in load
> > 
> > [2025-07-31T07:12:10.177Z]     conn.load_collection(
> > 
> > [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 141, in handler
> > 
> > [2025-07-31T07:12:10.177Z]     raise e from e
> > 
> > [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 137, in handler
> > 
> > [2025-07-31T07:12:10.177Z]     return func(*args, **kwargs)
> > 
> > [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 173, in handler
> > 
> > [2025-07-31T07:12:10.177Z]     return func(self, *args, **kwargs)
> > 
> > [2025-07-31T07:12:10.177Z]   File "/usr/local/lib/python3.10/dist-packages/pymilvus/decorators.py", line 107, in handler
> > 
> > [2025-07-31T07:12:10.177Z]     raise MilvusException(
> > 
> > [2025-07-31T07:12:10.177Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)>
> > 
> > [2025-07-31T07:12:10.177Z]  (api_request.py:35)
> > 
> > [2025-07-31T07:12:10.177Z] [2025-07-31 07:12:04 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=[load_collection] Retry timeout: 180s, message=[wait_for_loading_collection] Retry timeout: 180s, message=wait for loading collection timeout, collection: Checker__F20YGu2B)> (api_request.py:36)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cluster: 4am ns: chaos-testing pods
> > ```
> > [2025-07-31T07:16:25.292Z] + kubectl get pods -o wide
> > [2025-07-31T07:16:25.293Z] + grep pulsar-pod-failure-21965
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-0                                   1/1     Running       0               47m     10.104.27.202   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-1                                   1/1     Running       0               47m     10.104.19.240   4am-node28   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-etcd-2                                   1/1     Running       0               47m     10.104.30.177   4am-node38   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-nn7qc         1/1     Running       2 (47m ago)     47m     10.104.27.191   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-datanode-86df75d77f-tg8tl         1/1     Running       2 (47m ago)     47m     10.104.9.3      4am-node14   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-mixcoord-5694b4db6b-lxk8b         1/1     Running       2 (47m ago)     47m     10.104.24.21    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-proxy-768789b57b-zslz7            1/1     Running       2 (47m ago)     47m     10.104.24.20    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-fmphq        1/1     Running       2 (47m ago)     47m     10.104.27.189   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.293Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-m9zbp        1/1     Running       2 (47m ago)     47m     10.104.24.16    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-querynode-6c76bcccc4-wf6pk        1/1     Running       2 (47m ago)     47m     10.104.14.202   4am-node18   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-bsxbb    1/1     Running       2 (47m ago)     47m     10.104.24.17    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-milvus-streamingnode-6fc77788f9-xhzbb    1/1     Running       2 (47m ago)     47m     10.104.19.236   4am-node28   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-0                                  1/1     Running       0               47m     10.104.24.24    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-1                                  1/1     Running       0               47m     10.104.27.201   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-2                                  1/1     Running       0               47m     10.104.19.242   4am-node28   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-minio-3                                  1/1     Running       0               47m     10.104.30.179   4am-node38   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-0                        1/1     Running       8 (23m ago)     47m     10.104.27.200   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-1                        1/1     Running       8 (23m ago)     47m     10.104.30.178   4am-node38   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-2                        1/1     Running       8 (23m ago)     47m     10.104.24.27    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-bookie-init-v8k2d               0/1     Completed     0               47m     10.104.24.19    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-0                        1/1     Running       8 (22m ago)     47m     10.104.9.8      4am-node14   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-broker-1                        1/1     Running       8 (22m ago)     47m     10.104.14.203   4am-node18   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-0                         1/1     Running       8 (23m ago)     47m     10.104.24.18    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-proxy-1                         1/1     Running       8 (23m ago)     47m     10.104.9.6      4am-node14   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-pulsar-init-tbhkx               0/1     Completed     0               47m     10.104.24.22    4am-node29   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-recovery-0                      1/1     Running       8 (23m ago)     47m     10.104.9.7      4am-node14   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-0                     1/1     Running       8 (23m ago)     47m     10.104.27.198   4am-node31   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-1                     1/1     Running       8 (23m ago)     47m     10.104.30.172   4am-node38   <none>           <none>
> > [2025-07-31T07:16:25.294Z] pulsar-pod-failure-21965-pulsarv3-zookeeper-2                     1/1     Running       8 (23m ago)     47m     10.104.19.241   4am-node28   <none>           <none>
> > ```
> 
> new issue found, schema change blocks target update, will fix it ![Image](https://github.com/user-attachments/assets/b56bece1-3cfa-45e2-838a-b5c906bd7c2d)

<img width="5114" height="892" alt="Image" src="https://github.com/user-attachments/assets/3a8ab60b-c6d1-477f-a8eb-d8fa91ca5991" />

1. the root cause is delegator read unexpected schema version
2. when rootcoord try to update schema in `AddField`, send `schema change` to stream stuck and failed, but finally the `update change` has been write to stream, which cause schema version diff between root coord and stream
3. querycoord get schema version from rootcoord, delegator get schema version from stream, which cause sync distribution failed by `schema version changed`

**Comment by weiliu1031** [comment]
known issue, current ddl frame can't guarantee that ddl changes in stream will always be apply to rc meta successfully, and new ddl framework will fix this. /cc @chyezh

**Comment by weiliu1031** [comment]
> known issue, current ddl frame can't guarantee that ddl changes in stream will always be apply to rc meta successfully, and new ddl framework will fix this. /cc [@chyezh](https://github.com/chyezh)

The temporary solution is to release the collection and then load it again.

**Comment by zhuwenxing** [comment]
image tag `master-20250808-eca51ed2-amd64`

currently, this issue only happened in pulsar pod kill/failure chaos 


failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/22075/pipeline
log:  [artifacts-pulsar-pod-failure-22075-server-logs.tar.gz](https://github.com/user-attachments/files/21725867/artifacts-pulsar-pod-failure-22075-server-logs.tar.gz)


cluster: 4am
ns: chaos-testing
pods
```
pulsar-pod-failure-22075-etcd-0                                   1/1     Running       0               48m     10.104.21.138   4am-node24   <none>           <none>
 pulsar-pod-failure-22075-etcd-1                                   1/1     Running       0               48m     10.104.27.252   4am-node31   <none>           <none>
 pulsar-pod-failure-22075-etcd-2                                   1/1     Running       0               48m     10.104.26.57    4am-node32   <none>           <none>
 pulsar-pod-failure-22075-milvus-datanode-5895cc8597-4nknd         1/1     Running       2 (48m ago)     48m     10.104.18.68    4am-node25   <none>           <none>
 pulsar-pod-failure-22075-milvus-datanode-5895cc8597-pfx97         1/1     Running       2               48m     10.104.6.42     4am-node13   <none>           <none>
 pulsar-pod-failure-22075-milvus-mixcoord-7997db6588-kndzl         1/1     Running       2 (48m ago)     48m     10.104.6.41     4am-node13   <none>           <none>
 pulsar-pod-failure-22075-milvus-proxy-7f8d9c74d6-4nmqk            1/1     Running       2 (48m ago)     48m     10.104.26.51    4am-node32   <none>           <none>
 pulsar-pod-failure-22075-milvus-querynode-78fc799b9b-2flh7        1/1     Running       2 (48m ago)     48m     10.104.33.71    4am-node36   <none>           <none>
 pulsar-pod-failure-22075-milvus-querynode-78fc799b9b-6h2nn        1/1     Running       2 (48m ago)     48m     10.104.20.119   4am-node22   <none>           <none>
 pulsar-pod-failure-22075-milvus-querynode-78fc799b9b-8dskl        1/1     Running       2 (48m ago)     48m     10.104.19.241   4am-node28   <none>           <none>
 pulsar-pod-failure-22075-milvus-streamingnode-7d4576d44f-5hh69    1/1     Running       2 (48m ago)     48m     10.104.26.53    4am-node32   <none>           <none>
 pulsar-pod-failure-22075-milvus-streamingnode-7d4576d44f-m4zlm    1/1     Running       2 (48m ago)     48m     10.104.27.247   4am-node31   <none>           <none>
 pulsar-pod-failure-22075-minio-0                                  1/1     Running       0               48m     10.104.32.86    4am-node39   <none>           <none>
 pulsar-pod-failure-22075-minio-1                                  1/1     Running       0               48m     10.104.21.136   4am-node24   <none>           <none>
 pulsar-pod-failure-22075-minio-2                                  1/1     Running       0               48m     10.104.24.23    4am-node29   <none>           <none>
 pulsar-pod-failure-22075-minio-3                                  1/1     Running       0               48m     10.104.16.172   4am-node21   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-bookie-0                        1/1     Running       8 (24m ago)     48m     10.104.27.3     4am-node31   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-bookie-1                        1/1     Running       8 (23m ago)     48m     10.104.33.81    4am-node36   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-bookie-2                        1/1     Running       8 (24m ago)     48m     10.104.26.60    4am-node32   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-bookie-init-xpqd8               0/1     Completed     0               48m     10.104.32.83    4am-node39   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-broker-0                        1/1     Running       8 (23m ago)     48m     10.104.13.163   4am-node16   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-broker-1                        1/1     Running       8 (23m ago)     48m     10.104.14.142   4am-node18   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-proxy-0                         1/1     Running       8 (24m ago)     48m     10.104.32.82    4am-node39   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-proxy-1                         1/1     Running       8 (24m ago)     48m     10.104.21.130   4am-node24   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-pulsar-init-kxlwf               0/1     Completed     0               48m     10.104.21.131   4am-node24   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-recovery-0                      1/1     Running       8 (23m ago)     48m     10.104.14.143   4am-node18   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-zookeeper-0                     1/1     Running       8 (24m ago)     48m     10.104.21.135   4am-node24   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-zookeeper-1                     1/1     Running       8 (24m ago)     48m     10.104.27.251   4am-node31   <none>           <none>
 pulsar-pod-failure-22075-pulsarv3-zookeeper-2                     1/1     Running       8 (23m ago)     48m     10.104.33.75    4am-node36   <none>           <none>
```

**Comment by yanliang567** [comment]
@weiliu1031 please help to take a look again

**Comment by weiliu1031** [comment]
> [@weiliu1031](https://github.com/weiliu1031) please help to take a look again

<img width="2546" height="586" alt="Image" src="https://github.com/user-attachments/assets/391d8506-2d9a-4eed-8dff-9bb6fc7cb33b" />
