### ISSUE TITLE
[Bug]: query with filter "geo IS NOT NULL" on nullable geometry field returns MilvusException: EOF

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#44648]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2025-09-30T07:50:54Z {container="step-test"} [2025-09-30 07:50:42 - DEBUG - ci_test]: (api_request)  : [MilvusClient.query] args: ['test_create_collection_with_nullable_geometry_field__X6wx8cC4'], kwargs: {'filter': 'geo IS NOT NULL', 'output_fields': ['id', 'geo'], 'timeout': 120} (api_request.py:52)
2025-09-30T07:50:54Z {container="step-test"} [2025-09-30 07:50:42 - ERROR - ci_test]: Traceback (most recent call last):
2025-09-30T07:50:54Z {container="step-test"} File "/milvus/tests/python_client/utils/api_request.py", line 22, in inner_wrapper
2025-09-30T07:50:54Z {container="step-test"} res = func(*args, **_kwargs)
2025-09-30T07:50:54Z {container="step-test"} File "/milvus/tests/python_client/utils/api_request.py", line 53, in api_request
2025-09-30T07:50:54Z {container="step-test"} return func(*arg, **kwargs)
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 492, in query
2025-09-30T07:50:54Z {container="step-test"} raise ex from ex
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/milvus_client/milvus_client.py", line 481, in query
2025-09-30T07:50:54Z {container="step-test"} res = conn.query(
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 141, in handler
2025-09-30T07:50:54Z {container="step-test"} raise e from e
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 137, in handler
2025-09-30T07:50:54Z {container="step-test"} return func(*args, **kwargs)
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 173, in handler
2025-09-30T07:50:54Z {container="step-test"} return func(self, *args, **kwargs)
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 116, in handler
2025-09-30T07:50:54Z {container="step-test"} raise e from e
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/decorators.py", line 86, in handler
2025-09-30T07:50:54Z {container="step-test"} return func(*args, **kwargs)
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 1724, in query
2025-09-30T07:50:54Z {container="step-test"} check_status(response.status)
2025-09-30T07:50:54Z {container="step-test"} File "/usr/local/lib/python3.10/site-packages/pymilvus/client/utils.py", line 67, in check_status
2025-09-30T07:50:54Z {container="step-test"} raise MilvusException(status.code, status.reason, status.error_code)
2025-09-30T07:50:54Z {container="step-test"} pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=EOF)>
2025-09-30T07:50:54Z {container="step-test"} (api_request.py:35)
2025-09-30T07:50:54Z {container="step-test"} [2025-09-30 07:50:42 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=EOF)> (api_request.py:36)
```

### Steps To Reproduce

```markdown

```

### Milvus Log

failed ci job: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-44646/2/pipeline/101

**Comment by xiaocai2333** [comment]
If the value is `null` during insertion, it will be omitted instead of being filled with nil. Therefore, when performing checks, there’s no need to retrieve data based on the valid offset.

**Comment by xiaocai2333** [comment]
fixed. please verify
/assign @zhuwenxing

**Comment by zhuwenxing** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-44383/25/pipeline/

this issue can still reproduced in ci


looks like https://github.com/milvus-io/milvus/pull/44911 this fix was not cp to 2.5

**Comment by xiaocai2333** [comment]
- Please add more test scenarios, such as:

  - Growing + No Index / With Index

  - Flushed + No Index / With Index

@zhuwenxing  thx

**Comment by xiaocai2333** [comment]
close this, if new bugs are found, should be created new issue.
/close
