### ISSUE TITLE
[Bug]: [Nightly] The search results using json path index are empty after flush

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#45670]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7aed881
- Deployment mode(standalone or cluster):cluster
- MQ type(rocksmq, pulsar or kafka):    kafka
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The search results using json path index are empty after flush.

case: test_milvus_client_search_json_path_index_before_load
link: https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20Nightly%20CI(new)/detail/master/537/pipeline/98
error message: 
```
2025-11-17T23:17:14Z {container="step-test"} [2025-11-17 21:30:51 - DEBUG - ci_test]: (api_request)  : [MilvusClient.search] args: ['test_milvus_client_search_json_path_index_before_load__Yk691qHO', [[0.030737286652583802, -0.1167376786882127, -0.002816469842300763, 0.12542261304395985, 0.05186732080319336, 0.12884371191029143, -0.07468249492651163, 0.10117728677694347, 0.0784335564570161, -0.12411935413596965, -0.1032173103526......, kwargs: {'consistency_level': 'Strong', 'timeout': 120} (api_request.py:52)
2025-11-17T23:17:14Z {container="step-test"} [2025-11-17 21:30:51 - DEBUG - ci_test]: (api_response) : data: [[]]  (api_request.py:27)
2025-11-17T23:17:14Z {container="step-test"} [2025-11-17 21:30:51 - INFO - ci_test]: search_results_check: checking the searching results (func_check.py:418)
2025-11-17T23:17:14Z {container="step-test"} [2025-11-17 21:30:51 - INFO - ci_test]: search_results_check: Numbers of query searched is correct (func_check.py:444)
2025-11-17T23:17:14Z {container="step-test"} [2025-11-17 21:30:51 - ERROR - ci_test]: search_results_check: limit(topK) searched (0) is not equal with expected (10) (func_check.py:459)
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown

```

**Comment by yanliang567** [comment]
looks like a dup to #45575 
/unassign

**Comment by NicoYuan1986** [comment]
fixed.

**Comment by yanliang567** [comment]
@NicoYuan1986 I think the test class was skipped for now to unlock pr merging. The issue still need investigation and fix

**Comment by NicoYuan1986** [comment]
reproduce on weekly e2e:
case name: test_milvus_client_search_json_path_index_before_load
https://qa-jenkins.milvus.io/blue/organizations/jenkins/E2E%20Test/detail/E2E%20Test/1821/pipeline/

**Comment by NicoYuan1986** [comment]
reproduce
@sunby 
https://qtp.zilliz.cc/run/report?id=14658&region=awswest&image=v2.6.8-67e4a21f8-3078%282.6.8-20260104-67e4a21f8-f778c88%29
case name: test_milvus_client_search_json_path_index_default

**Comment by xiaofan-luan** [comment]
Let's priority this issue since this is a correctness issue

**Comment by sunby** [comment]
this test built flat index for `json['a']` and `json['a'][0]` with cast type `JSON`. If `json['a']`  index is loaded and `json['a'][0]` index building is not finished, milvus will use `json['a']` index and path `a/0` does not exist in flat index.

we discussed about using refine after search to resolve the problem that query like `json['array'] == 1` returns much more records than expected but it's not useful in this case because the result is empty so no data can be refined.

**Comment by sunby** [comment]
@zhengbuqian @xiaofan-luan do you have any suggestions for this issue?
