### ISSUE TITLE
Milvus is crashed when search specify vector as output_field

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#5992]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
Milvus is crashed when specify vector as output_field

**Steps/Code to reproduce behavior**
Code:
from pymilvus_orm import CollectionSchema, FieldSchema
from pymilvus_orm import Collection
from pymilvus_orm import connections
from pymilvus_orm.types import DataType

int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
connections.connect()
import numpy as np
collection = Collection("test_search_collection_binbin_6", schema=schema)
dim = 128
nb = 3000
nq = 1
limit = 1000
import random
default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
collection.load()
res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["float_vector"])

Addr [...] _execute_search_requests
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624360619.217552600","description":"Error received from peer ipv4:....","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-22 11:16:59.142607', 'RPC start': '2021-06-22 11:16:59.143092', 'RPC error': '2021-06-22 11:16:59.219226'}

**Expected behavior**
Milvus is not crashed (report error or support vector as output_field)

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Software conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)
milvus: master
Name: pymilvus
Version: 2.0a1.dev43
Name: pymilvus-orm
Version: 2.0a1.dev43

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by czs007** [comment]
currently ,we do not support specify vector field as output_field. @binbinlv  @FluorineDog  @fishpenguin

**Comment by binbinlv** [comment]
> currently ,we do not support specify vector field as output_field. @binbinlv @FluorineDog @fishpenguin

Yes, but I think tell user something like "do not support currently" is better than crash of milvus. May be need improvement here. @czs007

**Comment by czs007** [comment]
> > currently ,we do not support specify vector field as output_field. @binbinlv @FluorineDog @fishpenguin
> 
> Yes, but I think tell user something like "do not support currently" is better than crash of milvus. An improvement may be needed here. @czs007

u r right. @FluorineDog  @fishpenguin  can we return an error code ?

**Comment by fishpenguin** [comment]
I know this issue, but I'm strruggling if the vector field value should be returned or just return an error code?
I really think the vector field should be returned, but I cannot judge how much the work is, and this may need @FluorineDog's help.?

**Comment by yanliang567** [comment]
for 2.0.0RC1, return an error msg

**Comment by fishpenguin** [comment]
Already fixed.

**Comment by binbinlv** [comment]
It is still not good with this error. But the connection and server is good this time. Other operations could be done like "collection.partitions". 

If I run search with vector as output field again, it is stuck (hunging).

@fishpenguin  could you please have a look? Thanks.

milvus-master
Name: pymilvus
Version: 2.0a1.dev52
Name: pymilvus-orm
Version: 2.0a1.dev58

>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["float_vector"])

Addr [172.18.255.155:19530] _execute_search_requests
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624701666.376341749","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-26 10:01:06.340131', 'RPC start': '2021-06-26 10:01:06.340944', 'RPC error': '2021-06-26 10:01:06.377547'}

Addr [172.18.255.155:19530] search_with_expression
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624701666.376341749","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-26 10:01:06.324719', 'RPC start': '2021-06-26 10:01:06.328821', 'RPC error': '2021-06-26 10:01:06.377786

>>> c=Milvus("172.18.255.155")
>>>
>>>
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
>>>
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["float_vector"])
[It is stuck here]

**Comment by fishpenguin** [comment]
Fixed in [pr6145](https://github.com/milvus-io/milvus/pull/6145)

**Comment by binbinlv** [comment]
Not fixed yet: (the result is the same with last comment)

milvus master: effcbc7
Name: pymilvus
Version: 2.0a1.dev53
Name: pymilvus-orm
Version: 2.0a1.dev59

>>> from pymilvus_orm import CollectionSchema, FieldSchema
>>> from pymilvus_orm import Collection
>>> from pymilvus_orm import connections
>>> from pymilvus_orm.types import DataType
>>> int64_field = FieldSchema(name="int64", dtype=DataType.INT64, is_primary=True)
>>> float_field = FieldSchema(name="float", dtype=DataType.FLOAT)
>>> float_vector = FieldSchema(name="float_vector", dtype=DataType.FLOAT_VECTOR, dim=128)
>>> schema = CollectionSchema(fields=[int64_field, float_field, float_vector])
>>> connections.connect(host="172.18.255.155", port="19530")
<pymilvus.client.stub.Milvus object at 0x7fd1f5cca9b0>
>>>
>>>
>>> import numpy as np
>>> collection = Collection("test_search_collection_binbin_6", schema=schema)
>>> dim = 128
>>> nb = 3000
>>> nq = 1
>>> limit = 1000
>>> import random
>>> default_search_params = {"metric_type": "L2", "params": {"nprobe": 10}}
>>> vectors = [[random.random() for _ in range(dim)] for _ in range(nb)]
>>> res = collection.insert([[i for i in range(nb)], [np.float32(i) for i in range(nb)], vectors])
>>> collection.partitions
[{"name": "_default", "description": "", "num_entities": 3000}]
>>>
>>> collection.load()
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["float_vector"])

Addr [172.18.255.155:19530] _execute_search_requests
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624848102.433526000","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-28 02:41:42.383954', 'RPC start': '2021-06-28 02:41:42.384940', 'RPC error': '2021-06-28 02:41:42.434906'}

Addr [172.18.255.155:19530] search_with_expression
RPC error: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1624848102.433526000","description":"Error received from peer ipv4:172.18.255.155:19530","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>
	{'API start': '2021-06-28 02:41:42.356610', 'RPC start': '2021-06-28 02:41:42.358087', 'RPC error': '2021-06-28 02:41:42.435242'}

**Comment by binbinlv** [comment]
Verified, it is fixed.

milvus: master b27e6b5

Results:
>>> res = collection.search(vectors[:nq], "float_vector", default_search_params, limit, "int64 >= 0", output_fields=["float_vector"])
Error: <BaseException: (code=1, message=Search doesn't support vector field as output_fields)>
