### ISSUE TITLE
Stuck in collection.load()

### ISSUE THREAD

**Issue by xuqinkun** [milvus-io/milvus#6401]
**Describe the bug**
I modified the function fvec_L2sqr_avx in distances_simd_avx.cpp, and rebuild the source code. After replacing the lib directory in the docker mirror. The test code always stuck in the ollection.load().

![image](https://user-images.githubusercontent.com/19572081/125031004-93063e00-e0be-11eb-8e25-d7c2bc4aa389.png)

Function fvec_L2sqr_avx change to:
float fvec_L2sqr_avx (const float* x, const float* y, size_t d) {
    float x_plus = calc_nplusone_dim(x, d);
    float y_plus = calc_nplusone_dim(y, d);
    float mul = fvec_mult(x, y, d);
    float ip = mul - x_plus * y_plus;

    ofstream logfile;
    logfile.open ("/tmp/log_vec.txt", ios::out);
    logfile << "x_vec = ";
    log(logfile, x);
    logfile << "y_vec = ";
    log(logfile, y);
    myfile << "x_plus=" << x_plus << endl;
    myfile << "y_plus=" << mul << endl;
    myfile << "ip=" << ip << endl;
    logfile.close();

    return log(ip + sqrt(ip * ip- 1));
}

void log(ofstream out, const float* x) {
    logfile << "[";
    for (float *it = x; it < x + d < it++) {
        logfile << *it;
        if (it != x + d - 1) {
            logfile << ",";
        } else {
            logfile << "]";
        }
    }
    logfile << endl;
}

float fvec_mult(const float*x, const float* y, size_t d) {
    __m256 msum1 = _mm256_setzero_ps();

    while (d >= 8) {
        __m256 mx = _mm256_loadu_ps (x); x += 8;
        __m256 my = _mm256_loadu_ps (y); y += 8;        
        msum1 += mx * my;
        d -= 8;
    }

    __m128 msum2 = _mm256_extractf128_ps(msum1, 1);
    msum2 +=       _mm256_extractf128_ps(msum1, 0);

    if (d >= 4) {
        __m128 mx = _mm_loadu_ps (x); x += 4;
        __m128 my = _mm_loadu_ps (y); y += 4;        
        msum2 += mx * my;
        d -= 4;
    }

    if (d > 0) {
        __m128 mx = masked_read (d, x);
        __m128 my = masked_read (d, y);
        msum2 += mx * my;
    }

    msum2 = _mm_hadd_ps (msum2, msum2);//a0=a0+a1;a1=a2+a3
    msum2 = _mm_hadd_ps (msum2, msum2);//a0=a0+a1
    return  _mm_cvtss_f32 (msum2);// return a0
}

// The extended dim(n+1)
float calc_nplusone_dim(const float *x, size_t d) {
    __m256 msum1 = _mm256_setzero_ps();

    while (d >= 8) {
        __m256 mx = _mm256_loadu_ps (x); x += 8;        
        msum1 += mx * mx;
        d -= 8;
    }

    __m128 msum2 = _mm256_extractf128_ps(msum1, 1);
    msum2 +=       _mm256_extractf128_ps(msum1, 0);

    if (d >= 4) {
        __m128 mx = _mm_loadu_ps (x); x += 4;
        msum2 += mx * mx;
        d -= 4;
    }

    if (d > 0) {
        __m128 mx = masked_read (d, x);        
        msum2 += mx * mx;
    }

    msum2 = _mm_hadd_ps (msum2, msum2);  // a0=a0+a1;a1=a2+a3
    msum2 = _mm_hadd_ps (msum2, msum2);  // a0=a0+a1

    return  _mm_cvtss_f32 (msum2) + 1.0; // return a0 + 1
}

**Method of installation**
- [x] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
MacOS

- Milvus version (master or released version)
2.0

**Configuration file**
Default

```yaml
Default
```

**Comment by xiaofan-luan** [comment]
did you meet the same issue if you deploy the code directly?

**Comment by xuqinkun** [comment]
> did you meet the same issue if you deploy the code directly?

No, it's normal before I replace the libs

**Comment by xuqinkun** [comment]
![image](https://user-images.githubusercontent.com/19572081/125048097-28f79400-e0d2-11eb-8e03-29f5c1387502.png)


Directory lib is the replaced lib. How can I debug the new function or generate a coredump

**Comment by xiaofan-luan** [comment]
@cydrain we need a guide on how to develop and run unit test, would you mind help on this?

**Comment by xuqinkun** [comment]
> @cydrain we need a guide on how to develop and run unit test, would you mind help on this?

You can clone my code: https://github.com/xuqinkun/milvus, and just compile the internal/core

**Comment by xuqinkun** [comment]
I try to replace the lib and don't change any code, the problem still happened.

**Comment by xuqinkun** [comment]
> @xuqinkun which branch ?
develop
I try to replace the lib and don't change any code, the problem still happened. So I think the process of changing lib make some problem.

**Comment by xuqinkun** [comment]
@cydrain develop
I try to replace the lib and don't change any code, the problem still happened. So I think the process of changing lib make some problem.

**Comment by cydrain** [comment]
@cydrain How you change the lib ?

**Comment by xuqinkun** [comment]
@cydrain Use the docker cp command, the lib is compiled in Ubuntu

**Comment by cydrain** [comment]
@xuqinkun which Ubuntu version ?

**Comment by xuqinkun** [comment]
@cydrain ubuntu1~16.04.10
I tried, but as the issue https://github.com/milvus-io/milvus/issues/6332 saied, I can't start the components normally. I don't know why. All the steps is based on the doc https://github.com/milvus-io/milvus#to-start-developing-milvus

**Comment by cydrain** [comment]
@xuqinkun the docker image is build with ubuntu 18.04

**Comment by xuqinkun** [comment]
@cydrain You mean the docker image only supports ubuntu 18.04?

**Comment by cydrain** [comment]
@xuqinkun The system running in the docker image we released is Ubuntu 18.04, and all Milvus related binaries in this docker image are also build on Ubuntu 18.04.
You can try build your lib in the docker image, then replace the original one.

**Comment by xuqinkun** [comment]
@cydrain Ok, I understand it.

**Comment by xuqinkun** [comment]
@cydrain I tried build the lib in the docker image, the problem still happened.

**Comment by cydrain** [comment]
@xuqinkun show me your branch, let me have a try

**Comment by xuqinkun** [comment]
@cydrain develop    https://github.com/xuqinkun/milvus

**Comment by xuqinkun** [comment]
@cydrain How's it going?

**Comment by cydrain** [comment]
@xuqinkun
Here is the document how to use docker to build Milvus, hope it can help.
https://github.com/milvus-io/milvus/tree/master/build
