### ISSUE TITLE
Use multi-threads to improve getEntityById performance

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus#6684]
#### What would you like to be added:
Use multi-threads to improve getEntityById performance

#### Why is this needed:
When input ids is large array, the performance of getEntityById is not good

**Comment by yhmo** [comment]
Fixed by #6310

**Comment by SuoSiFire** [comment]
I recompiled the fixed version, but the performance still doesn't look good. It takes 10 minutes for me to get 10w  vector data with a batch size of 1k.  
@yhmo
