### ISSUE TITLE
Error message could be more accurate for invalid vectors of calc_distance interface

### ISSUE THREAD

**Issue by binbinlv** [milvus-io/milvus#7038]
#### Steps/Code to reproduce:
```python
from pymilvus_orm import connections
from pymilvus_orm import utility
import random
connections.connect()
op_l = "12-s"
op_r = "12-s"
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
op_l = {1: 1}
op_r = {1: 1}
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
op_l = {"float_vectors": vectors_l}
op_r = "12-s"
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
op_l = {"float_vectors": vectors_l}
op_r = {1: 1}
results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
```

#### Expected result:
(1) not required type (dict):  `vectors_left ` value {} is **illegal**
(2) is dict type, but invalid value: `vectors_left ` value {} is **invalid**

#### Actual results:
for left vectors:
(1) not required type (dict):  Left vectors array is invalid
(2) is dict type, but invalid value: Left vectors array is empty **[Here left vectors are not empty]**

for right vectors:
(1) not required type (dict):  Right vectors array is invalid
(2) is dict type, but invalid value:Cannot calculate distance between vectors with different dimension **[Here maybe need params check before check dimension]**

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93): bdb8396
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
Name: pymilvus
Version: 2.0.0rc3.dev16
Name: pymilvus-orm
Version: 2.0.0rc3.dev15
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

**Comment by yhmo** [comment]
Fixed by https://github.com/milvus-io/pymilvus/pull/647

**Comment by binbinlv** [comment]
Now scenario (1) and (3) has been fixed.
(1) not required type (dict) for left vectors: vectors_left value {} is illegal
(3) not required type (dict) for right vectors: vectors_right value {} is illegal

pymilvus: Version: 2.0.0rc5.dev19

**Comment by binbinlv** [comment]
Scenario (2) and (4) are not fixed: the error messages are still not accurate

Scenario (2): left vectors do not have the right key
Left vectors array is empty [Here left vectors are not empty], I think op_l = {} this is empty.
```
>>> op_r = {"float_vector_binbin": 1}
>>> op_l = {"float_vector_binbin": 1}
>>> results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
Error: <BaseException: (code=1, message=Left vectors array is empty)>
```

Scenario (4):  right vectors do not have the right key
```
>>> op_l = {"float_vectors": vectors_l}
>>> op_r = {"float_vectors_binbin": vectors_l}
>>> results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
pymilvus.client.exceptions.ParamError: Cannot calculate distance between vectors with different dimension
```

**Comment by yhmo** [comment]
Fixed by milvus-io/pymilvus#655

**Comment by binbinlv** [comment]
Verified and fixed.

Name: pymilvus
Version: 2.0.0rc5.dev22

Results:
```
>>> op_l = {1: 1}
>>> op_r = {1: 1}
...
pymilvus.client.exceptions.ParamError: vectors_left value {1: 1} is illegal
```

```
>>> op_l = {"float_vectors": vectors}
>>> op_r = {1: 1}
>>> results = utility.calc_distance(vectors_left=op_l, vectors_right=op_r)
...
vectors_right value {1: 1} is illegal
```
